core/databases/app_defaults.php

Use long string syntax to generate `config.lua` file.

---

app/fax/fax_send.php

* tiffXXX utils did not work with paths like `C:/xxx/ddd.tif`
* using `gswin32c` instead of `gs`
* using `copy` function instead of `cp` command

Fix. Send fax via web on Windows.

---

resources/install/scripts/app/voicemail/resources/functions/macro.lua

Current implementation produces not correct phrases e.g. on Russian language.

Change. Use predefined phrases in vm menu.

---

resources/install.php

On my Windows machine default domain now is `127.0.0.1` which is quite useless.

Add. Allow edit domain name while installing.

---

app/registrations/status_registrations_inc.php

When on profile set `force-register-db-domain` realm on xmlstatus is just IP but user is like 101@domain.name.

Fix. Show registrations to sip profile with force-XXX-domain.

---

core/databases/app_defaults.php

It needs because on windows FreeSWITCH builds without native support PostgreSQL.

Change. Use odbc connector if there exists odbc database

---

app/sip_profiles/sip_profile_edit.php
resources/switch.php

Disable of sip profile does not work

---

app/services/resources/classes/lib_win.php
app/services/service_edit.php
app/services/services.php

Require php_win32service.
Tested on WAMP 2.2 on WinXP/Win2k3

Add. Support windows services.

---

app/calls/resources/classes/follow_me.php

Problem is that php code clear `dial_string` field in DB.
And Lua code on enable try use it.

Fix. Can not enable follow me via `*21` if it was disabled via web.

---

app/calls/resources/classes/call_forward.php
app/calls/resources/classes/follow_me.php
resources/install/scripts/call_forward.lua

Use toll_allow of extension who set call forward/follow me.

Set Toll Allow for call forward/follow me

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

This replaces `inbound-reg-force-matching-username` profile option.
So if your extension has number-alias you can use
UserID=number-alias
AuthID=Extension
It also supports such check on INVITE not only on REGISTER.

Fix. Verify number-alias and user id.

---

resources/install/scripts/app/ring_groups/index.lua

Fix. Always use record dir with domain name like it does `user_record` extension.

Fix. Start recording only after call start and only for certain extension

---

resources/templates/provision/yealink/cp860/{$mac}.cfg

{$mac}.cfg

---

app/calls/call_edit.php
app/devices/app_languages.php
app/ring_groups/app_languages.php
app/ring_groups/ring_group_edit.php
app/voicemail_greetings/voicemail_greetings.php
resources/install/scripts/app/ring_groups/index.lua
resources/install/scripts/ring_member.lua

This adds the random strategy to the ring groups, its simply does an order by random in the SQL when selecting the members of the group. It should support mysql and postgresql (though I only tested it in psql).
Also included is a lua script for entering/leaving a ring group, the code is based on the fifo_member.lua and needs a dialplan entry like in the queues.

Random ring groups

---

resources/install/scripts/resources/functions/cache.lua

Fix. cache.set returns boolean value.
Add. basic self_test

Fix. `cache.del` method.

---

resources/install/scripts/app/voicemail/resources/functions/message_waiting.lua

rather big debug message when storing base64 coded voicemail messages...

Fix. suppress debug messages

---

app/xml_cdr/xml_cdr.php

width option was missing to support high res images

prepared img tag for high resolution (retina) images

---

app/fifo/app_menu.php
app/follow_me/app_menu.php

translations for some menu items

latest german translations

---

app/provision/index.php

fixed provisioning with http_domain_filter off

---

resources/install/scripts/app/ring_groups/index.lua

see https://github.com/moteus/fusionpbx/commit/e5a0134ec6c36e44d0828301b20c9c194c25cd78#commitcomment-13601198

Fix. use timeout handler in Enterprise ring group

---

resources/install/scripts/resources/functions/database.lua

This is one more basic class.
```Lua
local Database = require "resources.functions.database"
local dbh = Database.new('system')
--get the domain_uuid
if (domain_uuid == nil) and (domain_name ~= nil) then
local sql = "SELECT domain_uuid FROM v_domains "
sql = sql .. "WHERE domain_name='" .. domain_name .. "';"
domain_uuid = dbh:first_value(sql)
end
local dbh_switch = Database.new('switch') -- check also SQLite file.
local row = dbh_switch:first_row(sql)
if row then
...
end
```

Add. database class

---

app/calls/call_edit.php
app/calls/resources/classes/call_forward.php
app/calls/resources/classes/follow_me.php
app/extensions/extension_edit.php

Currently extension uses Outbound Caller ID Number, but Call Forward/Follow Me uses Destination number.

Fix. Use same Outbound Caller info in extenstion and call control.

---

resources/install/scripts/resources/functions/cache.lua

I think better move `load_balance` in to `config.lua` or `local.lua` file so it will be possible easy configure it and also allows check this flag in other places not only in directory.

Add. `cache` class emit MEMCACHE events.

---

core/databases/app_defaults.php
resources/install/scripts/app/xml_handler/resources/scripts/languages/languages.lua

changed phrases_dir to be dealt with inside app_defaults.php so it is retrieved once like the other paths

fix to use phrases_dir

---

app/time_conditions/app_defaults.php
app/time_conditions/time_condition_edit.php

migrates existing presets to be preset_usa and make that the default region and added england holidays

Enhance time conditions

---

resources/install/scripts/intercept.lua

This is same changes as in #1209.

Fix. Call intercept - a scenario where an outgoing call can be intercepted

---

app/fax/fax_emails.php
app/fax/fax_send.php

Fix. require EventSocket implicitly.
Fix. require `test` class.

Fix. multiple calls fax_send caused error.

---

app/sip_profiles/app_defaults.php
app/sip_profiles/resources/xml/sip_profiles/external-ipv6.xml
resources/templates/conf/sip_profiles/external-ipv6.xml.noload

Added External IPv6 sip_profile

Enhance sip profiles

---

app/provision/app_defaults.php
app/provision/resources/classes/provision.php

BugFix to respect http_domain_filter when auto creating
setting provision> directory_extensions populates $extensions as a
contacts array in provisioning

BugFix + Optional Enable extensions appear in directory

---

core/databases/app_defaults.php
core/install/index.php
core/install/install_first_time.php
core/install/resources/classes/install_fusionpbx.php
core/install/resources/classes/install_switch.php
core/install/resources/page_parts/install_config_database.php
core/install/resources/page_parts/install_config_detail.php
core/install/resources/page_parts/install_event_socket.php
core/upgrade/app_defaults.php
core/upgrade/index.php

@todo
-[ ] Track down why app_defaults are not getting run correctly

Bugfix ft install

---

resources/switch.php

Tested on WAMP and OpenServer.

Fix. Use wrapper bat file to v_malito.php on Windows.

---

app/emails/app_languages.php
app/fax/app_config.php
app/fax/fax_send.php
resources/install/scripts/app/fax/resources/scripts/queue/next.lua
resources/install/scripts/app/fax/resources/scripts/queue/retry.lua
resources/install/scripts/app/fax/resources/scripts/queue/tasks.lua
secure/fax_to_email.php

For now it send only basic messages on success/fail.

Add. Send reply message after fax task done.

---

core/install/resources/classes/global_settings.php
core/install/resources/classes/install_fusionpbx.php
core/install/resources/classes/install_switch.php

Bugfix install

---

core/install/install_first_time.php
core/install/resources/classes/install_fusionpbx.php
core/install/resources/classes/install_switch.php

this should fix upgrading switch scripts causing a non redirect in chrome

added suppression of progress by default

---

app/fax/fax_edit.php
app/fax/fax_files.php
app/fax/fax_files_remote.php
app/fax/fax_send.php
app/fax/resources/classes/fax.php

To upgrade need move fax failes to path with domain name and resave fax server to change path in dialplan extension

Change. Use path with domain name for faxes for single tenant installation.

---

app/system/app_languages.php
app/system/system.php

tweaks to the system information display

Enhance app system

---

core/install/resources/classes/global_settings.php

this would have also affected backup_dir

Fixed temp_dir not getting set correctly

---

app/system/app_languages.php
app/system/system.php
core/install/resources/classes/detect_switch.php

will now work with both git and packaged version numbers
added bits to detect_switch

Updated switch version detection

---

app/voicemails/resources/classes/voicemail.php

Fix. Play voicemail.

---

app/system/system.php
core/install/resources/classes/detect_switch.php

corrected collection of switch version during detect_switch

patch for SunOS

---

index.php

see - https://github.com/fusionpbx/fusionpbx/issues/1284

Go to User Dashboard if it is present

---

app/dialplan/resources/switch/conf/dialplan/290_intercept-ext-polycom.xml

first dialplan to be utilized as global="true" and
context="${domain_name}"

Intercept mode for Polycom

---

app/calls_active/calls_active_inc.php

Problem that when you have large app data (>7k in my case)
it takes over 2 pages to display only single channel.

Change. Reduce too long app data in active calls app.

---

app/operator_panel/index_inc.php

This make problems with numbers starting with `0` e.g. (001)
Also this makes problem with too long numbers which does not fit to int type.

Fix. Do not cast dialed number to int in `Operator Panel` app.

---

resources/install/scripts/app/voicemail/resources/functions/send_email.lua

cherry picked version of https://github.com/fusionpbx/fusionpbx/pull/1351

cherry picked changes from 4.0 branch

---

index.php

added missing / in path and set redirect correctly

BugFix-Dashboard_Redirect

---

resources/install/scripts/app/voicemail/resources/functions/send_email.lua

Reverts fusionpbx/fusionpbx#1355

Revert "cherry picked changes from 4.0 branch"

---

resources/templates/provision/yealink/cp860/y000000000037.cfg

found one more directory setting url that was missing the _

fix another directory setting url

---

app/xml_cdr/v_xml_cdr_import.php

wrong variable, use the correct one.

Bill the incoming call

---

app/devices/device_edit.php

changed protocol to match request

BugFix to app/devices

---

resources/install/scripts/app/xml_handler/resources/scripts/languages/languages.lua

removed extra ;'s
fix file_handle:close to be inside the if null check

BugFixes in languages.lua

---

app/devices/device_edit.php

values were being assigned rather than compared

BugFix-app/devices

---

app/operator_panel/index.php

fix for when the element is not in the document yet

BugFix Operator Panel

---

app/phrases/resources/functions/save_phrases_xml.php

not the name.domain_uuid format

phrases should be written out as there uuid

---

resources/install/scripts/app/ring_groups/index.lua
resources/install/scripts/app/xml_handler/resources/scripts/configuration/callcenter.conf.lua
resources/install/scripts/directory.lua
resources/install/scripts/ivr_menu.lua
resources/install/scripts/resources/functions/format_ringback.lua

Converted uses of ringback to common function that supports any *-ring in vars

Enhance ringback

---

resources/install/scripts/streamfile.lua

Fix. Unset input callback after play file done.

Fix. Use domain name in streamfile.lua.

---

app/ivr_menus/ivr_menu_edit.php

made it possible to find phrases
fixed string replace not taking out spaces aswell

BigFix-ivr_menu_edit

---

secure/fax_to_email.php
themes/enhanced/app_defaults.php

WhitespaceClean-others

---

app/access_controls/access_control_edit.php
app/access_controls/access_control_node_edit.php
app/access_controls/access_control_nodes.php
app/access_controls/access_controls.php

WhitespaceClean-app/access_controls

---

README.md

WhitespaceClean-root

---

core/install/install.php
core/install/resources/classes/detect_switch.php
core/install/resources/classes/global_settings.php
core/install/resources/classes/install_fusionpbx.php
core/install/resources/classes/install_switch.php
core/install/resources/page_parts/install_config_detail.php
core/install/resources/page_parts/install_event_socket.php

WhitespaceClean-core/install

---

resources/classes/cache.php
resources/classes/directory.php
resources/classes/event/handler/syslog.php
resources/classes/fax.php
resources/classes/orm.php
resources/classes/permissions.php
resources/classes/template.php

WhitespaceClean-resources/classes

---

app/call_block/call_block.php
app/conference_centers/conference_centers.php
app/contacts/contact_extensions.php
app/contacts/contact_settings.php
app/destinations/destinations.php
app/dialplan/dialplans.php
app/ivr_menus/ivr_menus.php
app/ring_groups/ring_groups.php
app/voicemails/voicemails.php
core/default_settings/default_settings.php
core/domain_settings/domain_settings.php
core/users/user_settings.php

fixed various uses of ucwords() to render true/false to use
$text[label-*] instead

BugFix-Translation-True_False

---

resources/install/scripts/app/ring_groups/resources/scripts/destination.lua
resources/install/scripts/app/ring_groups/resources/scripts/ring_member.lua

fixed bug introduced on 2/1/2016 in destination.lua
fixed bug introduced on 2/1/2016 in ring_member.lua

corrected function definition

---

resources/jquery/flot/jquery.flot.js
resources/jquery/flot/jquery.flot.time.js
resources/jquery/jquery-ui.css

WhitespaceClean-resources/jquery

---

resources/templates/provision/atcom/ag198/{$mac}.cfg
resources/templates/provision/digium/d50/${mac}.cfg
resources/templates/provision/linksys/spa2102/{$mac}.xml
resources/templates/provision/snom/7xx/{$mac}.xml

WhitespaceClean-resources/provision/others

---

resources/templates/provision/grandstream/dp715/{$mac}.xml
resources/templates/provision/grandstream/gxp110x/{$mac}.xml
resources/templates/provision/grandstream/gxp116x/{$mac}.xml
resources/templates/provision/grandstream/gxp1450/{$mac}.xml
resources/templates/provision/grandstream/gxp1450bk/{$mac}.xml
resources/templates/provision/grandstream/gxp20xx/{$mac}.xml
resources/templates/provision/grandstream/gxp21xx/{$mac}.xml
resources/templates/provision/grandstream/gxp21xxbk/{$mac}.xml
resources/templates/provision/grandstream/gxv300x/{$mac}.xml
resources/templates/provision/grandstream/gxv3140/{$mac}.xml
resources/templates/provision/grandstream/gxv3175/{$mac}.xml
resources/templates/provision/grandstream/gxv3175v2/{$mac}.xml
resources/templates/provision/grandstream/gxv3504/{$mac}.xml
resources/templates/provision/grandstream/gxw4004/{$mac}.xml
resources/templates/provision/grandstream/gxw4008/{$mac}.xml
resources/templates/provision/grandstream/gxw42xx/{$mac}.xml
resources/templates/provision/grandstream/ht502/{$mac}.xml
resources/templates/provision/grandstream/ht503/{$mac}.xml
resources/templates/provision/grandstream/ht701/{$mac}.xml
resources/templates/provision/grandstream/ht704/{$mac}.xml

WhitespaceClean-resources/provision/grandstream

---

core/events/resources/classes/events.php
core/menu/app_config.php
core/users/app_config.php

WhitespaceClean-core/batch

---

app/extensions/extension_download.php
app/fax/fax_send.php
app/fax/resources/classes/fax.php
app/fifo_list/fifo_interactive_inc.php
app/time_conditions/time_condition_edit.php
app/traffic_graph/svg_graph.php
app/vars/app_defaults.php

WhitespaceClean-app/batch_2

---

app/adminer/adminer.css
app/call_centers/resources/classes/call_center.php
app/calls/resources/classes/call_forward.php
app/click_to_call/app_languages.php
app/edit/filedelete.php
app/ivr_menus/resources/classes/ivr_menu.php
app/modules/resources/classes/modules.php
app/provision/index.php
app/scripts/resources/classes/scripts.php
app/services/resources/classes/lib_win.php
app/sql_query/sql_query_pdo.php
app/time_conditions/app_defaults.php
app/voicemails/app_defaults.php

WhitespaceClean-app/batch_1

---

app/emails/email_cron.php
app/emails/email_delete.php
app/emails/emails.php
secure/v_mailto.php

don't re-save the failed message to db if re-sending
create a php file that can be called from cron to resend emails
fix delete of saved emails when using show all

fix some email stuff

---

app/provision/resources/classes/provision.php

Add. Export `contact_type` and `phone_label` for provisioning template

Fix. Export `contact_category` for provisioning template

---

themes/default/template.php

P.S. Also class `menu` contain type `email` for menu item.

Fix. add `PROJECT_PATH` to menu item url

---

core/user_settings/user_dashboard.php

Also it does not request information about all active calls which can be quite huge.

Fix. Display session count on User Dashboard.

---

resources/install/scripts/email.lua

https://wiki.freeswitch.org/wiki/Mod_lua#freeswitch.email   
same as my other pull request

Wrong variable in freeswitch.email

---

app/sms/app_config.php
app/sms/app_defaults.php
app/sms/app_languages.php
app/sms/sms.php
app/sms/sms_api.php
app/sms/sms_edit.php
app/sms/sms_mdr.php
resources/install/scripts/app/sms/index.lua

added support for twilio and made it a bit easier to add support for
other carriers as well.

SMS add support for twilio

---

app/calls_active/calls_active_inc.php
app/dialplan_inbound/app_defaults.php
app/extensions/app_defaults.php
app/extensions/resources/classes/extension.php
app/fax/fax_edit.php
app/fax/fax_files.php
app/fax/fax_send.php
app/music_on_hold/music_on_hold.php
app/phrases/app_defaults.php
app/recordings/app_defaults.php
app/voicemail_greetings/voicemail_greetings.php
app/voicemails/app_defaults.php
app/xml_cdr/resources/classes/xml_cdr.php
app/xml_cdr/v_xml_cdr_import.php
core/install/resources/classes/install_switch.php
resources/functions.php
resources/switch.php

I got the permissions wrong
it should have been in octal mod (leading 0)
also updated the fax application as it needs the stickygid too

BugFix corrected stickybit to be octal

---

core/install/install.php
themes/default/app_defaults.php
themes/default/css.php

added support to allow install to use the theme's default settings and
reduce the number of php errors during the installer due to missing
settings

update installer to use default theme

---

core/install/resources/page_parts/install_config_detail.php

Set the default database type to postgresql as that is the one promoted
for the scripted install

Enhance Set postgresql as default

---

core/install/install.php
core/install/resources/page_parts/install_event_socket.php

Reinstated the detect Configuration
it is no longer required for the detect_switch to pass but this
reinstates the ability to change the values and check them with detect
configuration

Enhance Reinstate switch detect

---

app/music_on_hold/resources/classes/switch_music_on_hold.php
app/recordings/resources/classes/switch_recordings.php

fixed incorrect referenced to the switch_recordings class

BugFix-moh class bad ref

---

app/call_centers/call_center_queue_edit.php
app/extensions/extension_edit.php
app/music_on_hold/resources/classes/switch_music_on_hold.php

changed switch_music_on_hold->select to be more inline of usage
changed extension_edit to use new format
changed call_center_queue_edit to use new format while
https://github.com/fusionpbx/fusionpbx/pull/1637 is in testing

BugFix-remove-legacy-warning

---

app/call_centers/call_center_queue_edit.php

BugFix Convert call_center to ringback class

---

app/call_flows/app_config.php
app/call_flows/app_languages.php
app/call_flows/call_flow_edit.php
resources/install/scripts/call_flow.lua
resources/install/scripts/resources/functions/file.lua

This file uses new way to load recordings from DB.
This is replace to #1642 and #1640

Add. Support sound prompts on call flow.

---

app/music_on_hold/resources/classes/switch_music_on_hold.php

populate the default moh for switch source installs
set comment indents as preferred

BugFix-default moh for source mode

---

app/devices/app_languages.php
app/devices/device_edit.php
app/devices/device_profile_edit.php
app/provision/resources/classes/provision.php
resources/templates/provision/escene/e3xx/{$mac}_extern.xml

Also require #1658 to work with profile.

Add. Support provision programmable keys for Escene devices.

---

app/devices/cmd.php
app/devices/resources/classes/device.php
app/registrations/cmd.php

Add. Escene and AddPac vendors.

Add. Use static function to find vendor by User-Agent string.

---

app/provision/resources/classes/provision.php
app/provision/resources/functions/device_by.php

Close #1389
Rewrite code to write config file to file.

Fix. Disable device provision.

---

app/voicemails/app_defaults.php
resources/install/scripts/app/voicemail/resources/functions/record_greeting.lua
resources/install/scripts/app/voicemail/resources/functions/record_message.lua

allow the voicemail max_lengths to be configured from domain/default
settings

Enhance-make voicemail length configurable

---

resources/install/scripts/app/voicemail/resources/functions/record_greeting.lua
resources/install/scripts/app/voicemail/resources/functions/record_message.lua

Fix. Load required libraries in voicemail.

---

app/scripts/resources/classes/scripts.php

Fix. generate correct config file.

---

app/music_on_hold/music_on_hold.php

Fix. set correct value for `Default` sampling.
PS. #1719 still needed

Fix. create default path when upload new profile.

---

resources/templates/provision/yealink/t46g/{$mac}.cfg

Add programmable keys to yealink t46.

Add programmable keys to yealink t46

---

resources/install/scripts/app/voicemail/index.lua
resources/install/scripts/app/voicemail/resources/functions/forward_to_extension.lua
resources/install/scripts/app/voicemail/resources/functions/menu_messages.lua
resources/install/scripts/app/voicemail/resources/functions/message_count.lua
resources/install/scripts/app/voicemail/resources/functions/message_waiting.lua
resources/install/scripts/app/voicemail/resources/functions/mwi_notify.lua
resources/install/scripts/app/voicemail/resources/scripts/mwi.lua
resources/install/scripts/app/voicemail/resources/scripts/mwi_subscribe.lua

* move send event code to separate function
* move get message count to separate function

Fix. Send message count in each MWI notify.

---

app/music_on_hold/resources/classes/switch_music_on_hold.php

Don't do a nested select, it adds unnecessary overload to the db. Instead, use a left join, quicker and more compatible among db types.

More efficient and compatible SQL query

---

resources/install/scripts/app/voicemail/resources/scripts/mwi_subscribe.lua
resources/install/scripts/call_flow_subscribe.lua
resources/install/scripts/resources/functions/ievents.lua

Now subscriber stops and remove pid files when FS shutdown.
So if you use Status->Services you will see correct status.

Add. Support multiple events.

---

app/scripts/resources/classes/scripts.php
resources/install/scripts/app/conference_center/index.lua
resources/install/scripts/app/conference_center/resources/templates/en/us/email_body.tpl
resources/install/scripts/app/voicemail/resources/functions/send_email.lua

added project_path for lua to use where it needs to build urls

BugFix-Add PROJECT_PATH for lua

---

resources/install/scripts/resources/functions/event_consumer.lua
resources/install/scripts/resources/functions/interval_timer.lua

Usage
```Lua
-- execute action each 30 sec
events:onInterval(30*1000, function() end)
-- execute action once after 5 min
events:onIntervalOnce(5*60*1000, function() end)
```

Add. Support `onInterval` method to EventConsumer class

---

app/services/service_edit.php

Also I remove Domain UUID because there no way to know what domain uuid is used

Fix. Escape quotes and do not check domain_uuid in edit service form.

---

app/devices/resources/classes/device.php

Polycom were assigned a new MAC prefix - 64:16:7f

BugFix-Add new Polycom MAC

---

app/registrations/app_languages.php
app/registrations/status_registrations_inc.php

Retrieve ping-time and display it
display `&nbsp;` only when value is empty

Enhance-Add Ping to Registrations Status

---

resources/templates/provision/aastra/675x/{$mac}.cfg

Fix programmable keys in Aastra provisioning template

---

app/extensions/app_config.php
app/extensions/app_languages.php
app/extensions/extension_edit.php
resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

This option force FS send SIP OPTIONS message to
detect if this reged device still available.

Add. `force_ping` option for extension

---

app/calls/resources/classes/call_forward.php
resources/install/scripts/call_forward.lua

When a call gets forwarded you will see form witch Extension it came from.
https://tools.ietf.org/html/rfc5806#section-6.1

add Diversion Header to dail string

---

app/devices/device_edit.php

Added a key profile edit and add button for easier navigation, can now hop to profile editing with one click.

Added a key profile edit and add button

---

app/devices/device_edit.php

Added functionality to hide profile edit button and changed code to use jQuery and event hooks
As requested!

Added functionality to hide profile edit button

---

app/operator_panel/index.php

Missing S in the directory name. Please not this pull request is for 4.0 branch

Same fix as for DEVEL branch

---

app/operator_panel/index.php

it was looking for call_center, instead call_centerS

Wrong directory name

---

app/devices/app_config.php
app/devices/app_languages.php
app/devices/devices.php
app/provision/index.php

Added functionality to show when a device was last provisioned, method of provisioning and ip address

Added functionality to show when a devices was last provisioned

---

app/vars/app_defaults.php
resources/classes/ringbacks.php

corrected the system default us-ring category to 'Ringtones'
remove var_name like as var_cat now takes care of this

BugFix-Vars

---

app/tftp/resources/systemd.service.template
app/tftp/resources/tftpservice.class.php
app/tftp/tftpservice.php

Fixed linux and windows run as service issues
Fixed linux systemd service self install issues
Modified windows service self install process

TFTP Service 1.0.7

---

app/tftp/app_defaults.php
app/tftp/tftpservice.php

Added a check to pervent script execution from a webserver.

TFTP Service v1.0.8

---

app/xml_cdr/xml_cdr.php

Dont make the row clickable if the extended data field (json) is empty

CDR Display functionality change

---

app/xml_cdr/xml_cdr.php
app/xml_cdr/xml_cdr_inc.php

Raw data field was not being pulled so logic was broken, added derived
field raw_data_exists to sql statement, instead of pulling raw data with
query. Also added logic to hide the view extended data icon on the right
side of table.

CDR Extended Data Functiality Fix

---

app/recordings/recordings.php
themes/default/template.php

This fixes browsers like Safari and allows them to stream audio within
the browser vs downloading the audio.

FIX: Stream audio in browser

---

app/tones/app_config.php
app/vars/app_defaults.php
resources/app_languages.php
resources/classes/ringbacks.php
resources/classes/tones.php
resources/templates/conf/vars.xml

Enhance Add Tones

---

app/devices/app_defaults.php

Fixed bug in app_defaults that recreated new setting each upgrade

TFTP Service v1.0.9

---

resources/install/scripts/app/agent_status/index.lua

Moved the UPDATE sip request to the end as it was sending the UPDATE request sometimes before the ACK had been received to the 200OK. This was sometimes causing it to fail.
Also removed a couple of commented out lines.

Moved the display update to the end

---

app/dialplan/resources/switch/conf/dialplan/890_local_extension.xml

Fix load balancing in 4.3

---

app/dialplan/resources/switch/conf/dialplan/890_local_extension.xml

Same rationale as last PR for 4.0

Fix load balancing in 4.2

---

resources/install/scripts/app/xml_handler/index.lua

Look further for domain_name

---

app/dialplan_outbound/dialplan_outbound_add.php

Add the capability to have extension and DID with same number

---

core/default_settings/app_defaults.php
secure/fax_to_email.php
secure/v_mailto.php

I updated this to latest 4.2.
/core/default_settings/app_defaults.php
/secure/v_mailto.php
/secure/fax_to_email.php

email/fax fixes for 4.2 branch

---

resources/install/scripts/app/voicemail/resources/functions/record_message.lua

https://github.com/fusionpbx/fusionpbx/issues/2036

Changes to API per issue 2036

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua
resources/install/scripts/resources/functions/database.lua

Xml handler directory sql escape

---

core/upgrade/index.php

Old result (seems correct but actually failed):
Updating d190f6a..d958bea
Corrected result (includes failure message):
Updating d190f6a..d958bea
error: Your local changes to the following files would be overwritten by merge:
app/fax/fax_log_view.php
Please, commit your changes or stash them before you can merge.

[master] include stderr in git pull results and check for error 

---

core/upgrade/index.php

Old result (seems correct but actually failed)
Updating d190f6a..d958bea
Corrected result (includes failure message):
Updating d190f6a..d958bea
error: Your local changes to the following files would be overwritten by merge:
app/fax/fax_log_view.php
Please, commit your changes or stash them before you can merge.

include stderr in git pull results and check for error

---

resources/install/scripts/resources/functions/settings.lua

Add. Use params in `settings.lua`

Fix. Fetch correct arrays from settings.

---

app/devices/app_config.php
app/devices/device_profile_edit.php
app/devices/device_setting_delete.php
app/provision/resources/classes/provision.php

Adds device settings to device profiles. This is in response to [Issue#1973](https://github.com/fusionpbx/fusionpbx/issues/1973). 
The precedence for settings are system, domain, profile, device.

Device profile settings

---

app/registrations/status_registrations.php
app/registrations/status_registrations_inc.php

Adds the ability to search for information in the Registration page. Will search on any fields.

Registration search

---

app/extensions/app_languages.php
app/extensions/extension_copy.php
app/extensions/resources/classes/extension.php

app/extensions/app_languages.php
+ add duplicate extension error prompt
app/extensions/extension_copy.php
+ add check to see if duplicate extension exists
app/extensions/resources/classes/extension.php
+ add function to check if extension exists

prevent cloning duplicate extensions (master #1821)

---

app/gateways/gateways.php

make observation of the gateway_domain permission more strict when
generating edit and delete links
generate edit_link and delete_link once

observe gateway_domain permision more strictly

---

app/extensions/app_languages.php
app/extensions/extension_copy.php
app/extensions/resources/classes/extension.php

app/extensions/app_languages.php
+ add duplicate extension error prompt
app/extensions/extension_copy.php
+ add check to see if duplicate extension exists
app/extensions/resources/classes/extension.php
+ add function to check if extension exists
+ all cherry picks "AND AND" fix from master

fixes for #1821 4.2 branch

---

app/gateways/gateways.php

https://github.com/fusionpbx/fusionpbx/issues/2190

fix for issue #2190 missing }

---

core/upgrade/index.php

new features:
- bottom of upgrade screen shows git branch + commit you are on
- provide a link to github showing changes since this commit on on your current branch
More eyes reviewing the code is always a plus.  The github link helps make it easier.
p.s. Much thanks to @markjcrane

show git branch + commit.  +link to preview git changes

---

core/default_settings/app_defaults.php

master fix typo

---

app/dialplan_outbound/app_languages.php
app/dialplan_outbound/dialplan_outbound_add.php

+011-883-5100-xxxx-xxxx
Most voip providers will give you a free iNum number.  Calls between iNum numbers are typically free.

add iNum Dial pattern to dialplan drop-down

---

resources/install/scripts/app/speed_dial/index.lua

What changed
* Use json format to store information in memcache.
* Use `cache` class to interact with memcache. (this class e.g. escape 
* Use `log` class to write logs
* Add domain name condition to sql query
* Use only first speed dial number for transfer
Suggestion
* pass dial number as argument instead of use destination number.
* use `phone@domain` as memcache key instead of `phone@context` and do 
not store `context` in cache and always use current context value.

Rewrite speed_dial Lua script.

---

resources/install/scripts/app/speed_dial/index.lua

Also do not store `context` in memcache.

Fix. Find in database not empty phone number for speed dial.

---

resources/install/scripts/call_forward.lua

This is same behavior as in Web UI.

Fix. Use CID from extension for call forward if set `call_forward_fix`.

---

resources/install/scripts/app/failure_handler/index.lua

Fix Call forward BUSY and NO ANSWER DEVEL

---

resources/install/scripts/app/failure_handler/index.lua

Fix call forward BUSY and NO ANSWER 4.2

---

app/provision/resources/classes/provision.php

Fix global vars scope DEVEL

---

app/call_flows/call_flow_edit.php
app/dialplan/dialplans.php
app/fax/fax_edit.php
core/users/user_edit.php

call_flow_edit.php
- fix: <script> tag output before html headers

Minor fixes to HTML markup.

---

app/xml_cdr/resources/classes/xml_cdr.php

This pull request fixes many speed issues with extension summary on large multi-tenant deployments. It should not have much of an effect on single-tenant systems.
On large systems with millions of cdr's extension summary can take minutes to load (on a few extra active tenants, for us, it takes almost 45 minutes to load, which is very bad considering it also locks the session up). With this patch, even on those extra large tenants with no database caching effects it goes down to under 2 minutes. Still not ideal, but a massive improvement. Psql analyze shows over 20x improvement in query cost (psql explain's below), and in some cases where psql cache is in place I've timed almost 100x increase in page load time.
I essentially changed the whole query around, but data and table format it …

Fix xml_cdr_extension_summary.php speed issues

---

app/registrations/resources/classes/status_registrations.php

Grandstream send IP like `BJC.BGI.B.CAB` so we
should convert it to numeric form.

Fix. Display Lan IP for Grandstream

---

app/call_centers/call_center_queue_edit.php

Stops php warning message appearing when there are no assigned agents

Stop warning message appearing

---

resources/install/scripts/app/voicemail/resources/functions/send_sms.lua

Gives the user ability to add transcription to the sms message for
voicemail notifications.

Add transcription to the sms message

---

resources/classes/switch_settings.php

fix for a small, probably copy&paste error

fix condition in switch_settings.php

---

app/recordings/recordings.php

Specially when you have a cluster and there is no shared filesystem

Make sure recording directory exists

---

app/scripts/resources/classes/scripts.php
core/install/resources/classes/install_fusionpbx.php

fixed paths for debian pkg installs

fixing debian pkg installs

---

app/fax/fax_edit.php

not everybody names php binary as php5

FAX: PHP bin is not always php5

---

app/fax/fax_edit.php

Add multiple email fields to make entering multiple email addresses easier.

Add multiple email fields

---

app/registrations/app_languages.php

Translations for Contact header

Add contact column to registration table

---

app/voicemails/voicemail_messages.php

Show voicemail description (user name) after voicemail id.
Useful in case user has more than one mailbox assigned.

Show voicemail description (user name)

---

app/provision/resources/classes/provision.php

Make sure provisioning temporal directory exists

---

app/voicemails/voicemail_edit.php

Sets the default value on the page for the tutorial to false if the database has a null value.

Voicemail tutorial - patch

---

app/extensions/extension_edit.php
app/voicemails/app_config.php
app/voicemails/app_languages.php
app/voicemails/voicemail_edit.php
resources/install/scripts/app/voicemail/index.lua
resources/install/scripts/app/voicemail/resources/functions/change_password.lua
resources/install/scripts/app/voicemail/resources/functions/macro.lua
resources/install/scripts/app/voicemail/resources/functions/record_greeting.lua
resources/install/scripts/app/voicemail/resources/functions/record_menu.lua
resources/install/scripts/app/voicemail/resources/functions/record_name.lua
resources/install/scripts/app/voicemail/resources/functions/tutorial.lua

This change creates a voicemail tutorial for a voicemail user on their first login. Once the tutorial is completed the user will not be prompted again. An admin has the ability to turn the tutorial back on for a voicemail box if necessary. 
The tutorial asks 4 questions. The user has the ability to skip any of these. 
#1 - Do you want to setup your voicemail?
#2 - Do you want to record your name?
#3 - Do you want to change your password?
#4 - Do you want to record a greeting?
If #1 is skipped, the tutorial will finish and route them into the main menu.
If #2, 3 or 4 is skipped, then the tutorial will simple go to the next step. 
After the tutorial the user is routed to main menu. 
Existing "Callie" recordings were used.

Voicemail tutorial

---

app/destinations/destination_edit.php

Only if the group has the billing_edit allowed

Not everyone should change DID selling/buying pricing

---

app/destinations/destination_edit.php

Same rationale as 4.0

---

app/system/app_languages.php
app/system/system.php

make commit id clickable though to origin
display a status of the branch compared to remote

Enhance [master] Show more git information

---

app/provision/index.php

Mac detection for some Grandstreams phones

---

app/provision/index.php

Some GS models send the Mac address in the user agent

MAC detection for some Grandstream phones

---

app/provision/index.php

Yet another phone that reports mac in HTTP User Agent

---

app/system/app_languages.php
app/system/system.php

fix for if the .git folder is present but corrupt
report no git information when git isn't used

BugFix [master] system information git

---

app/devices/app_config.php
app/devices/device_vendor_restore.php
app/devices/device_vendors.php

The restore button will allow putting all tables as specified in the app_config file. It already has its group permission property.
I added some support for audiocodes phones.

Restore Button + Audiocodes preliminary support

---

core/domain_settings/domain_edit.php

The previous fix in PR #2512 was incomplete, this one should do it.
Sorry! 😳

Fixup for renaming domains

---

app/call_centers/app_config.php
app/call_centers/app_languages.php
app/call_centers/call_center_queue_edit.php
app/call_centers/resources/classes/call_center.php

just support for the cc_exit_keys call center parameter

CC Key Support for Call Center

---

resources/install/scripts/resources/functions/route_to_bridge.lua

Fix. Escape strings in regex api

---

app/devices/device_download.php
app/devices/devices.php

gives the ability to export your devices

device export

---

core/install/install.php
core/install/resources/classes/global_settings.php

Fix. Use correct way to get text message.
Fix. Use `Database Username` to create database if no `Create Database Username` specified.

Fix. Load `Message` class

---

resources/templates/provision/yealink/t19p/directory.xml
resources/templates/provision/yealink/t19p/favorite_setting.xml
resources/templates/provision/yealink/t19p/y000000000053.cfg
resources/templates/provision/yealink/t19p/{$mac}.cfg

Adding auto-provisioning template files for Yealink19P-E2 entry level IP phone.

Add provisioning template for Yealink T19P-E2

---

resources/install/scripts/follow_me.lua

It marked as deprecated and do not used anywhere.

Fix. Remove using `call_prompt` field.

---

resources/classes/text.php

update escape_str to more reliabiliy escape the string into a consistent format
unforunately for us addslashes is expecting you to single quote strings but we are double quoting so a bit more leg work has to be done to get the desired result

BugFix [master] text class

---

resources/classes/database.php

update return message when code 403 to also state the permission that failed

Enhance [master] Better reasons for 403 in database class

---

app/extensions/extension_dashboard.php

retrieve the correct items to feed to cache->delete

BugFix [master] outbound_caller_id_select cache issue

---

app/calls/resources/classes/call_forward.php
app/calls/resources/classes/follow_me.php

Although you already had somehow fixed the caller id here. you need to put origination and effective. For some reason, not all carriers get the CID from the same field in the SIP payload. origination_* and effective_* affects different parts of the SIP invite.

Fix the CID

---

resources/classes/database.php

Fix for if you send an array containing both updates and new data, it
would end up placing all the new data ontop of the last item containing
the uuid of the last update (if updates are earlier in the array than
new items)

BugFix [master] database class

---

app/sip_status/app_languages.php
app/sip_status/cmd.php
app/sip_status/sip_status.php

add stop action
change cmd.php to use messages::add and also trim trailing \n so message
does render

Enhance [master] sip_status Add Stop Action

---

resources/classes/messages.php
themes/default/template.php

htmlspecialchars isn't required for the javascript, only the \r?\n
escape

BugFix [master] - messages class

---

app/pin_numbers/pin_download.php

Fix Pin number export not working

---

app/sip_profiles/sip_profiles.php

change description to use correct $text

BugFix [master] - sip_profiles description

---

app/tftp/app_config.php
app/tones/app_config.php
app/traffic_graph/app_config.php
app/vars/app_config.php
app/voicemail_greetings/app_config.php

last batch of app_config.php changes

Enhance [master] - app_config.php last cleanup

---

app/dialplan_inbound/app_config.php
app/dialplan_outbound/app_config.php
app/edit/app_config.php
app/emails/app_config.php
app/exec/app_config.php
app/extensions/app_config.php
app/fax/app_config.php
app/fifo/app_config.php
app/fifo_list/app_config.php
app/follow_me/app_config.php
app/gateways/app_config.php
app/meetings/app_config.php
app/pin_numbers/app_config.php

correct a few missed tab indents on comments

Enhance [master] - app_config.php comment cleanup

---

app/system/system.php

use human format and wide display for free under linux
use posix output format and totals on df under linux
make spacing consistent on value assignements

Enhance [master] - system information

---

app/dialplan/resources/switch/conf/dialplan/570_nway_conference.xml

BugFix [master] - nway conference

---

app/xml_cdr/xml_cdr_search.php
app/xml_cdr/xml_cdr_statistics_inc.php

Add. Leg field to advanced search form.

Add. Statistics takes account to leg.

---

core/upgrade/app_languages.php

correct translation for message-upgrade_source

BugFix [master] - app_languages.php - core/upgrade

---

resources/classes/orm.php

update return message when code 403 to also state the permission that
failed

Enhance [master] - better reasons for 403 in orm class

---

resources/app_languages.php
resources/check_auth.php

convert to messages::add and utilize $text for invalid_credentials

Enhance [master] - update check_auth to use $text

---

login.php
resources/classes/messages.php

add new methods to messages class to let it take care of stash and pop
of the messages update login.php to use new methods
tweak html function to put the $_SESSION['message'] in the stack so there is only one code point to maintain for rendering

Enhance [master] - add message stash/pop

---

resources/classes/messages.php

stash/pop was present as a work around in login.php.
This removes the now redundant code.

Enhance [master] - remove statsh/pop from messages class

---

resources/classes/text.php

make the get routine a little more rugged by checking if the file exists not the directory it is in.
throw a exception if we are asked to load a app_languages that doesn't exist
don't reload the resources/app_languages if exclude_global was ommitted
code styling update to match project

Enhance [master] - text class

---

resources/check_auth.php

the update to check_auth to enable text i made a mistake and put the
wrong parameter into get. this corrects that

BugFix - check_auth

---

core/upgrade/upgrade.php
core/upgrade/upgrade_domains.php

the install uses upgrade_domains.php, update it to use well known varibles to show output

Enhance [master] - upgrade show during install

---

resources/classes/text.php

Try and auto fill a value when its blank an the same baseline language
has a value

Enhance [master] - text class autofill

---

core/users/app_config.php

Little language update

---

resources/install/scripts/ha_monitor.lua

This allows remove code related to create pid file and
handle system commands (e.g. to stop service) from service
file and leave it to base class.

Change. Use new service class to implement ha_monitor.lua

---

app/xml_cdr/xml_cdr_statistics.php

Add. Make legend outside of graphic of CDR Statistic.

---

resources/install/scripts/app/voicemail/resources/functions/advanced.lua

Need to pass in the "advanced" menu variable to functions in order to get back to Advanced menu.

Bug Fix: Route back to Advanced VM menu

---

core/install/install.php
core/install/resources/page_parts/install_config_detail.php
resources/require.php

fixes to remove some errors in the GUI installer

BugFix [master] - GUI install

---

app/provision/resources/classes/provision.php

Hide the extension in the phone directory if Extension -> Directory_Visible = false.

Hide in the phone directory

---

app/voicemails/app_config.php

I think this is a good default option for Admin's to have.

Admin privileges for VM local after email

---

resources/install/scripts/app/toll_allow/index.lua

Add South African Prefixes

---

.htaccess
app/devices/device_edit.php
resources/templates/provision/aastra/480i/aastra.cfg
resources/templates/provision/aastra/480i/{$mac}.cfg
resources/templates/provision/aastra/9112i/aastra.cfg
resources/templates/provision/aastra/9112i/{$mac}.cfg
resources/templates/provision/aastra/9133i/aastra.cfg
resources/templates/provision/aastra/9133i/{$mac}.cfg
resources/templates/provision/aastra/include/general
resources/templates/provision/aastra/include/keys
resources/templates/provision/aastra/include/network
resources/templates/provision/aastra/include/provision
resources/templates/provision/aastra/include/sip

provision aastra 9133i based phones (480i 480i CT, 9112i, 9133i)
leverage smarty include to common parts
have device_edit ignore 'include' folders

Enhance [master] - provision aastra 9133i

---

app/ring_groups/ring_groups.php

Add a search box to Ring Groups. 
Search by extension, name, strategy, enabled, or description.

Add Ring Group search field

---

core/users/user_edit.php

Same as pull request #2824 but for 4.3

Same as 4.2

---

app/voicemails/app_config.php

Add a envelope icon for Voicemails in the Destinations select list.

Envelope icon for voicemails in the Destinations select list.

---

resources/install/scripts/app/servers/resources/file_cache.lua

SSH method never worked. I submitted the wrong file.

Update file based cache sync to use curl instead of ssh

---

resources/app_languages.php

Fixes Turkish translation #2307

Add Turkish translation

---

resources/install/scripts/resources/functions/event_consumer.lua

Problem code is
``` Lua
for event in ievents{'SHUTDOWN','CUSTOM::event'} do
end
```

Fix. crash when using EventCounsumer.ievents iterator.

---

app/extensions/extension_dashboard.php

I believe this will help users to sort through the caller ID numbers on the dashboard.

Sort by CIDName if populated, otherwise CIDNumber

---

app/xml_cdr/resources/classes/xml_cdr.php

Bug fix for caller_destination and also caller_id_name populating the v_xml_cdr table.

Bug fix for caller_destination populating CDR's

---

app/xml_cdr/resources/classes/xml_cdr.php

call_recording_name & call_recording_path are the correct values.

Bug Fix - Match correct database column names

---

resources/templates/provision/yealink/t48g/y000000000035.cfg
resources/templates/provision/yealink/t48g/{$mac}.cfg

Cleaned up mac.cfg file and put Network settings into model config file.

Yealink T48G Template Updates

---

resources/templates/provision/yealink/t42g/y000000000029.cfg
resources/templates/provision/yealink/t42g/{$mac}.cfg

Modified yealink t42g templates

T42G Templates

---

resources/templates/provision/yealink/t52s/y000000000074.cfg
resources/templates/provision/yealink/t54s/y000000000070.cfg

fixed static.firmware.url

---

app/yealink/app_config.php
resources/templates/provision/yealink/t54s/y000000000070.cfg

created new variable yealink_dsskey_length
modified t54s to include it

dss key length

---

resources/templates/provision/yealink/t54s/y000000000070.cfg
resources/templates/provision/yealink/t58v/y000000000058.cfg
resources/templates/provision/yealink/t58v/{$mac}.cfg

added variables where they were missing in t54s and t58v templates

Update some Yealink t5xx templates

---

app/provision/resources/classes/provision.php
app/yealink/app_config.php
resources/templates/provision/yealink/t58v/y000000000000.boot

"t58v UA string, and template, t54s variable desc and file"

t54s variable value and descr update and t58v fixes

---

resources/install/scripts/app/ring_groups/index.lua

```
[absolute_codec_string='PCMU,GSM']sofia/gateway/carrier/123456
```
Limitations:
* supports only square braces. Fusion will replace them to needed one.
* does not support escape single quotes inside value like `a='b\'c'`
will be interpret as `a=b\`.
Limitations does not related with Lua code
* Fusion does not allow specify variable names inside string.
`[effective_caller_id_number=${outbound_caller_id_number}]....`
I think it should be safe to allow this here because FS does not
expand this string and all under control of Lua code.

Add. Support variables in ring groups when use direct dial

---

resources/templates/provision/cisco/spa303/{$mac}.xml

Add missing $ to spa_call_waiting

Add missing $

---

app/extensions/extension_edit.php

Probably not the best way but it works

Fix voicemail creation for ranges

---

app/number_translations/app_languages.php

Base on previous app/number_translation

Russian translation for number_translations

---

app/settings/app_languages.php

Correct typo

---

resources/install/scripts/app/ring_groups/index.lua

This scenario was broken: 
A ring group member forwards their phone to a destination. The destination is an external number and the outbound route has a toll_allow condition. 
This error would be generated: 
> [ERR] switch_cpp.cpp:1376 [route_to_bridge] Unsupportded condition: ${toll_allow}
This PR will get the toll_allow values from the RG member that is forwarding their phone. Then it will pass it to  'route_to_bridge.lua' correctly. If toll_allow is empty for the extension or the route doesn't have a toll_allow condition the call will also complete successfully.

Fix for Ring Groups with cfwd always & toll_allow

---

app/email_templates/app_languages.php

Add Russian translation strings

email_templates Russian 

---

resources/install/scripts/disa.lua

1. Allow custom sound_pin & sound_extension
2. Allow customization of max_tries, pin_tries & extension_tries
3. Add fallback_destination - fall to it if caller did not entered extension number
4. Allow custom digit_timeout

Add new features to disa.lua

---

app/devices/resources/classes/device.php

New Yealink t48s have different mac address

Include New yealink mac

---

app/devices/resources/classes/device.php

Yealink patch as 4.3

---

app/registrations/resources/classes/registrations.php

GIGASET Sculpture CL750A puts _ in it's lan ip account for this and
perform a replacement

Enhance [master] - Gigaset LAN IP

---

secure/fax_to_email.php
secure/v_mailto.php

Give the ability to customize the smtp from domain and name for voicemail and fax separately

Add customization for email

---

resources/install/scripts/resources/functions/send_mail.lua

Fixed where sendmail was sending to and from the same address which has a high potential to be blocked by spf spam filtering.

Formatting and sendmail to use smtp_from fix

---

resources/install/scripts/resources/functions/send_mail.lua

take call_uuid from the correct header
use smtp_from_name as part of the from address

BugFix - [master] - LUA send_mail()

---

resources/install/scripts/resources/functions/send_mail.lua

use correct header to retrieve call_uuid

BugFix [master] - send_mail.lua

---

app/devices/device_edit.php
app/provision/app_config.php
core/default_settings/default_setting_edit.php
core/domain_settings/domain_setting_edit.php
resources/templates/provision/aastra/480i/aastra.cfg
resources/templates/provision/aastra/480i/{$mac}.cfg
resources/templates/provision/aastra/673x/aastra.cfg
resources/templates/provision/aastra/675x/aastra.cfg
resources/templates/provision/aastra/686x/aastra.cfg
resources/templates/provision/aastra/9112i/aastra.cfg
resources/templates/provision/aastra/9112i/{$mac}.cfg
resources/templates/provision/aastra/9133i/aastra.cfg
resources/templates/provision/aastra/9133i/{$mac}.cfg
resources/templates/provision/aastra/include/general

add default settings for time format, date format and timezone
hide include folders (they are not provision templates)

Enhance [master] - update Aastra provision templates

---

app/call_recordings/call_recordings.php

Display the Number of Recordings next to the Title.

Display the Number of Recordings next to the Title.

---

resources/templates/provision/cisco/spa504g/{$mac}.xml

Fix key type disabled for park, page etc

Fix key type disabled

---

app/dialplans/resources/classes/dialplan.php

Fixes an issue were time conditions are not working if Date & Time is used.

Fix for broken time conditions

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

Same as 4.4

---

app/call_block/app_languages.php
app/call_block/call_block.php
app/dialplans/resources/switch/conf/dialplan/040_call_block.xml
resources/install/scripts/app/call_block/index.lua

- Added support for regular expressions in numbers to be blocked. Usefull for blocking number ranges used by call centers, etc.
- Added default sort order to GUI display

Enhance  Call Blocking [master]

---

resources/install/scripts/app/ring_groups/index.lua

The variable "external" is set as a String not as a Boolean. Changed the If statement to reflect.

Bug Fix: Wrong Variable Type

---

resources/install/sql/mysql.sql

Fix Mysql/MariaDB installation 2/2 [4.5]

---

resources/install/sql/mysql.sql

Fix Mysql/MariaDB installation 2/2 [4.4]

---

app/grandstream/app_config.php
resources/templates/provision/grandstream/gxp2130/{$mac}.xml
resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/gxp2140/{$mac}.xml
resources/templates/provision/grandstream/gxp2160/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml

This allows users to add custom city codes to tables.

City Code for GXP Phones

---

app/ivr_menus/ivr_menu_edit.php

UPDATE 2018/05/30: This is a new PR with updated code and behavior following our call.
Specifically:
1 - Variable names  updated to bring them in line with project nomenclature
2 - Uses glob() to find paths instead of previous method (thanks Mark!)
3 - Language is no longer a required field
4 - Language field now defaults to empty
5 - Does not set language variables in IVR dialplan at all if no language selection is made
ORIGINAL DETAILS:
This scans the FreeSWITCH sounds directory to find installed languages and then allows the user to select the language, dialect and voice from a dropdown.  The selected option will then be built into the dialplan and saved in the database when saving the IVR.
This fixes many cases of inconsistent language problems with email templates, multilanguage …

UPDATED: Add language, dialect and voice selection

---

app/dialplan_outbound/app_config.php
app/dialplan_outbound/app_languages.php
app/dialplan_outbound/dialplan_outbound_add.php

Added a true of false pin code option to outbound route for ease of enabling pin code dialing

Add Pin Code option to outbound route

---

app/dialplan_outbound/app_config.php
app/dialplan_outbound/app_languages.php
app/dialplan_outbound/dialplan_outbound_add.php

Reverts fusionpbx/fusionpbx#3084

Revert "Add Pin Code option to outbound route"

---

app/dialplan_outbound/dialplan_outbound_add.php

this is for ease of setting it up without making mistakes in the dialplan

set toll allow to a text box

---

resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml

Somehow this was static'ed to 60 minutes.  Set with variable so it pulls from device settings now.

Fixed gxp2170 template value register_timeout 

---

app/devices/app_config.php
app/devices/app_languages.php

Must also set "features.enhanced_dss _keys.enable = 1" in the provisioning files.
Adding this for creating speed dials with a pause then DTMF digits.

Add Custom option for Yealink DSS key

---

app/xml_cdr/xml_cdr_inc.php

Match updates in 4.4 branch to fix search options

Fix wildcard search for Source

---

secure/v_mailto.php

Seems like can handle, filesize with logrotate or another way manually.

append for troubleshooting purposes

---

app/dialplan_outbound/dialplan_outbound_add.php

add dropdown to enable pin codes

pin code dropdown

---

app/dialplan_outbound/app_config.php
app/dialplan_outbound/app_languages.php
app/dialplan_outbound/dialplan_outbound_add.php

This fixes the dropdown to allow Pin numbers in the outbound route and changes the name to Pin numbers from Pin Codes, it also fixes the permission as per Mark's suggestion on Continued Education

Fix Pin Numbers

---

app/dialplan_outbound/dialplan_outbound_add.php

it was not adding the pin_number.lua part as that was not added by mistake the first time i submitted

fix pin_codes dialplan

---

core/users/user_edit.php

List does not display with escape

List does not display with escape

---

resources/templates/provision/grandstream/ht802/{mac}.xml

This is a slightly modified HT802 provisioning file we've been using for the past year. Assuming the device is at factory default, this works well.

Added Grandstream HT802 provisioning file

---

core/install/resources/classes/install_fusionpbx.php

Fix Mysql/MariaDB installation 1/2 [4.4]

---

app/extensions/extension_edit.php

When provisioning 48 port analog gateway, (Grandstream GXW4248 for example) need ability to configure up to 48 lines per device.

Allow editing 48 lines on extension_edit page

---

app/user_imports/user_imports.php

User imports was looking for /app/users/users.php
not /core/users/users.php

fix user imports

---

app/xml_cdr/xml_cdr_details.php

[4.4] Unescape JSON before decoding

---

app/dialplan_outbound/dialplan_outbound_add.php

Confirmed via https://www.nationalnanpa.com/enas/nonGeoNpaServiceReport.do

Add 833, 844 to toll-free outbound pattern.

---

core/install/install.php

resources/classes/messages.php was renamed to resources/classes/message.php

Fix file name for install.

---

resources/install/scripts/app/voicemail/resources/functions/record_message.lua

Working on documenting the Custom Voice Transcription API in FusionPBX Docs (ReadTheDocs), figure I would fix this per our IRC conversation.

Minor variable renaming per IRC conversation

---

app/ivr_menus/ivr_menu_edit.php

The error says Ivr not enabled and wont save, this fixes it

fix ivr not saving

---

resources/install/scripts/app/agent_status/index.lua
resources/install/scripts/blf_subscribe.lua

Add the ability to monitor the availability status of a call center agent with "agent+agentname@domain.com".

BLF of agent status "agent+username@domain.com

---

app/operator_panel/resources/functions/get_call_activity.php

Add e.enabled = 'true' to SQL where and show only enabled extensions on the operator panel.

Show enabled extension only on operator panel

---

app/xml_cdr/xml_cdr_archive.php

Make the labels in the xml_cdr_archive.php page match what is on the xml_cdr.php page.

Fix the labels and the paging controls

---

resources/templates/provision/grandstream/gac2500/{$mac}.xml

Only values changed from raw template are FusionPBX variables and allow paging auto answer

New GAC2500 template Firmware 1.0.3.30

---

resources/templates/provision/grandstream/gxv3370/{$mac}.xml

Config template V2 from Grandstream. first model with new style of XML template.  
Does not use "P" codes.
MPK settings are not programmed in this commit.
Options with FusionPBX variables are set, but all other options are still set to default.

Initial template GXV3370 (New style)

---

resources/templates/provision/grandstream/gds3705/{$mac}.xml
resources/templates/provision/grandstream/gds3710/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml
resources/templates/provision/grandstream/htx86/{$mac}.xml

This will complete the list of current Grandstream telephones.
last remaining template to build is "surveillance general" for cameras.

New GS templates and update 2170

---

resources/install/scripts/app/ring_groups/index.lua

Two things:
1. Follow-me should only kick in when using "Enterprise". As it was written, follow-me was looked at for every strategy. 
2. Follow-me destinations were writing to 'destinations[x]'. They should write to 'destinations[key]' so they rewrite the current destination that is being analyzed.

Ring Groups with Follow-Me

---

resources/templates/conf/freeswitch.xml

support for new portuguese language in freeswitch

adding [pt-pt, pt-BR] languages for freeswitch 1.8

---

app/calls/resources/classes/follow_me.php
app/dialplans/resources/switch/conf/dialplan/030_is_loopback.xml

We need a way of the dialplan identifying calls that are generated by follow-me using loopback. This setting couple with a dialplan statement allows us to identify and set proper caller-id-name/number.

Marker for identifying call as follow-me loopback

---

app/dialplans/dialplan_edit.php

Previously, if a bridge statement was written with prepended variables to be passed, the gateway name would not be parsed and replaced. Additionally, if multiple bridges were used in failover in a single bridge statement separated by a pipe, only the first would be parsed and replaced.
I noticed this after upgrade to FreeSWITCH 1.8.5 (from 1.6.20) which changed failover behavior with multiple separate bridge statements. When network returns 486 BUSY, it will proceed to second bridge statement, initiating a second call. To allow failover and not have this behavior, you must write a single statement and separate your failover bridges with a pipe, this change allows the UI to show all gateway names on the line once saved.
Examples:
{fax_use_ecm=on}sofia/gateway/99b1234c-667c-4b31-9d2f-31d4f39 …

Retrieve gateway names with variables and failover

---

app/xml_cdr/xml_cdr_details.php

[4.5] Fix CDR Details

---

app/xml_cdr/resources/classes/xml_cdr.php
app/xml_cdr/v_xml_cdr_import.php

[4.4] fixes null record_name and record_path fields in v_xml_cdr

---

app/calls/resources/classes/follow_me.php

Set the follow-me dial_string so the sofia_contact will work with multiple SIP profiles.

Follow-me Dialstring Bugfix

---

app/calls/resources/classes/follow_me.php

This keeps the same caller-id method for loopback, but adds in a method for caller-id using bridge.

Set caller-id for Follow-me using Bridge method

---

app/call_recordings/call_recordings.php

Bug where you couldn't enter a page number and press ENTER to jump to that page.

Paging Controls Fix

---

app/dialplans/dialplans.php

Same fix as the one for the call recordings page. You couldn't type in a page number and press enter.

Bug Fix: Paging Controls in the wrong place

---

resources/classes/schema.php

I think you should declare 4.4.6 as the upgrading is a critical thing

[4.4] Same as 4.5

---

resources/install/scripts/cidlookup.lua

Added and optional parameter, argv[2], to take a domain_uuid.  This is to fix an issue where if two contact records exist with the same phone number, but in different domains, the CID lookup would always pick the same contact record irrespective of which domain the inbound number belonged to.

Update cidlookup.lua - Bug fix where contact phone number exists in more than one domain

---

resources/templates/provision/fanvil/x6/{$mac}.cfg

Update Fanvil X6 template to correct issues with DSS configuration, allow setting country tones and ring types.

Fanvil fixes x6template

---

core/authentication/resources/classes/plugins/ldap.php

Ldap connection to non standard port

---

resources/classes/schema.php

Reverts fusionpbx/fusionpbx#4097

Revert "[4.5] Fix the ALTER TABLE"

---

resources/classes/schema.php

Reverts fusionpbx/fusionpbx#4100

Revert "[4.4] Same as 4.5"

---

app/dialplans/resources/classes/dialplan.php

To make it possible to use descriptions for own dialplan xmls

Add the description element for import

---

app/destinations/destinations.php

It would be nice to have destination actions as a searchable field. 
Example: If I have 500 destinations and 17 of them have Ring Group 5050 as their action, it would be helpful to be able to search for 5050 and pull up all the applicable destinations.

Make Destination Actions Searchable

---

core/authentication/resources/classes/plugins/database.php

Oddly, you fix this in 4.5 but not in 4.4.

fixes _SESSION[user][contact_uuid] emtpy

---

resources/install/scripts/app/voicemail/resources/functions/record_message.lua

The following PR is for voicemail transcription using IBM Watson.
https://cloud.ibm.com/catalog/services/speech-to-text
The following values need to be configured in Default Settings:
Category: Voicemail
Subcategory: watson_key
type: text
Value: [Your Watson api key ]
Category: Voicemail
Subcategory: json_enabled
type: boolean
Value: true
Category: Voicemail
Subcategory: transcibe_language
type: text
Value: en-US
Category: Voicemail
Subcategory: transcribe_provider
type: text
Value: watson
Category: Voicemail
Subcategory: watson_url
type: text
Value: https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_NarrowbandModel
Category: Voicemail
Subcategory: transcribe_enabled
type: boolean
Value: true
Reload Default Settings. I Flushed Cache and Reloaded XML just for …

Watson Transcription

---

app/dialplans/dialplans.php

One might be tempted to scoff at such a small set of paging controls, yet that would be a grave mistake. Though small stature they work just as well as their bigger brother whilst also providing their own unique experience to the user.

Add Mini Paging Controls

---

app/edit/cliplist.php

Same as devel [4.5]

---

resources/install/scripts/app/follow_me/index.lua

Insert toll-allow from the original extension into the dialstring for external calls.

Toll-allow into dialstring for external calls

---

resources/install/scripts/app/ring_groups/index.lua

Add toll_allow to dialstring for external numbers

Populate toll-allow for Enterprise Ring Groups

---

resources/install/scripts/app/ring_groups/index.lua

We need to make sure that the delay for the leg takes into account the delay from the RG and from Follow-me. 
Also, let's use the timeout from the RG instead of the follow-me member

Enterprise RG with Follow-Me

---

resources/install/scripts/cidlookup.lua

[4.5] Fix the cidlookup script

---

resources/install/scripts/cidlookup.lua

DB scheme changed, wront module name, missing some variables to update while in another thread

[4.4] Fix the cidlookup script

---

app/calls/call_edit.php

Caller ID select for for call forward was not saving the selection and would default to NULL or ''

Fix call forward Caller ID select

---

resources/install/scripts/app/follow_me/index.lua

Correct the wrong table name on line 123. Correct the param on line 126 and correct the syntax on line 347.

Fix table name, variables and syntax Follow me Lua

---

app/dialplans/app_defaults.php
app/dialplans/resources/switch/conf/dialplan/999_not-found.xml
resources/install/scripts/app/xml_handler/resources/scripts/dialplan/dialplan.lua

This seems to be the right one, sorry by the other, I mixed up things.

[4.4] DEBUG to WARNING for the not-found dialplan

---

app/extensions/extension_edit.php

if the proper permission is set, it will allow reloading the ACL s. Makes easier the IP auth configuration.

Reloads the ACLs

---

app/extensions/app_config.php
app/extensions/extension_edit.php

[4.4] Reload ACL's

---

resources/templates/provision/yealink/t54w/{$mac}.cfg

fix coded section

---

resources/templates/provision/yealink/t53w/{$mac}.cfg

Fix codec section

---

app/voicemails/voicemails.php

Show a number of messages per box on a voicemail main page.

Show count of VM messages per box

---

app/music_on_hold/music_on_hold.php

$stream_file variable was overwritten, the base64_decode was lost

[4.4] Fix MoH

---

app/scripts/resources/scripts/fax_retry.lua

[4.5] Fix fax email Subject when not using sofia/gateway

---

app/conferences_active/app_languages.php
app/conferences_active/conference_exec.php
app/conferences_active/conference_interactive_inc.php
app/scripts/resources/scripts/app/conference_center/resources/scripts/raise_hand.lua
resources/templates/conf/autoload_configs/conference.conf

User can press key from phone to raise hand that will show up for the moderator on the active conference and thus notify him that the user wants to get unmuted

Conference center raise hand feature

---

app/xml_cdr/xml_cdr.php

just another option for searching calls

[4.4] REQUESTED_CHAN_UNAVAIL added

---

app/xml_cdr/xml_cdr.php

[4.5] REQUESTED_CHAN_UNAVAIL option in xml cdr

---

app/scripts/resources/scripts/app/voicemail/resources/functions/macro.lua

Original recording reference not available in anything but callie

Fix followed_by recording reference

---

resources/templates/provision/yealink/cp860/{$mac}.cfg
resources/templates/provision/yealink/cp920/{$mac}.cfg
resources/templates/provision/yealink/cp960/{$mac}.cfg
resources/templates/provision/yealink/t21p/{$mac}.cfg
resources/templates/provision/yealink/t23g/{$mac}.cfg
resources/templates/provision/yealink/t23p/{$mac}.cfg
resources/templates/provision/yealink/t27g/{$mac}.cfg
resources/templates/provision/yealink/t27p/{$mac}.cfg
resources/templates/provision/yealink/t29g/{$mac}.cfg
resources/templates/provision/yealink/t40g/{$mac}.cfg
resources/templates/provision/yealink/t40p/{$mac}.cfg
resources/templates/provision/yealink/t41p/{$mac}.cfg
resources/templates/provision/yealink/t41s/{$mac}.cfg
resources/templates/provision/yealink/t42g/{$mac}.cfg
resources/templates/provision/yealink/t42s/{$mac}.cfg
resources/templates/provision/yealink/t46g/{$mac}.cfg
resources/templates/provision/yealink/t46s/{$mac}.cfg
resources/templates/provision/yealink/t48g/{$mac}.cfg
resources/templates/provision/yealink/t48s/{$mac}.cfg
resources/templates/provision/yealink/t49g/{$mac}.cfg
resources/templates/provision/yealink/vp530/{$mac}.cfg

Fixed Yealink Account 6 Errors (misstyped)

Fixed Yealink Account 6 Errors

---

app/scripts/resources/scripts/disa.lua

New channel variable added so that one may hook on to DISA calls which are not local.
New variable: disa_outbound

Set new channel variable

---

app/phrases/app_config.php
app/phrases/phrase_edit.php

Added permission to disallow users without this permission to save to database if posting phrase execute function

Phrases add permission

---

app/scripts/resources/scripts/app/xml_handler/resources/scripts/directory/directory.lua

[4.5] prevents routing errors

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

when using LB, if you can't find the user don't use sofia_contact.

[4.4] prevents routing errors

---

app/music_on_hold/resources/classes/switch_music_on_hold.php

When deleting moh as user the sql statement was corrupt and moh was not deleted.

Fixed error when deleting moh as user

---

resources/templates/provision/grandstream/ht818/{$mac}.xml

Codes for account 8 were using account 4 array.
also reworded note about profile 2 settings

correct account 8 settings

---

app/devices/device_copy.php

[4.5] Use INT instead of NUMERIC

---

app/destinations/resources/classes/destinations.php
app/ivr_menus/ivr_menu_edit.php

```destination->valid()``` method was passing ``"dialplan"``  as the type to the`` destination->all()`` method causing to fail for menu-sub

Fix destination->valid method for ivr

---

core/groups/resources/classes/permission.php

This speeds up dramatically permission defaults

Optimize permission defaults

---

app/scripts/resources/scripts/pin_number.lua

if ```pin_number=databse``` get the pin number description as well from the database and set it as a channel variable to be able to use it further in the dialplan

pin_number.lua get pin number description

---

app/xml_cdr/resources/classes/xml_cdr.php

Choosing only the start date or only the end date was broken

fix extension summary date selection

---

app/devices/resources/classes/device.php

[4.5] Add digium support to get_vendor_by_agent()

---

app/devices/resources/classes/device.php

[4.4] Adding Digium support to get_vendor_by_agent()

---

themes/default/css.php

Add new CSS class for non-registered extensions. Button will appear disabled on the operator panel.

Update css.php for Operator Panel

---

app/scripts/resources/scripts/app/ring_groups/index.lua

change to use functions.send_mail so system from address is taken into account

BugFix [master] - ring_groups\index.lua

---

resources/templates/provision/linksys/spa941/{$mac}.xml
resources/templates/provision/linksys/spa942/{$mac}.xml

remove not supported values for old linksys spa devices

old linksys spa changes

---

resources/functions.php

Was breaking with creating a directory with whitespace and apostrophe in it

Escape quotes on mkdir

---

resources/templates/provision/yealink/w60b/y000000000077.cfg

Added yealink_vlan_enable and yealink_vlan_id settings

Add existing VLAN options to this template

---

resources/templates/provision/grandstream/ht802/{$mac}.xml

Add existing grandstream_lan_port_vlan setting

---

resources/templates/provision/yealink/t2x/y000000000044.cfg
resources/templates/provision/yealink/t2x/y000000000052.cfg
resources/templates/provision/yealink/t2x/y000000000053.cfg
resources/templates/provision/yealink/t2x/y000000000069.cfg
resources/templates/provision/yealink/t4x/y000000000028.cfg
resources/templates/provision/yealink/t4x/y000000000029.cfg
resources/templates/provision/yealink/t4x/y000000000035.cfg
resources/templates/provision/yealink/t4x/y000000000036.cfg
resources/templates/provision/yealink/t4x/y000000000054.cfg
resources/templates/provision/yealink/t4x/y000000000065.cfg
resources/templates/provision/yealink/t4x/y000000000066.cfg
resources/templates/provision/yealink/t4x/y000000000067.cfg
resources/templates/provision/yealink/t4x/y000000000068.cfg
resources/templates/provision/yealink/t4x/y000000000076.cfg
resources/templates/provision/yealink/t4x/y000000000107.cfg
resources/templates/provision/yealink/t4x/y000000000108.cfg
resources/templates/provision/yealink/t4x/y000000000109.cfg
resources/templates/provision/yealink/t4x/y000000000116.cfg
resources/templates/provision/yealink/t5x/y000000000070.cfg
resources/templates/provision/yealink/t5x/y000000000095.cfg
resources/templates/provision/yealink/t5x/y000000000096.cfg
resources/templates/provision/yealink/t5x/y000000000097.cfg

Added daylight savings from normal yealink templates commit #5229 to the x yealink templates so they stay up to date with the original templates.

Added daylight saving to yealink x templates

---

app/gateways/gateway_copy.php

Add these two missing properties to the copy.

Include profile and caller id type in copy

---

resources/switch.php

* The function now returns all bridges of an outbound route
* improved the function to do just one SQL query instead for each outbound route

outbound route to bridge add support for bridge failover

---

app/yealink/app_config.php
resources/templates/provision/yealink/t41s/y000000000068.cfg
resources/templates/provision/yealink/t42s/y000000000067.cfg
resources/templates/provision/yealink/t43u/y000000000107.cfg
resources/templates/provision/yealink/t46s/y000000000066.cfg
resources/templates/provision/yealink/t48s/y000000000065.cfg
resources/templates/provision/yealink/t4x/y000000000065.cfg
resources/templates/provision/yealink/t4x/y000000000066.cfg
resources/templates/provision/yealink/t4x/y000000000067.cfg
resources/templates/provision/yealink/t4x/y000000000068.cfg
resources/templates/provision/yealink/t4x/y000000000107.cfg
resources/templates/provision/yealink/t4x/y000000000108.cfg
resources/templates/provision/yealink/t4x/y000000000109.cfg
resources/templates/provision/yealink/t4x/y000000000116.cfg
resources/templates/provision/yealink/t52s/y000000000074.cfg
resources/templates/provision/yealink/t53w/y000000000095.cfg
resources/templates/provision/yealink/t54s/y000000000070.cfg
resources/templates/provision/yealink/t54w/y000000000096.cfg
resources/templates/provision/yealink/t57w/y000000000097.cfg
resources/templates/provision/yealink/t5x/y000000000070.cfg
resources/templates/provision/yealink/t5x/y000000000095.cfg
resources/templates/provision/yealink/t5x/y000000000096.cfg
resources/templates/provision/yealink/t5x/y000000000097.cfg

Enable Local Directory. Disabled by default to preserve existing behavior (variable unset in configuration file)

Yealink Local Directory

---

app/xml_cdr/xml_cdr_inc.php

Seems to be an accident, it exists in 4.2 and 4.5

[4.4] Missing support for * on CDR

---

app/scripts/resources/scripts/app/follow_me/index.lua

Accountcode of the called extension should be set for follow me

Follow me set accountcode for external destinations

---

app/extensions/extension_edit.php

[4.5] Fix Wrong CIDR

---

app/xml_cdr/xml_cdr_inc.php

Reverts fusionpbx/fusionpbx#5615

Revert "Order by start_epoch to Speed Up Query Execution"

---

app/extensions/app_config.php
app/extensions/extension_edit.php

More permissions, it will allow non-admin users to auto-manage themselves on some basic fields.

[4.5] More permssions on the extensions

---

app/destinations/destination_edit.php

Add a missing non-breaking space to fix the positioning of the checkbox.

Destination Emergency Checkbox Spacing Fix

---

app/xml_cdr/xml_cdr_details.php

When there's a single app in the app log it's saved as an single object in the json not as an array of objects

xml_cdr_details fix app log

---

app/call_centers/app_config.php
app/call_centers/call_center_agent_edit.php
app/scripts/resources/scripts/app/xml_handler/resources/scripts/configuration/callcenter.conf.lua

If call center recording is enabled it will record calls for all agents if disabled it won't record for anyone.  Added ability to enable recording on individual call center agents even call center recording is disabled.

call center agent record

---

app/call_centers/call_center_agent_edit.php

`$agent_record` is a string not a Boolean

Fix agent record selected

---

app/xml_cdr/xml_cdr_details.php

when `$key` was 0 PHP always evaluated to true causing an empty row

fix comparison operator

---

app/ivr_menus/app_defaults.php

Let users choose what they want

More DB compatibility 

---

app/scripts/resources/scripts/app/follow_me/index.lua

Fix follow me to record local destination if that destination has call recording enabled.

Follow me fix call recording

---

app/call_broadcast/app_config.php
app/call_broadcast/call_broadcast_edit.php
app/call_broadcast/call_broadcast_send.php

This will allow you to specify a toll allow variable for call broadcasts.

Add Toll Allow to Call Broadcast

---

app/yealink/app_config.php

Duplicate variable yealink_ringtone_url and uuid 7af991ec-ddb9-4942-a05d-d1acc529fef5

Duplicate variable yealink_ringtone_url and uuid

---

resources/check_auth.php

Unassigned group permissions was being assigned on login

fix unassigned group permission

---

resources/templates/provision/yealink/t46g/y000000000028.cfg

added wallpaper file resolution for easier access as well as some descriptions on variables.

Updates to template for Yealink T46G

---

app/extensions/extension_edit.php

Cache deleting was broken for user users without the extension_user_context permission

Extension fix cache not clearing

---

app/scripts/resources/scripts/dtmf_handler.lua

this will give the dtmf_history (similar to the transfer_history variable)
the use cases of this are only limited to the imagination

[4.5] DTMF handling

---

resources/install/scripts/dtmf_handler.lua

[4.4] DTMF handling

---

app/destinations/resources/classes/destinations.php

Added a button that links directly to the currently selected destination's edit page if you have the permission to view or edit it.
Possible Improvements: 
- Add this to the older style destination select.
- Update the button automatically when a new destination is selected. I don't know how to do that yet. It currently only updates when the change is saved.

Add direct link button for dynamic destinations

---

app/destinations/resources/classes/destinations.php
app/destinations/resources/destinations.php
app/voicemails/app_config.php

This allows the new destination edit button to change and update dynamically as different options are selected.
This sets the UUID as the ID in the options list. The we use the javascript onclick listener to get the id(uuid) of the selected option and open the link to the edit page. This also adds voicemail_uuid to the destinations array to enable that to work with this feature.
- This currently always shows the button even if it will not link to anything. The button should be hidden if nothing can be linked to/edited.

Dynamic Destination Edit Button

---

resources/templates/provision/grandstream/grp261x/phonebook.xml
resources/templates/provision/grandstream/grp261x/{$mac}.xml

This adds in a new configuration template that works for all GRP261x phones with newer firmwares that support the v2 XML format that uses human readable names. I have been using this template in production now for a few months without issue currently on a GRP2616 and a GRP2613.

GRP261x configuration using the new v2 XML format

---

app/dialplans/resources/classes/dialplan.php
app/scripts/resources/scripts/app/voicemail/resources/functions/record_message.lua

Transcriptions using Google were broken after last commit. 
transcribe_alternate_language was not defined anywhere it Google would return 400 error.
Added variable to fix the issue

Fix voicemail transcription using Google

---

themes/default/template.php

Disabled domains can still by managed by going to the Domains app and clicking Manage.

Hide Disabled Domains from domain Selector

---

core/default_settings/default_settings.php
core/domain_settings/app_languages.php
core/domain_settings/domain_settings.php

Going back and forth between domain settings and default settings is much easier now! Quality of life improvements are my bread and butter!

Add Domain and Global buttons on the respective settings page

---

app/dialplan_outbound/app_languages.php
app/dialplan_outbound/dialplan_outbound_add.php

Add shortcode outbound dialplan entry for 988 (Suicide lifeline USA)

add 988 national suicide prevention lifeline (USA)

---

app/fifo/app_languages.php

The suggested descriptions should be a bit easier for newer admins who want to know how a Queue works.

Updated the descriptions for some fields

---

app/extension_settings/extension_settings.php
app/extension_settings/resources/classes/extension_settings.php

extension setting used the database class instead of the extension_setting class causing not to clear the cache

fix extension settings using wrong class

---

resources/templates/provision/grandstream/ht801/{$mac}.xml

We are at our company, SmartIP, using grand stream ATA ht801. But I did not find template for ht801. So I created template for it.

Created Template file for HT801

---

app/devices/device_imports.php

It is possible to import duplicate MAC addresses via the bulk CSV import if they do not have their `device_uuid` column in the CSV. MAC addresses are already considered globally unique and duplication should not be allowed. Needs #5775 to ensure the MAC address is normalized for a database lookup.
- Create the database object only once throughout the import action section
- Add in a new block that will populate `device_uuid` if the `device_uuid` field was not provided by the CSV but the `device_mac_address` was provided.
- This block will also verify that the `domain_uuid` matches and if it does not it will disallow the import with an error message displayed to the user.
- This adds a database lookup for every device line entry in the database. Looking at `database.php` it doesn't look …

Check for duplicate MAC addresses in the device import

---

app/dialplans/resources/switch/conf/dialplan/470_valet_park_auto.xml
app/dialplans/resources/switch/conf/dialplan/470_valet_park_in.xml
app/dialplans/resources/switch/conf/dialplan/475_valet_park_out.xml

Reverts fusionpbx/fusionpbx#5612

Revert "Improve the valet_park_auto dialplan to support auto out and whole lot BLF monitoring"

---

app/dialplans/resources/switch/conf/dialplan/470_valet_park.xml

Reverts fusionpbx/fusionpbx#5611

Revert "Update the valet park dialplan to allow matching park+5901-5999"

---

app/dialplans/resources/switch/conf/dialplan/470_valet_park_auto.xml
app/dialplans/resources/switch/conf/dialplan/470_valet_park_in.xml
app/dialplans/resources/switch/conf/dialplan/475_valet_park_out.xml

After discussion this change is acceptable. The other change will require more work and LUA code to keep backwards compatible.

Unrevert the revert for valet-auto

---

app/call_centers/cmd.php

was checking for wrong variable `$queue`

[callcenter] fix cmd

---

app/call_centers/call_center_queue_edit.php
app/xml_cdr/app_config.php
app/xml_cdr/resources/classes/xml_cdr.php

* export call_center_queue_uuid channel variable to agent legs for cdr import (no need for sql)
* add call_center_queue_uuid field to cdr for referencing the call center queue table (cc_queue is a freeswitch variable for  the queue name)

[call_center] export call_center_queue_uuid channel variable to agent legs for cdr import

---

app/extensions/extension_edit.php

* remove duplicate caller id names from the list
* don't use destination description as a caller id name (descriptions aren't usually valid caller id's)

[extensions] Improve outbound caller id select list

---

app/scripts/resources/scripts/follow_me.lua

since commit https://github.com/fusionpbx/fusionpbx/commit/a2e4fd00bd805ef628a6f2e676426b6a0d33eeae we allow custom dial strings and don't null the dial string for DND

[follow me] *21 don't null dial string

---

app/scripts/resources/scripts/app/xml_handler/resources/scripts/configuration/ivr.conf.lua

You already do that in the dialplan, no need to do it here

[4.5] Fix doube ivr_menu_cid_prefix

---

app/scripts/resources/scripts/app/voicemail/resources/functions/menu_messages.lua

reference https://www.lua.org/pil/6.3.html

Voicemail use proper tail calls

---

app/devices/device_edit.php

When a device is being updated then we want to persist the old values

[devices] Use the default settings only when adding a device

---

app/destinations/destination_imports.php

Allows the use of TAB character for a delimiter while importing.

Allow the use of TAB as a delimiter

---

app/scripts/resources/scripts/directory.lua

Added the ability to press * to transfer back to the previous menu based on value of ${rdnis}.

Company Directory: Add Press * to Return to Previous Menu

---

resources/templates/provision/yealink/t46g/y000000000028.cfg

I made sure that the variable I added was consistent with the same naming convention for T46S,

Added variables to configure screensaver

---

resources/templates/provision/grandstream/ht814/{$mac}.xml

Based on HT818 Template but only with 4 FXS Ports.

Add "Grandstream HT814" provisioning template

---

app/fax/fax_emails.php

toll_allow should be honored for outbound routes

Honor toll_allow when using email-to-fax

---

core/dashboard/index.php

Also fixed bug for re-rendering the chart.

Add alert for unsaved changes in dashboard edit.

---

app/scripts/resources/scripts/app/xml_handler/resources/scripts/directory/directory.lua

using !USER_BUSY gives an error `Could not locate channel type !USER_BUSY`

[xml handler] Fix error channel

---

app/contacts/app_config.php
app/contacts/contact_edit.php

Changes:
- Using CSS Grid
- Mobile Friendly
- Responsive

Contacts version 2.0

---

app/contacts/contact_edit.php

Fixed icon styling and required class

---

app/scripts/resources/scripts/app/conference_center/index.lua
app/scripts/resources/scripts/app/emergency_notify/index.lua
app/scripts/resources/scripts/app/failure_handler/index.lua
app/scripts/resources/scripts/app/fax/resources/scripts/queue/tasks.lua
app/scripts/resources/scripts/app/hangup/index.lua
app/scripts/resources/scripts/app/ring_groups/index.lua
app/scripts/resources/scripts/app/voicemail/resources/functions/send_email.lua
app/scripts/resources/scripts/fax_retry.lua
app/scripts/resources/scripts/resources/functions/send_mail.lua

Add email_from to the send_mail function

Add from send_mail function consistently.

---

app/yealink/app_config.php
resources/templates/provision/yealink/t48u/directory.xml

- Added t48u directory.xml
- Fixed mislabeled description

Updates to yealink provisioning

---

resources/templates/provision/grandstream/gxp2130/{$mac}.xml
resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/gxp2140/{$mac}.xml
resources/templates/provision/grandstream/gxp2160/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml

Allows the label background to be toggled

Add grandstream_label_background varable

---

app/dialplan_outbound/dialplan_outbound_add.php

don't match if first digit of NPA and NXX are a 1

[outbound route] Improve north America regex

---

app/contacts/app_config.php
app/provision/app_config.php
app/provision/resources/classes/provision.php

Remove provision contact permissions for a broader setting.

Add contact permissions to default settings. Default false

---

app/dialplans/resources/switch/conf/dialplan/050_user_record.xml

use RECORD_ANSWER_REQ variable to start recording after answer

[user_record] move back to record_session

---

resources/templates/provision/grandstream/gxp2100/{$mac}.xml

Add grandstream_idle_screen_server_path setting

---

core/domains/domains.php
resources/check_auth.php

[5.0] Fixes NULL in _SESSION[context]

---

app/call_block/resources/classes/call_block.php

Hotfix for 11 digit format in call_block

Remove the country code if not e.164.

---

app/fax_queue/resources/job/fax_send.php

there was identical lines of code.

removed duplicate code

---

app/scripts/resources/scripts/app/voicemail/resources/functions/listen_to_recording.lua

Replaced // characters with --

BUG FIX: incorrect comment characters

---

app/click_to_call/click_to_call.php

Fix Click to Call

---

app/scripts/resources/scripts/app/fax/resources/scripts/hangup_rx.lua

to support systems that have the system commands disabled

[fax] replace bg_system with os.execute

---

app/extensions/extension_edit.php

Remove is_numeric check for voicemail id when creating the directory.

remove is_numeric check for voicemail id

---

app/scripts/resources/scripts/app/xml_handler/resources/scripts/configuration/callcenter.conf.lua

Fix xml_handler when edit Max Wait Time With No Agent Reached when edit Call Center

Fix Call Center max wait time with no agent reached

---

core/default_settings/default_setting_edit.php
core/default_settings/default_settings.php

Used in edit, add, and back buttons and handling passing through the category for the toggle.

Category and Search pass-through

---

app/call_flows/call_flow_edit.php

Trigger event on status change from WebUI

[call_flow] Adjust lamp on web changes

---

core/dashboard/app_config.php
core/dashboard/app_languages.php
core/dashboard/dashboard_edit.php
core/dashboard/index.php

Adds the ability to collapse or hide widget details with a dashboard widget setting.

Add details state dashboard widget setting

---

app/call_forward/resources/dashboard/call_forward.php

Fixed a bug where the chart doesn't show up when all the values are 0.

Fixed call forward chart not showing up

---

app/system/app_config.php
app/system/app_languages.php
app/system/system.php

Add database information

---

resources/classes/database.php

Remove '&' on static function new.

Remove '&' on new

---

resources/templates/provision/yealink/t54w/y000000000096.cfg

Added 2 new variables for changing the idle clock {$yealink_idle_clock} and transparency of the dsskeys {$yealink_idle_dsskey_title_transparency}

Added 2 new variables for T54W provisioning

---

core/upgrade/index.php

Sets the list of menus to upgrade sorted ascending, and leaves 'default' menu as default selected for consistency and ease.

upgrade menu sorted

---

app/vars/app_defaults.php

Fixes this
`<X-PRE-PROCESS cmd="set" data="busy-au-tone=v=-13;%(375,375,420);v=-23;%(375,375,420)" category="Tones" enabled="true" uuid="333c5a08-2389-4fb1-a398-a5a98e4f447a"/>
<X-PRE-PROCESS cmd="set" data="bong-us-tone=v=-7;%(100,0,941.0,1477.0);v=-7;>=2;+=.1;%(1400,0,350,440)" category="Tones" enabled="true" uuid="4be3153c-5e8d-4b2e-82f0-c89ce7006a0d"/>`

Fixes some vars.xml import

---

app/call_centers/call_center_agent_edit.php
app/call_centers/call_center_queue_edit.php
app/scripts/resources/scripts/app/xml_handler/resources/scripts/directory/directory.lua
app/scripts/resources/scripts/resources/functions/xml.lua
resources/classes/xml.php

All values saved into the XML dialplan are vulnerable to XSS and to getting expanded to freeswitch API commands.

[security] prevent xml injection and executing switch api cmds.

---

app/call_recordings/app_defaults.php
app/call_recordings/app_languages.php
app/call_recordings/call_recordings.php

Include destination number in call recordings view

[call_recordings] Add destination to view

---

resources/templates/provision/snom/D120/{$mac}.xml
resources/templates/provision/snom/D315/{$mac}.xml
resources/templates/provision/snom/D345/{$mac}.xml
resources/templates/provision/snom/D375/{$mac}.xml
resources/templates/provision/snom/D385/{$mac}.xml
resources/templates/provision/snom/D712/{$mac}.xml
resources/templates/provision/snom/D715/{$mac}.xml
resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D725/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D745/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml

This PR will add support for the secondary outbound proxy for Snom phones.
**Note:** this is only available in firmware 8.7.x onwards

Added support for secondary outbound proxy on Snom D series phones.

---

core/install/resources/classes/install.php
resources/require.php

An enhancement that adds simple options to show what errors to show in the web interface. This also fixes a bug that causes an error in PHP8.

[bug] error reporting options user, dev, all

---

resources/classes/domains.php

The focus is on the domains->upgrade() method only

Frytimo pr remove unused variables and fix clobbering

---

core/authentication/app_languages.php
core/authentication/resources/classes/plugins/totp.php
core/authentication/resources/views/email.htm
core/authentication/resources/views/login.htm
core/authentication/resources/views/totp.htm
core/authentication/resources/views/totp_secret.htm
core/authentication/resources/views/username.htm

Auto create TOTP secret after successful database authentication when the TOTP secret has not been set.

Auto create TOTP secret

---

core/authentication/resources/classes/authentication.php
core/authentication/resources/classes/plugins/database.php

When the URL domain doesn't match the user's domain
Authentication can use domain from the username.
username:
user@domain

[bug fix] get the domain from the username

---

app/xml_cdr/xml_cdr.php
app/xml_cdr/xml_cdr_inc.php
app/xml_cdr/xml_cdr_search.php
app/xml_cdr/xml_cdr_statistics.php
app/xml_cdr/xml_cdr_statistics_inc.php

Remove deprecated warnings for PHP version 8.1

Fix xml cdr for PHP 8.1

---

core/domain_settings/domain_setting_edit.php

Recent updates broke time zone setting for domain settings

Fix time zone setting for domain

---

themes/default/template.php

This will hopefully reduce the chances of search engines indexing a FusionPBX instance.

add a robots meta tag to reduce chances of private fusionpbx instances appearing in public Google search results

---

app/system/resources/dashboard/system_status.php

Simplified version of uptime for php 8.1

Simplified version of uptime for Linux

---

app/email_templates/app_defaults.php
app/fax/app_defaults.php
core/authentication/app_defaults.php

Ship some german email templates by default.

German email templates

---

app/event_guard/resources/service/event_guard.php

include facility in openlog(), it fails without it on php 8.1

Update event_guard.php (PHP 8.1)

---

app/ivr_menus/ivr_menu_edit.php
app/recordings/recordings.php

Play button is added in IVR menu edit page. It will play the selected media file for IVR. It makes IVR options setup more convenient.

Play button in IVR Menu edit

---

app/sip_profiles/sip_profile_edit.php

add one space to fix sql error

5.1 Update sip_profile_edit.php

---

resources/classes/settings.php

Use parameters in the method call to eliminate array packing/unpacking and utilize the object $this properties

update the settings set method to use params instead of array

---

app/contacts/app_defaults.php
app/contacts/resources/classes/contacts.php
resources/classes/schema.php

Removed unused variables from unset command. Removed foreach config_list from schema->schema as it was already done in the constructor of schema.
Added class constants in contacts object but left the private variables for backwards compatibility.

Patch contacts calling multiple schemas

---

app/ring_groups/app_config.php
app/ring_groups/ring_group_edit.php

The adding range of extensions for ring groups

Ring groups extensions range

---

app/contacts/contact_edit.php

Has to be checked otherwise adding a contact with default setting contact permissions set to true would not work.

[PHP81] Check empty array

---

app/extensions/app_config.php
app/extensions/extensions.php

Showing Device address in extension list

Device address in extensions list

---

app/dialplans/dialplan_edit.php

Fix bug where a dialplan detail item was deleted but still shows in the XML dialplan.

Fix bug where a dialplan detail item was deleted but still shows in the XML dialplan

---

app/snom/app_config.php
resources/templates/provision/snom/360/{$mac}.xml
resources/templates/provision/snom/3xx/{$mac}.xml
resources/templates/provision/snom/7xx/{$mac}.xml
resources/templates/provision/snom/8xx/{$mac}.xml
resources/templates/provision/snom/D120/{$mac}.xml
resources/templates/provision/snom/D315/{$mac}.xml
resources/templates/provision/snom/D345/{$mac}.xml
resources/templates/provision/snom/D375/{$mac}.xml
resources/templates/provision/snom/D385/{$mac}.xml
resources/templates/provision/snom/D712/{$mac}.xml
resources/templates/provision/snom/D715/{$mac}.xml
resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D725/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D745/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml

Some clients require static IP addresses. This commit gives the ability to adjust to their needs.

change default DHCP perm value to match SNOM recommendation

---

app/provision/resources/classes/provision.php
resources/templates/provision/grandstream/grp2612/{$mac}.xml
resources/templates/provision/grandstream/grp2612w/{$mac}.xml
resources/templates/provision/grandstream/grp2613/{$mac}.xml
resources/templates/provision/grandstream/grp2614/{$mac}.xml
resources/templates/provision/grandstream/grp2615/{$mac}.xml
resources/templates/provision/grandstream/grp2616/{$mac}.xml
resources/templates/provision/grandstream/grp261x/{$mac}.xml
resources/templates/provision/grandstream/grp26xx/{$mac}.xml
resources/templates/provision/grandstream/gxp2130/{$mac}.xml
resources/templates/provision/grandstream/gxp2160/{$mac}.xml

* Fixed issue with registration time for Grandstreams with registration expiration time set for less than 60 seconds
* Updated Grandstream GXP provisioning files to use values from registration expiration time
* Fixed physical key profile issues on GXP & GRP phones

Grandstream Provisioning File Updates

---

app/extensions/app_config.php
app/extensions/extension_edit.php

Set a default value for ring time delay before voicemail

add default value for ring time delay before voicemail

---

app/emergency/emergency.php

Add the column view when showing all domains. Also, use only one database instance with the assigned app name and app uuid for tracking.

add domain column when showing all domains

---

resources/templates/provision/snom/PA1plus/{$mac}.cfg

PA1plus is the product replacement for PA1

Create snom PA1 plus

---

app/fax/fax_send.php

This adds a date/time stamp on the fax coversheet.

Include Date on Fax Coversheet

---

app/recordings/recording_edit.php
app/recordings/recordings.php
core/ai/resources/interfaces/ai_speech.php
core/ai/resources/interfaces/ai_transcribe.php

- Fix typo for $SESSION to be $_SESSION
- expand interface requirements to include languages and voices
- set defaults in the recordings to stop warnings for undefined variables

Ai bug fixes and update interfaces

---

app/fax/app_config.php
app/fax/fax_send.php

Cover Page Option

---

app/destinations/resources/classes/destinations.php

settings was being set in constructor but property was missing from object

settings was being set in constructor but property was missing

---

app/dialplans/dialplans.php

You can disable this permission to hide global dialplans from the list

Use dialplan_global permission

---

app/email_queue/resources/functions/transcribe.php

* v2 doesn't require to have api_key set
* allow setting setting a path to the application credentials
* check only ones if the file path exists

[voicemail transcription] fix google v2

---

app/switch/resources/conf/languages/ar/vm/sounds.xml
app/switch/resources/conf/languages/de/vm/sounds.xml
app/switch/resources/conf/languages/el/vm/sounds.xml
app/switch/resources/conf/languages/en/vm/sounds.xml
app/switch/resources/conf/languages/es/vm/sounds.xml
app/switch/resources/conf/languages/fr/vm/sounds.xml
app/switch/resources/conf/languages/fr/vm/voicemail.xml
app/switch/resources/conf/languages/he/vm/sounds.xml
app/switch/resources/conf/languages/it/vm/sounds.xml
app/switch/resources/conf/languages/nl/vm/sounds.xml
app/switch/resources/conf/languages/pt/vm/sounds.xml
app/switch/resources/conf/languages/ro/vm/sounds.xml
app/switch/resources/conf/languages/ru/vm/sounds.xml
app/switch/resources/conf/languages/sv/vm/sounds.xml
app/switch/resources/conf/languages/tr/vm/sounds.xml
app/switch/resources/conf/languages/uk/vm/sounds.xml
app/switch/resources/scripts/app/voicemail/resources/functions/main_menu.lua

Split out macros for voicemail_message_count to be two separate macros in the xml files to allow more flexibility in translation.
Also updated French xml files to fix French language grammar/syntax.

[vm] Split new/saved message count macros + improve french translations

---

core/upgrade/upgrade_menu.php

Software name was not showing for option 1a

Include software_name in the global declaration

---

resources/classes/auto_loader.php

Use the magic __DIR__ constant instead of document_root or another predefined constant

update auto_loader to use magic dir constant

---

resources/classes/config.php
resources/classes/database.php
resources/classes/domains.php

Rewrite the config class that loads the config.conf file. This allows the database class to receive the config object and get the database information to connect to the database.

Update config and database classes

---

core/default_settings/default_settings.php
resources/classes/config.php
resources/classes/database.php
resources/classes/domains.php
resources/functions.php

- Use a singleton pattern in the database class to re-use the database object inside the permission_exists function.

Config class rewrite

---

app/call_centers/resources/dashboard/call_center_agents.php
app/devices/resources/dashboard/device_keys.php
app/voicemails/resources/dashboard/voicemails.php
app/xml_cdr/resources/dashboard/missed_calls.php
app/xml_cdr/resources/dashboard/recent_calls.php
core/dashboard/dashboard_edit.php
core/dashboard/index.php
themes/default/app_config.php

Added dashboard theme settings:
dashboard_chart_cutout
dashboard_chart_text_size
New messages, missed calls, and recent calls widgets chart type default to none.
Fixed some php errors on the dashboard.

Dashboard - Added chart cutout and text size default settings

---

app/snom/app_config.php
resources/templates/provision/snom/C520/{$mac}.xml

Adding support for Snom C520.
If this is approved there will be some nginx rewrite rules I will create a PR for.

Adding Snom C520 template

---

app/extensions/extension_imports.php

This commit will lower the case on all boolean values since if you enter the value as not all lower-case the value will be invalid.

Fix importing extensions

---

app/dialplans/resources/switch/conf/dialplan/470_valet_park.xml

Include 59 in the park_lot variable to support the BLF status.

Update valet_park to include 59 in the park_lot variable

---

resources/templates/provision/snom/C520/directory.xml
resources/templates/provision/snom/C520/{$mac}.xml

I've added support for directory on C520 phone as well as I have added the web interface password to follow the default settings in Fusion

C520 directory changes to template

---

app/extensions/extension_imports.php

I missed a few fields that should have been added to my previous commit.
Previous PR that was already merged was [PR6985](https://github.com/fusionpbx/fusionpbx/pull/6985)

More fixes for  importing extensions

---

resources/classes/settings.php

device_profile_settings and device_settings are never looked up in the database. This adds those methods with a more complete set of documentation on how the settings class works using hierarchical overriding.

Add methods to handle device and add documentation

---

resources/classes/command_option.php
resources/classes/service.php

This is the first implementation of abstract class service.

introduce new abstract service class

---

core/upgrade/index.php

move dollar sign to inside the curly brace

move dollar sign to inside the curly brace

---

resources/classes/database.php

add function to return the config object used to create database object

add function to return the config object used to create database object

---

resources/classes/auto_loader.php

allow searching in separate folders for traits

allow auto_loader to search in traits directories

---

app/voicemails/app_config.php

I do not believe this default settings is used anymore since the new transcription method started being used.

remove unused variables

---

app/voicemails/app_config.php

I enhanced the description of this default setting to be more obvious to new users.

clarified one of the transcription default setting

---

app/access_controls/resources/classes/access_controls.php

format class for comments to be at the same tab stop

format class for comments to be at the same tab stop

---

app/voicemails/resources/classes/voicemail.php

Add ability for voicemail maintenance to be handled by the maintenance class

Voicemail maintenance

---

app/xml_cdr/resources/classes/xml_cdr.php

add the ability for the maintenance app to clean out old CDRs

add maintenance function to the xml_cdr

---

app/voicemails/app_config.php

This is to fix my mistake in https://github.com/fusionpbx/fusionpbx/pull/7002

bug fix for transcription

---

app/provision/index.php

Fixed comment that Mark and I found to be incorrect on a call

Fixed comment

---

app/email_queue/resources/jobs/email_send.php

Use a single instance of the object instead

email_send_remove_extra_database_objects

---

app/xml_cdr/app_config.php
app/xml_cdr/resources/classes/xml_cdr.php

update database_maintenance method in xml_cdr with the latest changes in the maintenance service

update database_maintenance method in xml_cdr with the latest changes in the maintenance service

---

app/voicemails/app_config.php
app/voicemails/resources/classes/voicemail.php

Update the public static function filesystem_maintenance in voicemail class to use the newest changes in the maintenance class. The maintenance class now has a constant defined for the subcategory used within the project.

update voicemail with the latest changes to the maintenance application

---

app/system/app_config.php
app/system/resources/classes/session.php

implement changes in to the session class for maintenance

implement changes in to the session class for maintenance

---

core/users/app_config.php
core/users/resources/classes/users.php

implement changes in to the user_logs class for maintenance application

implement changes in to the user_logs class for maintenance application

---

app/xml_cdr/app_config.php
app/xml_cdr/resources/classes/xml_cdr.php

Specify the CDR category for the maintenance application

specify the cdr category for xml_cdr

---

app/fax_queue/app_config.php
app/fax_queue/resources/classes/fax_queue.php

implement changes in to the fax queue class for maintenance application

implement changes in to the fax queue class for maintenance application

---

app/database_transactions/app_config.php
app/database_transactions/resources/classes/database_transactions.php

Database transactions maintenance

Database transactions maintenance

---

app/avaya/app_config.php
resources/templates/provision/avaya/J139/directory.xml
resources/templates/provision/avaya/J139/{$mac}.cfg
resources/templates/provision/avaya/J169/{$mac}.cfg
resources/templates/provision/avaya/J179/{$mac}.cfg
resources/templates/provision/avaya/J189/{$mac}.cfg

Support for the Avaya J139 has been added and some minor fixes have been made. i've also added a comment showing the dimensions of the wallpapers in the template

added avaya J139 plus other changes to avaya

---

app/devices/device_edit.php

This fixes the QRCode generation for the BSDs

fix qrcode generation on BSD

---

core/default_settings/default_settings.php

move the permission checking outside of the for loop and instead set a boolean value for use inside the for loop

reduce permission_exists calls from 7,000+ to just 7

---

app/system/resources/classes/session.php

When using session_path, the session must be active and will automatically activate the session. This is a better method so that the session is never started.

Use ini_get to retrieve the session path instead of using session_path

---

resources/functions.php

This is the function that will be used in the Messages app to avoid using file_get_contents since it requires PHP INI settings and curl does not.

adding function url_get_contents to be used in app/messages

---

app/voicemails/resources/classes/voicemail.php

The method overwrites the object property initially set when the method is called. This causes any subsequent calls to be incorrect. Removing this keeps the initial objects property intact. The method voicemail_messages is only used internally from the messages method for getting message details in the voicemails. This has been set to a private method to reflect this type of use.

method messages in object voicemail erases the property voicemail_uuid

---

app/event_guard/resources/service/event_guard.php
app/ring_groups/ring_group_edit.php
app/vars/app_defaults.php
app/xml_cdr/xml_cdr_inc.php
core/databases/databases.php
core/groups/group_edit.php

The database object is a global variable that contains a database object reference and should not be unset.

Remove the unset($database) statements

---

themes/default/css.php

This margin makes the Messages app have a scrollbar that is not needed and makes the application look bad.
I've removed this in my lab and do not see any issues with other pages.

remove footer bottom margin

---

resources/classes/token.php

exit for loop when matching token for slight performance increase

exit for loop when matching token for slight performance increase

---

core/authentication/resources/classes/authentication.php

Logging after all checks are complete ensures the session ID is correct when logging it in the user_logs table

regenerate the session after cidr check is complete and then log

---

core/authentication/resources/classes/authentication.php
core/authentication/resources/classes/plugins/database.php

Pass the settings and authentication objects to the plugins to re-use existing objects

pass objects to authentication plugins when possible

---

app/call_recordings/call_recordings.php
app/ivr_menus/ivr_menu_edit.php
app/music_on_hold/music_on_hold.php
app/recordings/recordings.php
app/voicemail_greetings/voicemail_greetings.php
app/voicemails/voicemail_messages.php
app/xml_cdr/xml_cdr.php
themes/default/css.php
themes/default/template.php

- Added the ability to seek on the audio player. When a user clicks on the audio player, the playback needle is repositioned to the location of the cursor and the audio is played from that point (If currently in Play mode) or left idle at that position (If in Paused mode). This has been added across all applications with an audio player.
- Fixed some audio player display issues in Recordings
- Extended playback needle just a little

Added player seek ability

---

app/log_viewer/log_viewer.php

This PR fixes searching when pressing enter while in the textbox. Previously, you needed to press the update button to get the search results to work.
The issue was that the `$_REQUEST['submit']` is not sent in the post when the enter key is hit.
Below is screenshots of the POST from my developer tools window when pressing enter in the form as well as pressing the update button.
UPDATE BUTTON:
ENTER KEY:

fix search when pressing enter in textbox

---

app/fax/fax_send.php
app/fax_queue/fax_queue.php
app/xml_cdr/resources/classes/xml_cdr.php
resources/classes/email.php

update template to match new boolean in settings

update template to match new boolean in settings

---

app/xml_cdr/app_config.php
app/xml_cdr/app_languages.php
app/xml_cdr/resources/classes/xml_cdr.php
app/xml_cdr/xml_cdr.php
app/xml_cdr/xml_cdr_inc.php
app/xml_cdr/xml_cdr_search.php

This PR is to add the functionality to have a dropdown to quickly search for calls that went to a particular ring group.
This should help make reporting on RGs quicker and easier and more user-friendly.
Here is a screenshot of it:

Ring Group search in CDR

---

resources/templates/provision/grandstream/gxv3240/phonebook.xml

- Regroups multi line contacts to be single contact with multiple numbers
- Creates groups based on contact type. groups contacts with more then number into one contact. Sets FirstName to contact_organization if there is no given or family name but contact_organization is set
- Labels work, home, and mobile numbers with all others set as other
- Sets Primary to line with phone_primary set (will set Primary for each if multiple lines have phone_primary set even though phone  will likely only use one of the tags)

Rewrite gxv3240/phonebook.xml adds groups and regroups multi line contacts to be single contact

---

app/voicemails/voicemails.php

fix voicemail message count when viewing all domains

fix voicemail message count when viewing all domains

---

app/destinations/app_languages.php

Small language fix to include en-us for SMS/MMS to email notifications

fix-sms/mms-to-email-en-us

---

app/xml_cdr/xml_cdr_extension_summary.php

rename extension summary export/download from 'user-summary.csv. to 'extension-summary.csv'

rename extension summary csv export

---

core/default_settings/default_settings.php

Harder to guess when length is also hidden

Security, Use the same number of characters for the masked password

---

resources/templates/provision/grandstream/wp826/phonebook.xml
resources/templates/provision/grandstream/wp826/{$mac}.xml

This template is customized for WP826 and may also works for WP816/WP836

Add grandstream wp826 template

---

app/switch/resources/scripts/app/voicemail/index.lua
app/voicemails/app_config.php

Hi,
I saw that there was no way for connecting voicemail messages to a call, so i added a call_uuid in voicemail_messages table.
Can anyone help me how to add the extra column in this pull request?

Update voicemail script to add call_uuid with voicemail messages

---

app/voicemails/voicemails.php

Update the voicemails.php file to use settings class where possible

Voicemails use settings object where possible

---

app/registrations/resources/dashboard/registrations.php
core/dashboard/index.php
core/dashboard/resources/dashboard/icon.php

fix dashboard php warnings

---

app/devices/device_edit.php

removed device_label duplicated in 2 locations

remove device_label duplicates

---

resources/classes/schema.php

format schema class using auto format
No other changes have been made

format schema class

---

app/provision/resources/classes/provision.php

Server port is calculated but should not be incremented by 1 as this will cross in to the TLS ports.

remove the automatic setting of server connection port in provisioning

---

resources/classes/menu.php

initialize variable before use

fix php warning in menu class

---

app/emergency/emergency.php

change the order of the columns

date column before time column

---

resources/require.php

Load the auto_loader first
Use the config object to find config.conf file and declare global
Use the database object and declare global
Use the settings object and declare global

Optimize require.php

---

resources/functions.php

fix missing quotes on parameter default value

fix missing quotes on parameter default value

---

core/email_templates/app_defaults.php

escaping character not needed on the template_subject

remove escaping character typo

---

resources/classes/settings.php

Allows checking the settings object for the currently loaded domain and user uuid

Create get methods for domain_uuid and user_uuid

---

app/voicemails/voicemail_edit.php

Voicemail transcription in voicemail_edit.php is not visible despite having the correct permissions. This is a fix for that.

bug fix for voicemail edit transcription

---

resources/templates/provision/grandstream/grp2612/{$mac}.xml
resources/templates/provision/grandstream/grp2612w/{$mac}.xml
resources/templates/provision/grandstream/grp2613/{$mac}.xml
resources/templates/provision/grandstream/grp2614/{$mac}.xml
resources/templates/provision/grandstream/grp2615/{$mac}.xml
resources/templates/provision/grandstream/grp2616/{$mac}.xml
resources/templates/provision/grandstream/gxp2130/{$mac}.xml
resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/gxp2140/{$mac}.xml
resources/templates/provision/grandstream/gxp2160/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml

Fix user id instead of auth id used in grandstream template

Fix user id instead of auth id used in grandstream template

---

app/yealink/app_config.php
resources/templates/provision/yealink/cp965/y000000000143.cfg
resources/templates/provision/yealink/t34w/y000000000171.cfg
resources/templates/provision/yealink/t43u/y000000000107.cfg
resources/templates/provision/yealink/t44w/y000000000174.cfg
resources/templates/provision/yealink/t46u/y000000000108.cfg
resources/templates/provision/yealink/t53/y000000000095.cfg
resources/templates/provision/yealink/t53w/y000000000095.cfg
resources/templates/provision/yealink/t54w/y000000000096.cfg
resources/templates/provision/yealink/t57w/y000000000097.cfg
resources/templates/provision/yealink/t5x/y000000000095.cfg
resources/templates/provision/yealink/t5x/y000000000096.cfg
resources/templates/provision/yealink/t5x/y000000000097.cfg

Add to default setting and other templates using wifi settings

Add wifi function enabled

---

resources/templates/provision/yealink/w60b/y000000000077.cfg

Adding Alarm server lines to be used with ver 85 firmware and the W59R handset.

Yealink W60B Updates

---

app/sip_status/sip_status.php

Added function to sort the 'sofia xmlstatus' SIP profiles alphabetically to match the sort order lower down in the page.

Sort the 'sofia xmlstatus' profiles alphabetically

---

resources/templates/provision/yealink/t48u/y000000000109.cfg

Bugfix for T48u

---

app/yealink/app_config.php

T44W requires at least 108.87.0.15 to add the capability for 12-hour time format

Add yealink T44W firmware

---

app/active_calls/resources/classes/active_calls_service.php
app/active_calls/resources/classes/extension_filter.php
core/websockets/resources/classes/subscriber.php

When a user is assigned to an extension, they can now view their calls on the dashboard widget.

Add extension handling to subscriber

---

app/active_calls/resources/classes/active_calls_service.php
core/websockets/resources/classes/subscriber.php
core/websockets/resources/classes/websocket_service.php

Fix active calls eavesdrop

---

app/active_calls/active_calls.php

fix missing hangup confirmation

fix missing hangup confirmation

---

app/active_calls/active_calls.php

Adjust the logic for handling the hangup when check boxes are used. Enable the Hangup All button.

add hangup all button

---

resources/templates/provision/fanvil/w611w/directory.xml
resources/templates/provision/fanvil/w611w/{$mac}.xml

Added initial w611w support.
Includes dsskey support (line 1-16)
Includes XML Contacts support with directory.xml

Add support for fanvil w611w 

---

resources/templates/provision/yealink/t85w/directory.xml
resources/templates/provision/yealink/t85w/favorite_setting.xml
resources/templates/provision/yealink/t85w/super_search.xml
resources/templates/provision/yealink/t85w/y000000000000.boot
resources/templates/provision/yealink/t85w/y000000000196.cfg
resources/templates/provision/yealink/t85w/{$mac}.cfg

This is the initial template for the T85W

Template for T85W

---

app/fax/app_config.php
app/fax/fax_advanced.php

Fax advanced - check certificate

Use true boolean types for switch theme toggle or drop-down box

---

app/xml_cdr/resources/service/xml_cdr.php

Only check database connection when CDR files exist

Only check database connection when CDR files exist
