app/xml_cdr/v_xml_cdr_import.php

When using redirect cdr also can contain e.g. `sip_redirect_contact_0` / `sip_redirected_to`.
I use `preg_replace_callback` to proceed all fields.
May be it more correct use `urlencode` because if we get xml with non UTF8 char we lost CDR.
```php
$xml_string = preg_replace_callback("/<([^><]+)>(.*?)<\/\g1>/",
function ($matches) {
// var_dump($matches);
return '<' . $matches[1] . '>' .
urlencode($matches[2]).
'</' . $matches[1] . '>';
},
$xml_string
);
```

Fix. Escape `<>` in all fields in CDR xml.

---

app/dialplan/resources/switch/conf/dialplan/380_hold_music.xml
app/dialplan/resources/switch/conf/dialplan/480_operator.xml

Default dilplan context contains all needed extension to does not use `feature` context.

Remove using `feature` context.

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

When uses number_alias contact should be searched by extension name.
Close #1022

Fix. Use extension to generate dial-string in xml_handler

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

Odd, but on some deployments LUA wont accept unixtime stamp functions (regardless it works on CLI). So, to workaround this, lets use os.time() which it returns the same value expected.

Use os.time instead of mysql native function

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

I think also possible just use `user` variable instead of `extension`.
But because I can not figure out why now uses `extension` I leave this.

Fix. Use number_alias in dial-string.

---

resources/install/scripts/intercept.lua
resources/install/scripts/intercept_group.lua

Now it is possible intercept call from local extension to the world.
Fix. intercept channels also in EARLY state.
One of my softphones return 180 Ringing with SDP (no 183 Progress).
And FreeSWITCH shows such channel as `EARLY` not as `RINGING`)

Fix. Allow intercept only outbound calls.

---

resources/install/scripts/app/toll_allow/index.lua

Add. Russian toll_allow templates.
This needs because we need
89%d is mobile except 8940%d which one is international.
Also it is possible move configuration in separate dirs e.g
```Lua
-- instead of `local templates = templates[country]`
local function prequire(m) 
local ok, err = pcall(require, m) 
if not ok then return nil, err end
return err
end
local templates = prequire("app.toll_allow.resources.countries." .. country)
```
and country file is like `RU.lua`
```lua
return {
{"international", "810%d+|8[89]40%d+|87%d%d%d%d%d%d%d%d%d"};
{"mobile",        "89%d%d%d%d%d%d%d%d%d"                  };
{"tollfree",      "8800%d%d%d%d%d%d%d|10[1-9]"            };
{"landline",      "8[3-68]%d%d%d%d%d%d%d%d%d%d"           };
{"unknown",       ""                                      };
}
```

Change. toll_allow use ordered template-list.

---

app/devices/device_edit.php
app/dialplan/resources/switch/conf/dialplan/999_local_extension.xml
resources/install/scripts/app/ring_groups/index.lua

Change. Use bind_bind_digit instead of bind_meta_app.
Change. Allow transfer and turn on recordings only for authorized users.
Fix. Use record_ext in recording in ring_group.
This allow configure other dtmf sequence like `*#` and `##`

Bind digit action

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

Change. Store data in cache based on UserID. 
Change. Support register with AuthID==UserID==Extension for extension with number-alias.
Add. Flag to switch mode for building dial-string.
1. We need only one record in memcache.
When we get SIP request we can find record by userid.
When we want check AuthID we do `user_data userid@domain attr id`
which also search record by userid.
2. We do not need check AuthID if we get record from DB. There already has check.
So we can reduce number of request to
* if there no record in memcached
- one memcache get (returns not found)
- database auth
- one memcache set
* if record in memcache
- one memcache get to retrieve XML
- one memcache get to check Extension==AuthID
You can configure ether you register with UserID=number-alias or UserID=Extension
In …

Store number alias in memcache

---

resources/classes/EventSocket.php
resources/switch.php

Problem with commands that do not return Content (e.g. sendevent)
In this case `event_socket_request` go to busy wait cycle without chance to success.
On my system it require alot process time and may take >30 sec to save one extension.

Fix. Parse ESL response more accurate.

---

app/dialplan/resources/switch/conf/dialplan/050_user_record.xml

This fix problem when DID transfers to IVR.
After that user make direct-dial to extension.
IVR do transfer but a-leg already answered and
api_on_answer did not call.

Fix. Start record when b-leg answer.

---

resources/install/scripts/app/xml_handler/resources/scripts/dialplan/dialplan.lua
resources/install/scripts/resources/functions/cache.lua
resources/install/scripts/resources/functions/log.lua

This is just suggestion about make code easy to write/read.
`dialplan.lua` is just example of how to use this classes.
Log class replace
```Lua
freeswitch.consoleLog("notice", "[xml_handler] " ....)
```
to
```Lua
-- `local` here is mondatory
local log = require"resources.functions.log"["xml_handler"]
log.notice(....)
log.noticef("%s", "message") -- formatted version
```
Cache class escape symbols `\` and `'` automatically

Add Log and Cache classes

---

resources/switch.php

It was not possible to send faxes to destinations starting with * or +.

fixed fax destination with * or + in number

---

resources/install/scripts/app/ring_groups/index.lua
resources/install/scripts/intercept.lua
resources/install/scripts/intercept_group.lua
resources/install/scripts/resources/functions/channel_utils.lua

With enterprise call each outbound channel has its own call_uuid.
But we have to use `intercept` for call_uuid of inbound channel.
I see problen only with loopback. 
If outbound call make call to user via loopback but I think fusion does not do this.

Fix. Intercept enterprise ring group.

---

app/time_conditions/app_languages.php
app/time_conditions/time_condition_edit.php

When adding a new time condition it always gets generated as the last one, sometimes this isn't desired and the solution is to edit de dialplan manually and change the group for all the entries, which can be tedious if you have multiple conditions.
With this the "order" of the dialplan is also presented in the time condition form so can be edited.
PS. A drag&drop interface would be more intuitive so it doesn't presents the group_id to the final user but my javascript is kinda basic for doing that :/

Add. Ability to order the time conditions

---

resources/install/scripts/intercept_group.lua

If Alice calls Bob's mobile and Bob returns a "183 Session progress" with SDP (for example if the mobile has no service) the call stays in EARLY callstate in the database.
If Charlie (from the same Call Group as Alice) dials "*8", the outgoing call from Alice gets chosen as an "interceptable" call and freeswitch bridges Alice and Charlie's legs, sending a "CANCEL - Reason: SIP;cause=200;text="Call completed elsewhere" to Bob's call leg.
This should fix it. We make sure that the direction of the call is outbound.

Fix. Call intercept - a scenario where an outgoing call can be intercepted

---

resources/install/scripts/call_flow.lua
resources/install/scripts/call_flow_monitor.lua
resources/install/scripts/resources/functions/presence_in.lua

* Move code to turn on/off BLF to separate function.
```Lua
presence_in.turn_lamp( toggle == "false",
call_flow_feature_code.."@"..domain_name,
call_flow_uuid
);
```
<b>One note</b>
Turn on code define `event:addHeader("status", "Active (1 waiting)");`
Turn off code define `event:addHeader("state", "Active (1 waiting)");`
I leave only `event:addHeader("status", "Active (1 waiting)");` in both cases.
Tested on Grandstream GXP-2000
* Close temp file in call_flow_monitor because on Windows it prevent to remove it.
* Connect/release to database inside call_flow_monitor loop.
* Check successful connection to database in call_flow_monitor loop so monitor did not crash
if connection temporary lost.

Fix small bugs and clear code in call_flow.

---

resources/install/scripts/app/fax/resources/scripts/hangup_rx.lua

1. Command should use only double quotes.
2. Application should not be quoted (I am not sure may be it is bug in FS `system` command).
So I use double quote on Windows and single quote on other system.
Also I quote strings only if they contain spaces.
To escape quote in string i just double it.
`you got "some text"` become to `you got ""some text"""`

Fix. hungup_rx.lua works on Windows

---

themes/enhanced/app_defaults.php
themes/enhanced/template.php

It is now possible to have the default setting to enable background
images (via theme > enable_background_images) but have a domain turn it
off again as they want to use gradients or specific images.
Upgrading any installation that already has any background_image enabled
will cause enable_background_images to turn on to let it continue to
work.
Including support code that the new install system will utilize ($set_session_theme), should
not affect existing systems.

Optimized control of background images

---

resources/install/scripts/fax_queue/exec.lua
resources/install/scripts/fax_queue/next.lua
resources/install/scripts/fax_queue/retry.lua
resources/install/scripts/fax_queue/tasks.lua
resources/install/scripts/resources/functions/esl.lua

It can be when originate has group dial-string. So it call `api_hangup_hook`
for each channel.
Now we release task in `retry.lua` only if originate success and this is same channel
which execute `exec.lua`.
If originate fail we release task in `next.lua`.
But we write log for each channel so we can have more log than expected.

Fix. problem when same session can release task multiple times.

---

resources/install/scripts/app/voicemail/resources/functions/send_email.lua
resources/install/scripts/resources/functions/send_mail.lua

Also add implementation based on [sendmail](https://github.com/moteus/lua-sendmail) library.
Fix. Send voicemail when set unknown language/dialect.
I add `T` function.
This function allows change
```Lua
text['label-attached'][default_language.."-"..default_dialect] or text['label-attached']['en-us']
```
to
```Lua
T'label-attached'
```
So I think one letter function is very convinient.
But if not I will change it to other name e.g. 
```Lua
i18n('label-attached')
```

Add. `send_mail` wrapper function to freeswitch.email and v_mailto.php.

---

secure/v_mailto.php

This needs for example if fax server could not create outgoing channel.

Fix. Make channel uuid optional in email.

---

resources/install/scripts/app/xml_handler/resources/scripts/dialplan/dialplan.lua

This pull requests fixes XML Handler support for 'date-time' time condition. With this, date-time gets rendered as:
```
<condition date-time="2015-12-15 15:00~2015-12-16 15:00">
```
Without this, the time condition WOULD get redered as:
```
<condition field="date-time" expression="2015-12-15 15:00~2015-12-16 15:00">
```
which is incorrect and would always match false in FreeSWITCH.
FreeSWITCH docs for this are here: https://freeswitch.org/confluence/display/FREESWITCH/Time+of+Day+and+Holiday+Routing#TimeofDayandHolidayRouting-Variables
All other time condition variables documented seem to be included in FusionPBX'es XML Handler.

XML Handler incorrectly handling 'date-time' time conditions

---

resources/classes/cache.php

Fix. Implicitly close esl connection after do cache command.

Change. Reuse same esl connection to send cache event and command.

---

app/ring_groups/ring_group_forward.php

this is so the user_dashboard consistently shows the ring group name (as
used elsewhere to refer to a ring group)

Updated ring_group_forward for user dashboard

---

app/provision/resources/classes/provision.php
resources/templates/provision/snom/320/{$mac}.xml

We wanted to populate the addressbook of our snom320 phones from the list of available extensions and found out, that the provided xml templates only provide an empty address book. Also, we didn't want to base the address book on the contacts. This commit adds another template variable internal_addressbook from the extensions table.
The snom320 template was modified to support the function keys (like the 7xx template) and populates the tbook array.

Allow provisioning with internal addressbook and update snom320 tpl

---

core/upgrade/index.php

only offer the source upgrade if it is writeable.
This check will prevent the source upgrade rendering if the .git folder is not writeable

Enhance-core/upgrade

---

.htaccess

Normalized and fixed htaccess
added comments explaining each rule
normalized tabbing
converted captures where not needed (note use of ?: means don't capture)
updated Yealink comment as it also covers Polycom
added missing $mac-directory.xml for Polycom
removed ^(?:.*/) as it is technically not needed, the test that showed it was needed turned out to be invalid

BugFix-Normalize .htaccess

---

app/conference_centers/app_config.php
app/conference_centers/resources/classes/conference_center.php

If a conference room had no admins it would become impossible to see it in the GUI
This fix makes it possible for a admin or super admin to view rooms in this state.
this uses a new permission "conference_room_view_all"

Fix for when a conference room has no admins

---

resources/templates/provision/yealink/w52p/{$mac}.cfg

account.1.subscribe_mwi should be set to '1' as per Yealink documentation. Not setting this may cause MWI to not work on the W52P.

Update W52P Provisioning Template

---

resources/install/scripts/resources/functions/database.lua
resources/install/scripts/resources/functions/database/luasql.lua
resources/install/scripts/resources/functions/database/odbc.lua
resources/install/scripts/resources/functions/database/odbcpool.lua

From [FreeSWITCH documentation](https://freeswitch.org/confluence/display/FREESWITCH/Lua+with+Database#LuawithDatabase-freeswitch.Dbh) 
> If you (optionally) return a **number other than 0** from the callback-function, you'll break the loop.
Problem that FS also breaks loop if callback returns string which contain number
```Lua
dbh:query(sql, function()
-- according doc it should not break loop
--  but it do in current implementation.
return "1"
end)
```

Fix. Break query loop accordin FS documentation

---

resources/install/scripts/email.lua

according to https://wiki.freeswitch.org/wiki/Mod_lua#freeswitch.email, it should be from, not to. This will prevent problems with hardened mail systems.

Wrong variable in freeswitch.email

---

resources/templates/engine/smarty/README
resources/templates/engine/smarty/debug.tpl
resources/templates/engine/smarty/sysplugins/smarty_internal_compile_include.php
resources/templates/engine/smarty/sysplugins/smarty_internal_templatelexer.php
resources/templates/engine/smarty/sysplugins/smarty_internal_templateparser.php

WhitespaceClean-resources/templates/smarty

---

resources/templates/provision/cisco/7940/SIP{$mac}.cnf
resources/templates/provision/cisco/7960/SIP{$mac}.cnf
resources/templates/provision/cisco/spa122/{$mac}.xml
resources/templates/provision/cisco/spa501g/{$mac}.xml

WhitespaceClean-resources/provision/cisco

---

app/dialplan/resources/classes/dialplan.php
app/dialplan/resources/switch/conf/dialplan/310_att_xfer.xml
app/dialplan/resources/switch/conf/dialplan/410_freeswitch_conference.xml
app/dialplan/resources/switch/conf/dialplan/430_directory.xml
app/dialplan_inbound/app_defaults.php

WhitespaceClean-app/dialplan

---

app/xml_cdr/v_xml_cdr_import.php
app/xml_cdr/xml_cdr_import_update.php
app/xml_cdr/xml_cdr_statistics_inc.php

WhitespaceClean-app/xml_cdr

---

app/sip_profiles/resources/xml/sip_profiles/default.xml
app/sip_profiles/resources/xml/sip_profiles/external-ipv6.xml
app/sip_profiles/resources/xml/sip_profiles/external.xml
app/sip_profiles/resources/xml/sip_profiles/internal-ipv6.xml
app/sip_profiles/resources/xml/sip_profiles/internal.xml

WhitespaceClean-app/sip_profiles

---

app/operator_panel/resources/functions/get_call_activity.php

Problem because if you have say 15 ext. and one of ext has say number `14`
and extension `14` has index 15 in array.
And php returns
```PHP
$a = array('14' => 'string', 14 => 'number');
print($a['14']); // number
``

Fix. Use operator panel with short extension.

---

resources/install/scripts/resources/functions/database.lua
resources/install/scripts/resources/functions/database/native.lua

To configure use `database.backend` option
It can be a string value like `database.backend = 'native'`.
So it will always use same backend.
Or it can be a table value like
```Lua
database.backend = {
main   = 'native';
base64 = 'luasql';
}
```
Role `database.backend.main` is predefined and it equal to `native` if not set.
If there no role when Database class creates or role unknown role `main` is used
```Lua
dbh = Database.new('system') -- uses role `main`
dbh = Database.new('system', 'main') -- same as previews
dbh = Database.new('system', 'base64') -- uses role `base64`
dbh = Database.new('system', 'test')   -- uses role `main`
```

Add. `role` to be able select database backend in constructor.

---

resources/install/scripts/app/xml_handler/resources/scripts/dialplan/dialplan.lua

If you use 'xml_locate dialplan' from fs_cli, you get an error, to prevent this I intialized call_context with the value of the "domain"-variable

initialize call_context

---

resources/app_languages.php

This is special case because all this names should be displayed
in same time on single page on different languages.
So not translate in strict way.
Before:
After:

Fix. Display language name on Install page.

---

resources/classes/menu.php

Problem now in `tepmplate.php`
```PHP
$menu_array = $menu->menu_array();
...
foreach ($menu_array as $index_main => $menu_parent) {
```
It appear while install process because in this moment there not `$db`
and `$menu->menu_array()` returns nothing.
I fix it like `$menu->menu_array()` always returns array.
This problem also can be solved in `tepmplate.php` like
```PHP
if(is_array($menu_array)){
foreach ($menu_array as $index_main => $menu_parent) {
...
```

Fix. warning about using NULL as first argument in `foreach`.

---

resources/classes/menu.php

On `themes/default/template.php` it called without args
```PHP
$menu_array = $menu->menu_array();
```
And it produce PHP warning.

Fix. Use default value in function definition.

---

app/extensions/extensions.php

Problem that
```SQL
select (select count(*) as num_rows ...)
```
is  not the same as
```SQL
select (select count(*) ...) as num_rows
```
I think problem may be on SQLite too.

Fix. Display extension on MySQL.

---

resources/functions.php

From PHP.net
```
Warning
This extension was deprecated in PHP 5.5.0, and it was removed in PHP 7.0.0.
Instead, the MySQLi or PDO_MySQL extension should be used.
...
Alternatives to this function include:
* mysqli_real_escape_string()
* PDO::quote()
```

Fix. use `mysqli_real_escape_string` instead or deprecated `mysql_real_escape_string`

---

core/install/resources/classes/install_fusionpbx.php
core/install/resources/page_parts/install_config_database.php

* MySQL/PgSQL ignore error while create new user because user may already exists.
* MySQL on database page use same checkbox like one for PgSQL
* MySQL/PgSQL if create user empty try use db user.(may be better use root/postgres without pass)
* PgSQL fix `GRANT ALL ON DATABASE dbname` instead of `GRANT ALL ON dbname`
* MySQL fix connect string build
* MySQL fix use correct password to connect
PS. This PR superseed #1520

Fix. Install with create new database for PgSQL/MySQL

---

resources/install/scripts/intercept.lua
resources/install/scripts/intercept_group.lua

Note.
* `inbound` is call to some extension
* `outbound` is call from some extension to external number.
Currently there no way to find call from extension to extension as `outbound`

Add. optional intercept only inbound/outbound calls.

---

secure/v_mailto.php

Allows users to create a function called get_transcription that they
can use to call any transcription service such as AT&T, Google,
iSpeech, etc and return just the translated text to be included in the
email.

Allow outside transcription service to be called

---

app/edit/filelist.php
app/edit/fileoptionslist.php

Problem when `opendir($dir)` returns `false` and then
while cycle adds many empty strings which produce in the end
```
/etc/freeswitch/tls
/etc/freeswitch/tls/
/etc/freeswitch/tls//
/etc/freeswitch/tls///
/etc/freeswitch/tls////
/etc/freeswitch/tls/////
/etc/freeswitch/tls//////
/etc/freeswitch/tls///////
```

Fix. Do not populate invalid paths.

---

resources/templates/conf/sip_profiles/external-ipv6.xml.noload
resources/templates/conf/sip_profiles/external.xml.noload
resources/templates/conf/sip_profiles/internal-ipv6.xml.noload
resources/templates/conf/sip_profiles/internal.xml.noload

you cannot actually set it to none, you have to not set it to get that
value.
made ipv6 profile tls settings consistent with ipv4 profile

Fix for [ERR] sofia_glue.c:329 Invalid tls-verify-policy value: none

---

resources/install/scripts/app/xml_handler/resources/scripts/configuration/callcenter.conf.lua
resources/switch.php

Problem that `mod_commands` may load after than `mod_callcenter` and there no function `global_getvar`
So current code just create database with name `INVALID COMMAND!.db`.

Fix. Use correct database for Call Center while FS load.

---

app/contacts/contact_phone_edit.php

The + prefix is being removed, this should be ignored for the very start of the string, resolution below.
Line 69.
Replace:
$phone_number = preg_replace('{\D}', '', $phone_number);
With:
$phone_number = preg_replace('{(?!^\+)[\D]}', '', $phone_number);

E.164 format support - contact_phone_edit.php

---

app/music_on_hold/app_defaults.php
app/music_on_hold/resources/classes/switch_music_on_hold.php
resources/templates/conf/autoload_configs/local_stream.conf.xml

Added basic searching for moh
added basic searching for the default moh directory
added app_defaults so moh is configured/repairable with app_defaults
changed to use PROJECT_ROOT
changed template replacement to be encased in comment so xml will
validate
changed to use preg_replace so leading spaces and tabs can be stripped
(to output clean xml)
local_stream_conf dos2unixed
made default search consistent (they should all be music/default or
music not a mixture)

BugFix-Default-MOH

---

app/music_on_hold/resources/classes/switch_music_on_hold.php

because app_defaults now deals with detecting the default music we don't
need to forcefully put it on the list
if default is detected name it using the $text['opt-default']

BugFix-Double default moh

---

app/xml_cdr/resources/classes/xml_cdr.php

I think to use some think like 
```PHP
if (permission_exists('number_alias') ) {
$sql .= "or (e.number_alias is not null and (caller_id_number = e.number_alias or destination_number = e.number_alias)) \n";
}
```
But not sure it correct way.

Fix. Display correct info for extensions with number-alias.

---

app/call_flows/call_flow_edit.php
resources/install/scripts/call_flow_subscribe.lua
resources/install/scripts/resources/functions/database.lua
resources/install/scripts/resources/functions/presence_in.lua

Usage:
1. Run form fs_cli `luarun call_flow_subscribe.lua`
2. Create new call flow extension and set feature code to `flow+<EXTENSION>`(e.g. `flow+401`).
3. Set on the phone BLF key to `flow+401`
This code based on `mod_valet_parking`.
Notes.
Because of prefix `flow+` in subscribe FS does not response by self to such subscribe with notify so it should not reset blf on phone. So old way with `call_flow_monitor.lua` script also should works except when phone turn on BLF lamp will not be in any state and will be turn off. This lamp will be set to appropriate state only when state of call flow will be changed or when `call_flow_monitor` send current state.
`call_flow_subscribe.lua` send call flow state each time FS receive SUBSCRIBE with `flow+`.
PS. There bug in Fusion. When you create …

Add. Handler for SUBSCRIBE method for call flow application.

---

resources/templates/provision/yealink/cp860/y000000000037.cfg
resources/templates/provision/yealink/cp860/{$mac}.cfg
resources/templates/provision/yealink/t21p/y000000000052.cfg
resources/templates/provision/yealink/t21p/{$mac}.cfg
resources/templates/provision/yealink/t23g/y000000000044.cfg
resources/templates/provision/yealink/t23g/{$mac}.cfg
resources/templates/provision/yealink/t23p/y000000000044.cfg
resources/templates/provision/yealink/t23p/{$mac}.cfg
resources/templates/provision/yealink/t27p/y000000000045.cfg
resources/templates/provision/yealink/t27p/{$mac}.cfg
resources/templates/provision/yealink/t29g/y000000000046.cfg
resources/templates/provision/yealink/t29g/{$mac}.cfg
resources/templates/provision/yealink/t41p/y000000000036.cfg
resources/templates/provision/yealink/t41p/{$mac}.cfg
resources/templates/provision/yealink/t42g/y000000000029.cfg
resources/templates/provision/yealink/t42g/{$mac}.cfg
resources/templates/provision/yealink/t46g/{$mac}.cfg
resources/templates/provision/yealink/t48g/y000000000035.cfg
resources/templates/provision/yealink/t48g/{$mac}.cfg
resources/templates/provision/yealink/t49g/y000000000051.cfg
resources/templates/provision/yealink/t49g/{$mac}.cfg

Fix the variable names to be consistent across all yealink provision
files. Also remove all the duplicate/redundant time settings from the
files.

Fix variable names and clean up duplicate time settings in yealink files

---

app/dialplan/dialplans.php

When clicking True/False link from the dialplan list (like outbound routes for example), the change isn't effective until the cache expires and leads to confusion.
Full editing the dialplan entry  via dialplan_detail_edit.php does this right and clears the cache, I took the code from there.

Clear memcache when toggling on/off dialplans

---

app/sip_status/sip_status.php

display '*@(Global)' for global gateways (instead of *@')

BugFix-Display global gateways name appropriately

---

resources/install/scripts/resources/functions/cache.lua

There 2 way.
First one generate `MEMCACHE` event without subclass
Second generate `CUSTOM` event with subclass e.g. `fusion::memcache`

Fix. Lua can not generate non CUSTOM event with subclass.

---

resources/install/scripts/app/voicemail/resources/functions/play_greeting.lua

This corrects the issue in #1760, where the default voicemail message was not being played and instead skipped directly to recording (start recording tone).

Add silence_stream to default voicemail message

---

resources/install/scripts/resources/functions/event_consumer.lua

It may be need if using Fusion `Services` app.
Then if there error in such service and `pid` file remain exists then there
no way to restart such service from Web UI.

Fix. Properly stop (e.g. remove pid file) event consumer loop in case of error

---

core/default_settings/app_defaults.php
resources/install/scripts/app/voicemail/resources/functions/send_email.lua
resources/install/scripts/app/voicemail/resources/templates/de/at/email_body.tpl
resources/install/scripts/app/voicemail/resources/templates/de/de/email_body.tpl
resources/install/scripts/app/voicemail/resources/templates/en/gb/email_body.tpl
resources/install/scripts/app/voicemail/resources/templates/en/us/email_body.tpl

* Renamed template variable account to voicemail_id and adjusted all templates
* Added ${voicemail_description}
* Added ${voicemail_name_formatted} (will render the voicemail identifier in accordance with  Default/Domain Settings > Voicemail > display_domain_name)
* Updated templates to be consistent spacing
* Updated templates to include use of ${voicemail_name_formatted}
* Changed ${account} to be voicemail_name_formatted instead of id

Enhance Voicemail Emails

---

resources/templates/conf/lang/en/ivr/wakeup.xml
resources/templates/conf/lang/en/wakeup/sounds.xml

The missing ".wav" extension makes Freeswitch looking for .PCMU file, which does not exist. The call hangs up without setting the wakeup.

Missing .wav file extension in wakeup.xml

---

resources/install/scripts/resources/functions/format_ringback.lua

add processing of when ringback is set to default_ringback and correctly
set it to the current value of the globalvar for ringback

BugFix-add missing default ringback to lua

---

secure/fax_to_email.php

This is a pull request to fix https://github.com/fusionpbx/fusionpbx/issues/1595
During fax2mail conversion, the dual tiff->pdf->tiff->pdf conversion for the libtiff color bug is not necessary as the incoming tiff files have no colors.
This saves on processing time and resources too.
The patch currently maintains the now unnecessary "tiffinfo" processing. This will be removed in a subsequent PR.
The patch is tested over a span of few days and about 100 faxes received and can be safely assumed to be working.

fix tiff2pdf conversion in short faxes

---

resources/install/scripts/app/voicemail/resources/scripts/mwi_subscribe.lua
resources/install/scripts/call_flow_subscribe.lua
resources/install/scripts/resources/startup/odbc_pool.lua
resources/install/scripts/service

This is more FS way. E.g. sofia sends `sofia::register` event
and add all information to headers. So now `service` script
emit `fusion::service::control` event and each service responsible
for test its own name. This also allows add in future evnets to
e.g. monitor service status like `fusion::service::satus` so it
will be possible write service which will be restart services.

Change. Use `service::control` event to control services

---

resources/classes/cache.php
resources/install/scripts/ha_monitor.lua
resources/install/scripts/resources/functions/cache.lua

Freeswitch 1.6 does not seem to recognize the MEMCACHE event. This commit changes the event to an event of type CUSTOM and also introduces a new script ha_monitor.lua that can also currently start and stop gateways across all servers.

Fixed scripts to get multiserver memcache working

---

app/time_conditions/time_condition_edit.php

This is a minor bug which is fixed with a few minor adjustments.
Valid values for 'minute-of-day' in FreeSWITCH are 1-1440, the page is currently converting 'time-of-day' to 'minute-of-day' as 0-1439, the fix will correct the values to 1-1440.
Sources:
https://wiki.freeswitch.org/wiki/Time_of_Day_Routing

Time of day routing convertion fixed.

---

app/time_conditions/time_condition_edit.php

When using 'time-of-day' it's not currently possible to specify a range which will finish at the end of the day.
This is a minor adjustment to allow a range which finishes at the end of the day 23:59 to be specified.

Update to time_condition_edit.php

---

app/vars/app_defaults.php

move ringtones to thier own category
import ringtones from vars.xml
by default if a vars.xml ringtone does not have the enabled attribute it will be imported as enabled
I have tested this on a existing debian 8.5 VM and it appears to work as expected, including importing and enabled states and descriptions should they appear.

Enhance-Import rintones from vars.xml

---

resources/templates/provision/polycom/5.x/{$mac}.cfg

I have been assigning a button on the Polycom VVX phones to allow users to access their voice mail from the phone easier that simply is a speed dial to *97 with a button label "My VoiceMail".  Why?  Because by default when a user presses the dedicated messages key (that has the picture of an envelope) the user is shown a screen titled "Messages".  There they press 1 or Select soft key to choose "Message Center".  Then a screen shows a summary count urgent, new and saved messages totals and the user can then press the Connect soft key to connect them to *97 to be prompted for their password.  This shortens up the process by 2 key presses and is more simple for the user.
I found an option to change the messages key so it does not display the summary and just dials the voice mail server …

Add one touch voice mail access to messages key

---

resources/install/scripts/app/xml_handler/resources/scripts/dialplan/dialplan.lua

In trying to write a dialplan I ran into some cases where the XML was not correct.  Since a dialplan condition statement could be in one of three states: (1) already output to XML opening a
<condition ...> block, (2) currently saved in var condition, or (3) one or more time conditions saved
in var condition_attribute, the main change is to check/handle all three possible cases at those
places where conditions are finalized.
If a dialplan group only consisted of a condition, then the output XML would become just
a </condition> entry without any opening <condition ...> entry.
If a time-based condition was following by a non time condition, the time condition would be
completely lost.
If a time-based condition, in a new dialplan group follows an action statement, the time condition
would get …

Corrects some cases where dialplan conditions were not fully handled

---

resources/install/scripts/app/call_block/index.lua

We've had instances where special characters (other than +) are used in the caller_id_number field which prevents these calls from being detected using the call_block feature. We've resolved this by updating fusionpbx/resources/install/scripts/app/call_block/index.lua line 49 to match only numbers rather than using a gsub replace.

Update call_block index.lua script

---

app/fax/resources/classes/fax.php

$fax_number variable is not defined, instead of this, it is safe to use ${destination_number}. Freeswitch will do the smart substitution.
The lack of this variable breaks the incoming rxfax command, as the complete path to store TIF files does not exist.

$fax_number variable is undefined

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

username is set to alias if it exists, otherwise it falls back to the extension value.
sofia_contact does not work with aliases. since we have the extension value already filled, it is safe to use it

use extension rather than username

---

resources/install/scripts/app/voicemail/resources/functions/macro.lua

Expected result: The person at extension XXX is unavailable ...
Actual result: The person at is unavailable... 
i.e. it doesn't say the extension number.
bug: trying to access local variable voicemail_greet_id outside it's scope...so it doesn't exist and you get this in the logs:
2016-09-18 12:32:54.615249 [ERR] switch_cpp.cpp:977 Error! invalid args. 
Fix moves local variable creation outside the inner "if" so it's available for the later table.insert

Update macro.lua to fix reading voicemail extension number

---

app/dialplan/resources/switch/conf/dialplan/999_local_extension.xml

This is for 4.0
When using balancing, and getting an INVITE from a peer PBX, the domain is lost and we get public context. This breaks the load balancing.
I have found that we need to export domain_name variable in order to let the LUA XML Handler to create the correct SQL query (which it uses the variable domain_name) to find where an endpoint is registered. This change is harmless for non-loadbalanced deployments.

export domain_name to fix load balancing

---

app/fax/fax_send.php
resources/functions.php

- Since $fax_name is modified the code didn't work properly, as the filenames didn't change.
The whole code works now fine, when renaming the attachment file to $fax_name.
- local email addresses where not valid, since the valid_email checker required a domain with 2-6 characters.

Fix e-mail attachment handling / conversion & allow local emails to be valid

---

resources/install/scripts/app/xml_handler/index.lua

When using load balancing, and a ring group is involved the domain_name, variable_domain_name, nor the sip_from_host are filled. Instead, there is a variable called variable_sip_from_host which it has the correct value.
This fix fixes this, avoiding a NIL in the domain_name variable, therefore domain_uuid empty

Look further for domain_name

---

app/fax/fax_emails.php
app/fax/fax_send.php

Added some changes from ICR regarding the text/plain emails, added a
uuid to the file name when getting saved to the FS in the event that
multiple emails come in with the same exact file name and also reset
the tif_files in fax_send as it was just adding to the end of the array
and creating bad tiffcp commands.

fix fax multiple files.

---

app/fax/fax_send.php

Prevents loss of message text when the message is longer than a single page.
Footer is placed afterwards, and has page break enabled.

[4.2] allow page-break on fax_message & fax_footer

---

app/call_centers/app_languages.php
app/click_to_call/app_languages.php
app/click_to_call/click_to_call.php
app/ring_groups/app_languages.php

Values obtained from [voip-info.org](http://www.voip-info.org/wiki/view/Asterisk+indications+Germany)
Hebrew translation is from Google Translate and therefore possibly wrong

Add German indications

---

app/fax/app_config.php
app/fax/app_defaults.php
app/fax/fax_log_view.php

app/fax/app_defaults.php:
+ fix: duplicate check only within same default_setting_category.  This fixes the bug where "keep_local" for fax wasn't being created because there was a "keep_local" for voicemail.  Without this fix you will get a lua error due to the field not being set and nothing shows up in the sent faxes log.
fax/fax_log_view.php:
+ fix: back button text is missing.  Copied correct localized text code from another fax page that worked.
app/fax/app_config.php
+ fix: date field is now timestamp for postgres+mysql.  This fixes the listing only showing the date, not the time as well.
Note: app->defaults doesn't change field types.  Existing installs will have to manually update the field type e.g. for postgres:
sudo -sHu postgres
\d fusionpbx
alter table v_fax_logs alter column …

#1987 combined fix for Master

---

app/fax/app_config.php
app/fax/app_defaults.php
app/fax/fax_log_view.php

app/fax/app_defaults.php:
+ fix: duplicate check only within same default_setting_category.  This fixes the bug where "keep_local" for fax wasn't being created because there was a "keep_local" for voicemail.  Without this fix you will get a lua error due to the field not being set and nothing shows up in the sent faxes log.
fax/fax_log_view.php:
+ fix: back button text is missing.  Copied correct localized text code from another fax page that worked.
app/fax/app_config.php
+ fix: date field is now timestamp for postgres+mysql.  This fixes the listing only showing the date, not the time as well.
Note: app->defaults doesn't change field types.  Existing installs will have to manually update the field type e.g. for postgres:
sudo -sHu postgres
\d fusionpbx
alter table v_fax_logs alter column …

#1987 combined fix for 4.2

---

resources/templates/provision/yealink/cp860/y000000000037.cfg
resources/templates/provision/yealink/t20p/y000000000007.cfg
resources/templates/provision/yealink/t21p/y000000000052.cfg
resources/templates/provision/yealink/t22p/y000000000005.cfg
resources/templates/provision/yealink/t23g/y000000000044.cfg
resources/templates/provision/yealink/t23p/y000000000044.cfg
resources/templates/provision/yealink/t26p/y000000000004.cfg
resources/templates/provision/yealink/t27p/y000000000045.cfg
resources/templates/provision/yealink/t28p/y000000000000.cfg
resources/templates/provision/yealink/t29g/y000000000046.cfg
resources/templates/provision/yealink/t32g/y000000000032.cfg
resources/templates/provision/yealink/t38g/y000000000038.cfg
resources/templates/provision/yealink/t40p/y000000000054.cfg
resources/templates/provision/yealink/t41p/y000000000036.cfg
resources/templates/provision/yealink/t42g/y000000000029.cfg
resources/templates/provision/yealink/t46g/y000000000028.cfg
resources/templates/provision/yealink/t48g/y000000000035.cfg
resources/templates/provision/yealink/t49g/y000000000051.cfg
resources/templates/provision/yealink/vp530/y000000000023.cfg
resources/templates/provision/yealink/w52p/y000000000025.cfg

In version 80 of the yealink firmware the trust_ctl changed from
account.X.sip_trust_ctrl=1  to sip.trust_ctrl=1. Making this change in
the provisioning files.

Update sip.trust_ctrl for yealink firmware version 80

---

resources/install/scripts/app/voicemail/index.lua

When saving Voicemail messages where the Caller ID number uses E-164 format these may include a '/' prefix used to escape '+'. This causes the '/' to be saved with the number which prevents the call from being returned.
The above fixes the issue by removing '/' prefix from the start of the Caller ID number before saving the Voicemail message.

Fix Voicemail for E-164 Caller ID

---

app/calls/resources/classes/call_forward.php
app/calls/resources/classes/follow_me.php
resources/install/scripts/app/xml_handler/resources/scripts/directory/action/reverse-auth-lookup.lua
resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua
resources/install/scripts/call_forward.lua
resources/switch.php

* About calculate presence_id.
If some extension make CF/Follow me to another extension then presence id for such cannel set to
number of new extension. (e.g. ext 101 make forwad to 102. then presence_is is 102).
If some extension make CF/Follow me to some external number then presence id for such cannel set to
number of origin extension. (e.g. ext 101 make forwad to +0123456. then presence_is is 101).
* `reverse-auth-lookup.lua`
We have to set number-alias here because if we make call with setted `fs_path`  and use number-alias for this then without this record FS can not find auth info.
* `directory.lua`
If ext has number alias then we should set info in memcache for both ext id and number alias in any case.

Add. Support number_alias field as presence id in follow me/call forward

---

resources/install/scripts/resources/functions/database.lua

This PR add 2 features.
1. Use `sql_escape` function to implementation `dbh:escape()` method.
2. Support basic parameterized queries.
It is not ideal solution because not sure that `sql_escape` is really secure when deal with e.g. multibyte strings. Need more tests. Also parameters substitutions implements in very primitive way. Just replace
strings like `:NAME` with values. But I think it may be sufficient to Fusion needs.
Also it may provide some common API so it should be easier improve it in the futer. E.g. if FS adds
parameterized queries to their DBH API.
So this code
```Lua
sql = "SELECT * FROM v_extensions WHERE domain_uuid = '" .. domain_uuid .. "' and (extension = '" .. user .. "' or number_alias = '" .. user .. "') and enabled = 'true' ";
dbh:query(sql, function(row) ....
``` …

Add. Extend database API to support parameters.

---

app/ring_groups/ring_group_delete.php

steps to test:
create a ring group with one extension and one user.  This will add one user to v_ring_group_users table.  Delete the ring group.
ring group and all it's components are deleted
actual result
v_ring_group_user entry for this ring group is not deleted.
This fix: deletes v_ring_group_user when ring group is deleted.

fix orphan v_ring_group_users after deleting ring group

---

app/ring_groups/ring_group_delete.php

Same as pr #2110 except for 4.2 branch
steps to test:
create a ring group with one extension and one user. This will add one user to v_ring_group_users table. Delete the ring group.
ring group and all it's components are deleted
actual result
v_ring_group_user entry for this ring group is not deleted.
This fix: deletes v_ring_group_user when ring group is deleted.

[4.2] fix orphan v_ring_group_users after deleting ring group

---

app/ring_groups/ring_group_edit.php

test case:
Create a new ring group with one extension.
Immediately dial the ring group number.
Phone rings.  No errors in log.
actual result:
Call terminates and log has "0" as ring_group_uuid and a sql error.
Note: editing and re-saving the ring group works around the problem
The Problem:
Line 162: non-existent variable...being checked is returned as false  = 0
Line 278: Xml gets generated with bogus zero...
Line 298: Generate a new uuid...but too late.  We already generated the xml dial plan which will be invalid until we edit and resave this ring group.
fix:
Generate uuid before generating xml

[master] fix bug #2017 ring groups broken until re-save

---

resources/install/scripts/app/ring_groups/resources/scripts/destination.lua

[destination.lua](https://github.com/fusionpbx/fusionpbx/blob/master/resources/install/scripts/app/ring_groups/resources/scripts/destination.lua) is equal to [ring_member.lua](https://github.com/fusionpbx/fusionpbx/blob/master/resources/install/scripts/app/ring_groups/resources/scripts/ring_member.lua). So I suggest remove one of them. not sure which one.

Add. Use params in ring_groups/destination.lua

---

app/backup/app_languages.php
app/backup/index.php

prerequisite:
- add at least one backup path to the Advanced->defaults
- do NOT install rar archive/de-archive programs
test case #1
- go to backup screen and download backups as rar
test case #2
- go to backup screen and upload a RAR file
- get a sign that an error occurs
actual result:
- not clear if it failed, or why
fix:
added error message.  And you will get the top-bar warning in red on error instead of in green.
note: cut-pasted from google translate for "extraction failed" part of message-restore_failed_extract
Thank you @markjcrane

additional error handling for backup/restore

---

app/voicemails/app_config.php
app/voicemails/app_languages.php
app/voicemails/voicemail_edit.php
resources/install/scripts/app/voicemail/index.lua
resources/install/scripts/app/voicemail/resources/functions/send_sms.lua

Requires that you have fusionpbx-apps/sms
Doesn’t impact anything if you don’t have it. Must be enabled with
default_setting voicemail_to_sms
Everything is disabled by default and the fields in voicemail_edit.php
are hidden by default.

Voicemail to sms notification

---

app/voicemails/resources/classes/voicemail.php

p.s. Thanks for feedback.  Separated out this fix.
bug: voicemail_id was never set so wrong path constructed and glob finds no matching files.
test case:
delete a voicemail message from the web interface
voicemail is deleted in the database + file system
actual results:
voicemail .wav file is still on the file system

fix: voicemail message delete bug #2100

---

resources/install/scripts/app/voicemail/index.lua

`true` and `false` string literals evaluates to `true` boolean value.

Fix. Set correct values for voicemail_to_sms_* settings

---

app/extensions/extension_edit.php

If as a superadmin you add recording to an extension, then the admin for the domain (ie member of group: admin) goes in and edits the extension, the recording property will be set to false.

Fix recording setting in extension

---

app/log_viewer/log_viewer.php

test:
- enable all errors
- go to log view page
- no notice message
actual result:
Notice: Undefined index: ln in /var/www/fusionpbx/app/log_viewer/log_viewer.php on line 48
Notice: Undefined index: ord in /var/www/fusionpbx/app/log_viewer/log_viewer.php on line 51
Notice: Undefined index: fs in /var/www/fusionpbx/app/log_viewer/log_viewer.php on line 54
Notice: Undefined index: a in /var/www/fusionpbx/app/log_viewer/log_viewer.php on line 57
Notice: Undefined index: filter in /var/www/fusionpbx/app/log_viewer/log_viewer.php on line 81
Notice: Undefined variable: byte_count in /var/www/fusionpbx/app/log_viewer/log_viewer.php on line 221
Notice: Use of undefined constant color - assumed 'color' in /var/www/fusionpbx/app/log_viewer/log_viewer.php on line 246
Notice: Use of …

Fix multiple notify warnings

---

resources/install/scripts/app/failure_handler/index.lua

This applies only when load balancing is on, this change is harmless when off. The SIP answer from peers contains the correct SIP error code, but the wrong Q code (when BUSY 486 or NO ANSWER 480, Q code will show NORMAL CLEARING). Freeswitch and this script, in particular, uses Q code which it is not always the correct.
This script takes the SIP error code and it evaluates as well in order to take the right call.
Please note that even this fix seems easy, it took a while before figuring out why it was not working.

Fix the call forward when BUSY or NOT ANSWER 4.0

---

app/provision/resources/classes/provision.php

Some PHP installations won't recognize such as $db_type as a global variable if is inside a class. Using the super variable $GLOBALS makes sure the global variables are reached.

Fix globals variable scope in 4.2

---

resources/install/scripts/fax_retry.lua

Please do further testing/review and give comments and suggest cleanup, etc.
This bug is only tripped if all of the following are true:
a) fax send fails
b) email notification of fax failure also fails
c) Other?
how to test
- have a 100% working fax to email setup.
- Change Advanced->defaults->email and set the port to be something invalid.
- e.g. smtp port 9999 is invalid
- send a test fax to something without a fax
- e.g. I just faxed my own DID which does NOT have fax answering
- each time the phone rings answer...wait 5 seconds, and then hang up
- note: it will retry sending the fax 5 times so repeat the above.
- on the last try it will give up, and try to send the failure email
- the email will fail (bad port) and then it will insert the failed email into v_emails
- the insert will …

fixes bug #2270 reported by volga629

---

app/exec/exec.php

test #1:
enter an invalid command for the shell.  e.g. "asdf" then click execute.
You get some type of result about invalid command.
Actual result: nothing shows up.  You have no idea if your command worked or not.
fixed result: When doing an exec include errors in the response: 2>&1
Test #2:
Enter something invalid in the switch command.  e.g. "asdf".  Click Execute.  Change to SQL.  Enter something valid e.g. "select * from v_users;"  Click execute.
Expected result:
You see the SQL output right below your "select * from v_users;" input text box.
Actual result:
Because the output from the previous switch/php/shell is not hidden the SQL output is pushed down off the screen.  Unless the user scrolls down they will not see the result and think their SQL command didn't …

show shell exec errors.  Nicer hide/show.

---

app/call_centers/call_center_queue_edit.php

Stops php warning message appearing when there are no assigned agents
(Warning: Invalid argument supplied for foreach() in /var/www/fusionpbx/app/call_centers/call_center_queue_edit.php on line 635)

Stop warning message appearing

---

resources/install/scripts/app/toll_allow/index.lua

There also some `interesting` destinations.
E.g. prefixes `79298 3-9` and `792981 0-2` is South Ossetia.
And codes like `7997445 0-6` may be very costly (I saw price up to 20$/min in some carriers).

Fix. Russia has 11 digits (close #2303)

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

Some Freeswitch deployments will create an empty core.db file (no tables inside) even when the core-db-dsn and core-recovery-db-dsn options are set. 
There is no reason to try looking for the core.db file when using balancing. The existence of an empty core.db file breaks the balancing.
This patch is totally safe, as line 141 only executes this code if balancing is on.

Fix a bug that breaks load balancing

---

app/devices/resources/classes/device.php
resources/install/scripts/app/event_notify/index.lua

Tested with Panasonic KX-TGP500 Firmware 22.90
User agent string `Panasonic_KX-TGP500B09/22.90 (<MAC>)`

Add. Support remote reboot Panasonic devices.

---

resources/templates/provision/yealink/cp860/y000000000037.cfg
resources/templates/provision/yealink/t20p/y000000000007.cfg
resources/templates/provision/yealink/t21p/y000000000052.cfg
resources/templates/provision/yealink/t22p/y000000000005.cfg
resources/templates/provision/yealink/t23g/y000000000044.cfg
resources/templates/provision/yealink/t23p/y000000000044.cfg
resources/templates/provision/yealink/t26p/y000000000004.cfg
resources/templates/provision/yealink/t27p/y000000000045.cfg
resources/templates/provision/yealink/t28p/y000000000000.cfg
resources/templates/provision/yealink/t29g/y000000000046.cfg
resources/templates/provision/yealink/t32g/y000000000032.cfg
resources/templates/provision/yealink/t38g/y000000000038.cfg
resources/templates/provision/yealink/t40p/y000000000054.cfg
resources/templates/provision/yealink/t41p/y000000000036.cfg
resources/templates/provision/yealink/t42g/y000000000029.cfg
resources/templates/provision/yealink/t46g/y000000000028.cfg
resources/templates/provision/yealink/t46s/y000000000066.cfg
resources/templates/provision/yealink/t48g/y000000000035.cfg
resources/templates/provision/yealink/t49g/y000000000051.cfg
resources/templates/provision/yealink/vp530/y000000000023.cfg
resources/templates/provision/yealink/w52p/y000000000025.cfg

Allows trusted certificate signing enforcement to be enabled or disabled via variable $trusted_cert_only.
If set to true, enforcement is enabled.
If set to false, enforcement is disabled.
If not set or any other value is entered, provisioning templates set nothing for this field.

Yealink Provisioning - Add Trusted Cert Variable

---

app/fax/fax_send.php

Apply the fix for multi-page faxes which is already commited in 4.2 to master.
References: #1978 & 687e02569d8605e5294dcf67e300e7175e39bb94
* enable page-breaks on fax messages
* fix footer & allow page break
* update footer placement to work properly on single page

allow page-break on fax_message & fax_footer

---

app/provision/resources/classes/provision.php

New Linux distributions are using PrivateTmp=true (systemd) which it is good from the security point of view but it creates a blank /tmp directory which it needs to create the directories to let this work. This patch just add a way to create the directory, if it already exist, it will be harmless

Make sure the provision temporal directory exists

---

core/user_settings/user_dashboard.php

On the user_dashboard clicking on the username brings you to a 404 page.
Fixed link path.

Fix user_dashboard broken user_edit link

---

app/extensions/extension_edit.php

Editing an extension causes the voicemail_description filed to disappear in v_voicemails.
* Preserves voicemail_description if present in v_voicemails table.
* Creates voicemail_description if empty in v_voicemails.

Fix disappearing voicemail_description.

---

resources/install/scripts/app/ring_groups/index.lua

I really don't know if this is an IP phone issue (tested on grandstream) or a new behavior on FreeSWITCH, but in order to add the prefix to the caller id (name or number) correctly, you need to export instead of set.

Fix CID alteration in Ringroups

---

app/scripts/resources/classes/scripts.php

At this moment, all LUA scripts must be at resources/install/script, this patch allows applications to be more self-contained by having app/*/resources/install/scripts directory, which it will be copied to the scripts_dir directory as well.
I would like to discuss the addition to this into 4.2.3

Let the apps be more self-contained regarding LUA scripts

---

themes/default/template.php

Fix for $mod_li and $mod_a_li not being blanked/reset foreach menu
parent item rendered, causing the first menu with sub items to force sub
item rendering for all remaining menu items

BugFix-[master]-sub item rendering

---

themes/default/template.php

Fix for $mod_li and $mod_a_li not being blanked/reset foreach menu
parent item rendered, causing the first menu with sub items to force sub
item rendering for all remaining menu items

BugFix-[4.2]-sub item rendering

---

resources/install/scripts/app/voicemail/index.lua

Bug fix in per user vm transcription. If domain had transcription enabled but the user did not, then the sql insert of the msg would fail.

Per User VM Transcription Bug

---

resources/templates/provision/grandstream/gxp2140/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml
resources/templates/provision/grandstream/ht702/{$mac}.xml

cis-scott found a bug with the handling of the expansion module programming (a typo from when I wrote the code); this pull fixes the two affected files: gxp2170/{$mac}.xml and gxp2140/{$mac}.xml.   call park type for expansion module should be code 16, not code 19.

Bug fix for two grandstream templates (Please backport to 4.2)

---

app/sip_profiles/sip_profile_edit.php

Fix. Add setting (seems need also set sip_profile_uuid)
Change. Order settings by name when output.

Fix. Redirect back to correct profile after delete setting.

---

app/conference_centers/conference_room_edit.php
app/conference_centers/conference_rooms.php
app/conferences/conference_edit.php
app/conferences_active/conference_interactive_inc.php
app/conferences_active/conferences_active_inc.php
resources/install/scripts/app/conference_center/index.lua
resources/install/scripts/app/conference_center/resources/scripts/start_recording.lua

Use '@' instead of '-' for separating conference name and domain, which
is what FreeSWITCH mod_conference uses.

Make presence for conferences work out of the box

---

resources/install/scripts/app/speed_dial/index.lua

One user can not use speed dial numbers from contacts
associated with another user

Add. Speed dial respects contacts user.

---

resources/install/scripts/resources/functions/database.lua

E.g. now it handle queries like
```Lua
local sql = "select :J::text as value"
print(dbh:first_value(sql, {J='hello'}))
```

Fix. Improve parameters patterns.

---

app/provision/index.php

Adds a variable http_auth_disable where when set true disables password authentication. If disabled or any other value is set, password authentication remains enabled.
Disabling password check currently necessary to set new autoprovisioning password on devices via autoprovisioning.
Better alternative may be to enable two passwords at the same time temporarily until all devices have been provisioned with the new password.

Add variable to disable autoprovisioning password

---

core/users/user_edit.php
resources/classes/messages.php
themes/default/css.php
themes/default/template.php

Support legacy $_SESSION['message_*']
Use new messages class
New function messages::add($message, $mood, $delay) to simplify adding messages
simplification of giving messages, allows multiple messages to be displayed with individual moods and delays

Enhance add message stack

---

app/call_centers/call_center_queue_edit.php

I did a bad copy and paste, reading $_POST where it was $row

Typo in the CC exit key patch

---

core/install/resources/classes/install_fusionpbx.php

Tested on CentOS v7 using MariaDB v5.5.52 and PHP v5.4.16
When reinstalling using the same superuser, install will fail due to incorrect MySQL syntax.  `SET` is used twice instead of once and separating the two commands with a `,`
After that correction the install is able to proceed to the next step which fails because `row['count']` does not exist and is actually `row['count(*)']`.  It will always match `==0` and incorrectly try execute the insertion of the duplicate `v_contact`.

Fix MySQL syntax

---

resources/classes/messages.php

because we are using javascript to populate the messages list we need to
make sure all special chars are escaped or line feeds will cause
problems

BugFix [master] - messages class escape more text automatically

---

resources/classes/menu.php

when a translation is missing/blank take it from en-us
take the list of lanaguages from text class so all languages get a value
(should fix missing logout button in some languages)

BugFix [master] - menu class

---

resources/classes/menu.php
resources/classes/text.php

when a translation is missing/blank take it from en-us
take the list of lanaguages from text class so all languages get a value
(should fix missing logout button in some languages)
add languages to text class as required by this patch

BugFix [4.2] - menu class

---

core/upgrade/app_languages.php
core/upgrade/index.php

convert message handling to use messages class
unify response display to reduce boilerplates
fix for when performing source upgrade with any other operation going wrong (required preservation of cwd)
add missing $text for default permissions
removed surpless $text provided by reources/app_languages.php
correct all br tags
formatting updates for messages class to make multiple messages render
with the same indent in source

Enhance [master] messages::add convert core/upgrade

---

core/apps/apps.php

Where application description is availible in the session language,
display it, if not fall back to en-us then &nbsp;

Enhance [master] - Display application descriptions in native

---

core/default_settings/default_settings.php
core/domain_settings/domain_settings.php

add to the sort order for default/domain settings so when a type is
array without *_setting_order the values will sort in order

Enhance [master] Default settings sort order

---

resources/switch.php

Prev version has bug when extension_dir has relative path (e.g. `ext`)
`basedir('ext')` returns not empty string by dot symbol `.` so it going to
infinity loop.
Also official distro of PHP has no executable binaries with version (phpX.exe)
only `php.exe`.
Tested on OpenServer with PHP 5.3-7.1 under Apache/Nginx.
And also on manual install of Nginx 1.11 / PHP 5.4

Fix. Find php interpreter when use CGI/FastCGI mode.

---

resources/install/scripts/app/xml_handler/resources/scripts/configuration/acl.conf.lua
resources/install/scripts/app/xml_handler/resources/scripts/configuration/callcenter.conf.lua
resources/install/scripts/app/xml_handler/resources/scripts/configuration/ivr.conf.lua
resources/install/scripts/app/xml_handler/resources/scripts/configuration/sofia.conf.lua

On my system mod_memcached returns `-ERR SOME ERRORS WERE REPORTED` when
memcached service not available. And sofia.conf.lua does not handle this case
and interpret this response as valid one.
Using `cache` class allows handle such errors. Also this class handle all
escaping operation which makes code more clear.

Fix. Properly handle error from memcached when load configs.

---

resources/classes/domains.php
resources/classes/menu.php

if a application is installed via a symlink PHP will resolve the symlink
for `__DIR__` and `__FILE__` making it impossible for an application to work
out it's relative path withing the fusion system.
By providing $app_path during upgrade routines an application will
beable to provide the correct link for menu items (e.g.
/opt/languages/index.php) instead of having to hard code it where it
could change depending on how the application was installed

Enhance [master] provide $app_path during upgrade

---

app/call_flows/call_flow_edit.php
resources/install/scripts/call_flow.lua
resources/install/scripts/call_flow_subscribe.lua

This PR allows create call flow extension with some feature code (e.g. `*401`)
Then on the phone you can configure BLF like `flow+*401` and use `call_flow_subscribe` to
track current status of this call flow. BLF like `*401` will also works but only if
use `call_flow_monitor` script.
Also it is possible dial `flow+*401` as well as `*401` to toggle call flow state.

Add. Allow use `call_flow_subscribe.lua` with feature codes without `flow+` prefix

---

app/number_translation/resources/classes/number_translation.php
resources/classes/database.php

if $database->app_uuid is not set it would use '' in some conditions which isset would test true.
This fix uses strlen instead, but also fixes number_transations app that highlighted the flaw

BugFix [master] - database class app_uuid

---

resources/classes/permissions.php

because application defaults is now captured for output these debug
lines show up when used. This removes them

[master] remove debug lines in permissions

---

resources/templates/provision/yealink/t21p/y000000000052.cfg

This is a security risk as other users can push redial and see the pin code

Hide pin codes when a user pushes the redial button

---

app/xml_cdr/app_config.php
app/xml_cdr/xml_cdr_statistics.php
app/xml_cdr/xml_cdr_statistics_inc.php

* Fix. Number of calls always calculate only for all domains.
Problem because `$sql_where` variable does not have domain specific condition
and when it used like `$stats[$i]['volume'] = get_call_volume_between($stats[$i]['start_epoch'], $stats[$i]['stop_epoch'], $sql_where);` then `get_call_volume_between` also does not add such condition.
So result has info for all domains. [source link](https://github.com/fusionpbx/fusionpbx/blob/a83d52eba6969475a9d59ddd6967db574f29e9ac/app/xml_cdr/xml_cdr_statistics_inc.php#L333)
* Fix. Number of missed calls ignores any search parameters and use only `inbound` filter.
Problem because if we use search parameters we have some conditions. But missed calls calculate as
```PHP
$where = "where domain_uuid = '".$_SESSION['domain_uuid']."' and "; // optional …
```

Update CDR Stats application.

---

app/xml_cdr/xml_cdr_inc.php

This argument used when build link in xml_cdr_statistics.php.

Add. Support `missed` argument in xml_cdr.php

---

resources/templates/provision/grandstream/gxp2130/{$mac}.xml
resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/gxp2140/{$mac}.xml
resources/templates/provision/grandstream/gxp2160/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml

Caller ID Display was not working for Attended Transfer.  Set "Caller ID Display" back to defaults "Auto" and Attended Transfer Caller ID Display works properly.   Thanks to matthewearl for hints on on #fusionpbx irc.

Fix Attended Transfer Caller ID Display

---

resources/templates/provision/snom/7xx/{$mac}.xml

the template uses the wrong parameter for sip registry expire, the
parameter user_subscription_expiry sets the expiry of subscriptions and
not the register (see
http://wiki.snom.com/Settings/user_subscription_expiry)
To set the register expiry one needs to use the user_expiry parameter
(see http://wiki.snom.com/Settings/user_expiry)

fix snom register_expire

---

resources/install/scripts/resources/functions/cache.lua
resources/install/scripts/resources/functions/file.lua

* `send_event` raise error so `Cache.del` did not remove key or send any event
* use `memcache` method by default even if `cache` table does not defined in config
* `Cache.get` did not return any data when use `memcache` method
* `Cache.get` did not close file. (Its should not be a big problem because GC should do it by self).
* `Cache.get` can returns some undefined global value. (if method is `file` and file not exists then method returns global `result` value)
* `Cache.get` does not need check for file existence
* Value escaping does not needed for `file` method
* Needed different key escaping for `memcache` and `file` methods
* Update self test

Fix. Cache class.

---

app/extensions/extension_edit.php

Set line display name to Effective Caller ID instead of extension #. Full directory name could be used too.

Set assigned device line display name

---

resources/install/scripts/app/voicemail/index.lua
resources/install/scripts/app/voicemail/resources/functions/change_password.lua
resources/install/scripts/app/voicemail/resources/functions/macro.lua

Adds the ability to check for password complexity and minimum length while changing your vm password through the phone. 
Also, fixes a bug where the password was changed if the caller hung up in the middle of changing their password.

VM Password Complexity through the Phone

---

.htaccess

convert tabs to fixed spacing so consistently displays in all editors
update polycoms to use anchor to provision to minimize rewrite looping
.htaccess's RewriteRule operates relative to it's dir so anchoring to ^provision is correct even for where fusion is on a sub folder

Enhance [master] - .htaccess

---

resources/install/scripts/app/voicemail/index.lua

This resolves issue #2333. On systems where 9 is used to make an external call we can use effective_caller_id_number in the inbound plan to modify the incoming CLI - for example to insert digit 9. This modified number is then passed to the extensions and the users handset's will store this modified CLI for redial and call history.
This pull request modifies the voicemail recording to use the effective_caller_id_number variable when available when saving voicemail messages, meaning that option 5 to return the call will work in the same manner. Without it, on a system that is using 9 for an outside line, the call back option in voicemail simply hangs up as it has stored the unmodified CLI for which there is no matching outbound dialplan.

Use effective_caller_id_number instead of caller_id_number when storing voicemail messages

---

core/users/usersupdate.php

Although the protections are already set, it has been forgotten to check the username existence in another tenant if unique is turned on. This will lead to an offending user to take control over another domain by renaming the username. This patch fixes this, it will verify the user even if unique is on.

Preventing the steal of user access

---

resources/install/scripts/app/conference_center/index.lua

Removal of the  ( ) in the sched_api cmd string allows the start_recording.lua to function as designed. 
Added "..scripts_dir.." as well.

Updated /scripts/app/conference_center/index.lua

---

resources/install/scripts/app/xml_handler/resources/scripts/configuration/ivr.conf.lua

when debug["xml_string"] is on, it will overwrite /tmp/ivr.conf.xml file each hit an ivr goes. this makes very hard to trouble shoot in a living system. this patch allows to put one ivr menu per file.

Update ivr.conf.lua for better debugging

---

resources/install/scripts/app/voicemail/resources/functions/advanced.lua

Fix "invalid greeting" message played on entry when pressing 5 for advanced, then 1 for record greeting.

Fix "invalid greeting" message played

---

resources/install/sql/switch.sql

255 characters is too small for phones with 15+ BLF lines. 
The phone will generate a postgres ERROR:  value too long for type character varying(255)

Change Column to allow for more characters

---

resources/install/scripts/app/voicemail/resources/functions/listen_to_recording.lua
resources/install/scripts/app/voicemail/resources/functions/menu_messages.lua

MWI was not turning off after messages were deleted for extensions that start with 0. This requires that real voicemail_id to be pulled from the database and not just taken from the destination number. To get around this we try to send mwi to the original vociemail_id (destination number) and voicemail_id_copy (from database). Index.lua is already doing something similar.

Fix MWI for Extensions that with 0

---

app/provision/index.php

Adding this fix enables both remote phone book and provisioning to work correctly on the newly released android based Yealink devices.
It appears that during the provisioning process, the T5X series supply a colon formatted mac address in their user agent.
However, when requesting a remote phone book, the presented user agent has no colons. This allows both formats to work as expected.

Update to provisioning engine

---

app/dialplans/resources/switch/conf/dialplan/230_group-intercept.xml
app/dialplans/resources/switch/conf/dialplan/290_intercept-ext.xml

In cluster installation first node search channel uuid
and send it inside special SIP header. So other node
can just use it and do not call Lua script again.

Small optimization with intercept.

---

app/dialplan_outbound/dialplan_outbound_add.php
app/dialplans/resources/classes/dialplan.php
app/dialplans/resources/switch/conf/dialplan/020_call_direction.xml

It is needed to use with b-leg filtering.
There exists some other places where fusion set call_direction.
Did not try figureout when they used

Fix. Export call direction to B-Leg.

---

resources/install/scripts/app/voicemail/resources/functions/record_message.lua

Bing is not perfect, when it fails it returns nothing, therefore name variable is nill.  This will fix it.

Fix a nil core dump when debug is on and bing fails

---

app/registrations/resources/classes/registrations.php

FS Always mark xml as ISO-8859-1, but pass info as-is.
So if user send its contact info as UTF-8 then we get
corrupted xml. But RFC describe text as UTF8
[RFC 3261 - 25.1 Basic Rules](https://tools.ietf.org/html/rfc3261#section-25.1)
```
qdtext = LWS / %x21 / %x23-5B / %x5D-7E / UTF8-NONASCII
```

Change. Treat `sofia xmlstatus` as UTF8

---

app/extensions/extension_edit.php

I am not very sure but seems that since last Chrome update, this select box stop working if there is no id property in the select tag.
Anyway, the old if statement is wrong, it is not comparing against $toll_allow and since we are using a foreach, it is cleaner using $name than the big session variable indexes

fix the toll_allow select

---

resources/templates/provision/polycom/3.x/{$mac}.cfg
resources/templates/provision/polycom/4.x/{$mac}.cfg
resources/templates/provision/polycom/5.x/{$mac}.cfg

This is backed up by...
1. phone boot log has errors when set to 0
2. documentation says valid values are 1-7, default being 1.

fix polycom error during bootup

---

app/system/system.php

Fix. Symbol '^' should be inside double quotes on Windows system.
Fetch may be not possible in some cases but git still be valid.
I test git status on repo with changes. And it also returns 0 as
return code.

Fix. Do not try `fetch` git repo when open system page.

---

app/xml_cdr/resources/classes/xml_cdr.php

This grabs a recording if started by bind_digit_action "*2" or by "nolocal:api_on_answer=uuid_record ${uuid} start ${recordings_dir}/${domain_name}/archive/${strftime(%Y)}/${strftime(%b)}/${strftime(%d)}/${uuid}.${record_ext}".

More ways of adding recordings to CDR's

---

app/dialplans/dialplan_xml.php

When in dialplan edit form press `XML` and then `Back`
Fusion build wrong URL like `&?app_uuid` so if then press
save server will do not get this arg and assign new random app_uuid.

Fix. Dialplan may loose its app_uuid

---

resources/install/scripts/app/ring_groups/index.lua
resources/install/scripts/resources/functions/route_to_bridge.lua

This commit has several improvements
1. Select only needed fields. (do not select quite big XML text strings)
2. Filter routes also by context name
3. Filter dialplans also by hostname
4. Handle conditions based not only `destination_number`
5. Handle `break` and `continue` attributes for extensions
6. Escape vars inside dial-string
7. Add log messages similar as FS dialplan do
8. Handle inline set/export actions
Also its fix bug when script may set 
```Lua
dial_string = "regex m:~"..destination_number.."~"..r.dialplan_detail_data
```

Add. Use `route_to_bridge` module to build routes for ring groups.

---

resources/install/scripts/app/ring_groups/resources/scripts/call_forward.lua

This is my dialplan. But it requires enter ring group number by hand. It is not big problem but not sure 
it is worth to add such dialplan to repo.
```XML
<context name="{v_context}">
<extension name="ring-group-call-forward" number="[ring_grop]*2,3,4" continue="false" app_uuid="ffe5bc1c-c3b0-43a3-a917-0690cdeec58f" enabled="false">
<condition field="destination_number" expression="^(500)\*[234]$">
<action application="set" data="ring_group_number=$1"/>
</condition>
<condition field="destination_number" expression="\*2$" break="on-true">
<action application="set" data="enabled=true"/>
<action application="lua" data="app/ring_groups/resources/scripts/call_forward.lua"/>
</condition>
<condition field="destination_number" expression="\*3$" break="on-true">
<action application="set" …
```

Add. Lua script to set call forward for ring group.

---

app/provision/index.php

Check whether loaded file is xml or not, if not xml than set Content-Type to text/plain

Rendering error of .cfg file in XML format

---

app/dialplans/resources/switch/conf/dialplan/500_call-forward.xml

It is consistent with enable/disable actions.

Fix. Do not request number when do call forward toggle.

---

resources/install/scripts/app/ring_groups/index.lua

After checking for Call Forward loops, set the destination_number to the call forward target.

Ring Group Member - Call Forward

---

resources/install/scripts/app/emergency_notify/index.lua
resources/install/scripts/app/emergency_notify/resources/templates/en/us/email_body.tpl
resources/install/scripts/app/emergency_notify/resources/templates/en/us/email_subject.tpl

A script for generating an email if an emergency call is placed. 
Instructions:
Simply add an action to your emergency outbound route. Make sure the order is a lower number than your bridge statement.
```
Tag: action
Type: lua
Data: app.lua emergency_notify [to_email_address] [from_email_address]
```

Emergency Notify lua script

---

app/provision/resources/classes/provision.php

This is a fix for a multi-tenant installation where you require domain specific provisioning templates. From what I can see the templating engine is initialised before the domain folder check, as such the templating engine ignores the domain folder. 
Comments welcome, FusionPBX (and pull requests for that matter) is new ground for me.

Fix provisioning templates ignoring domain specific templates

---

core/install/resources/classes/install_fusionpbx.php

Problem that `create_database_pgsql` does not create actual scheme
but `create_odbc_database_connection` try insert record to v_database and
installation fails.

Fix. Create database scheme before trying insert record to `v_database`

---

app/dialplans/resources/switch/conf/dialplan/370_tone_stream.xml

Just trying out fusionpbx and wondered why the tone_stream wasn't working.. now fixed (and listening to tetris)!

Fix tone_stream in default dialplan

---

resources/install/scripts/app/failure_handler/index.lua
resources/install/scripts/app/hangup/index.lua

change the failure_handler and hangup apps use
resources.functions.send_mail so they can use the correct smtp_from*
settings

BugFix - [master] - make hangup and failure use send_mail()

---

resources/templates/provision/yealink/t52s/y000000000074.cfg
resources/templates/provision/yealink/t54s/y000000000070.cfg

Merged in all variables from the Yealink T4x templates (specifically based off T46s) to ensure the T52s and T54s phones provision with similar settings to the T4x phones.
Notable changes include admin user login password is now correctly set, timezone settings are fixed and many other changes. No behaviors have been hardcoded/changed that don't already exist on T4x phones so should not break any existing configurations.
In addition, there are a ton of new variables that can be set in the Fusion GUI. All these new changes should probably also be backported to all the other Yealink templates as well, time permitting.

Yealink T52s/T54s: Add Variables from T4x Templates + New Ones

---

core/default_settings/default_setting_edit.php
core/default_settings/default_settings.php

update anchor names to use correct names, the mentioned commit changed the anchors over to use #anchor_{subcategory} from #{subcategory} but didn't correct all instances where anchors where called into the page
this commit broke it - https://github.com/fusionpbx/fusionpbx/commit/45bf2e5fd647200a02985819529dbb6fa0f84449

BugFix [master] - default_settings anchors

---

resources/install/scripts/resources/functions/route_to_bridge.lua

Problem was cause by query wrapper which do not reset counter before new call.
So preloaded dialplan can be use only once.
Can you please revert changes in ring group?
I have installation which depends on ability to set variables
via `user_data` in outbound dialplan,
My external routes has action like this
`export nolocal:param=${user_data(${caller_id_number}@${domain_name} var XXX)}`

Fix. Use preloaded dialplan more then once.

---

app/fax/fax_edit.php

Changed the type of fax_caller_id_number to text, because else leading 0 is removed.
In the database the 0 is/was still there.

Update fax_edit.php type change from 'number' to 'text'

---

resources/switch.php

if (stristr(PHP_OS, 'WIN')) isn't specific enough, it will be true for Darwin or MSWindows.

Update switch.php at Line 1282 detecting MSWindows

---

resources/install/scripts/app/event_notify/index.lua

Changed SIP NOTIFY Event header for Grandstream phones to allow provisioning with out requiring a reboot of the device. Based on communication with a Grandstream support rep. Tested on Grandstream GXP2130 and GXP2160 models.

Changed NOTIFY Event header for Grandstream phones

---

app/dialplans/dialplan_detail_edit.php
app/dialplans/dialplan_edit.php

Hello first time PR here in this project...
The idea behind this PR is to add the sip_h_Diversion header in the list of conditions for the dial plan editor.  A use case could be, for example, to detect that diversion header is present and then playback some kind of pre media such as "please wait while we connect your call" or what have you.

Adding sip_h_Diversion channel variable to list of conditions in dialplan editor.

---

resources/install/scripts/app/xml_handler/resources/scripts/directory/directory.lua

When updating from 4.2 to 4.4. Because there are new fields, some of them can return a NIL. this verifications prevents a LUA script failure

Prevent NILs for 4.4

---

app/dialplans/resources/switch/conf/dialplan/500_call-forward.xml
resources/install/scripts/call_forward.lua

Useful for softkey on hard phones, where the phone wants to sent *72xxxxxxxx.
Modification does not change original functionality of IVR set of forwarding on dialing *72.

Allow call forwarding to be enabled and set by argument in INVITE.

---

resources/install/scripts/resources/functions/mkdir.lua

This change reduces  the strain on the system by running the OS command through Freeswitch rather than directly from Lua. When running directly from Lua it causes RTP jitter in a high capacity system.

Use Freeswitch for mkdir

---

app/voicemails/voicemail_edit.php

As the other patches, the AS alias is not supported on MariaDB/MySQL and maybe other databases as well. You do not need an alias as you are just dealing with a single table.

Fix Voicemail DELETE FROM SQL Query [4.5]

---

app/voicemails/voicemail_edit.php

Same, the AS alias is not needed, it breaks MariaDB/MySQL and maybe other databases as well. Also, the SQL sentence is just dealing with one table, so it is not needed.

Fix Voicemail DELETE FROM SQL Sentence [4.4]

---

app/voicemails/voicemail_edit.php

MariaDB/MySQL (and maybe other databases) are not compatible with a DELETE FROM table AS alias. Anyway, you don't need the AS alias part as you are just dealing with a single table in this sentence.

Fix a DELETE FROM SQL Sentence for VoiceMails [4.2]

---

resources/templates/provision/grandstream/gxp2130/{$mac}.xml
resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/gxp2140/{$mac}.xml
resources/templates/provision/grandstream/gxp2160/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml

This prevents SIP anonymous calls, This should really be set as a default.

Disable anonymous (ghost calling) on Grandstreams 

---

app/ivr_menus/ivr_menu_edit.php
resources/templates/provision/yealink/t21p/{$mac}.cfg
resources/templates/provision/yealink/t23g/{$mac}.cfg
resources/templates/provision/yealink/t23p/{$mac}.cfg
resources/templates/provision/yealink/t26p/{$mac}.cfg
resources/templates/provision/yealink/t27g/{$mac}.cfg
resources/templates/provision/yealink/t27p/{$mac}.cfg
resources/templates/provision/yealink/t28p/{$mac}.cfg
resources/templates/provision/yealink/t29g/{$mac}.cfg
resources/templates/provision/yealink/t32g/{$mac}.cfg
resources/templates/provision/yealink/t38g/{$mac}.cfg
resources/templates/provision/yealink/t40g/{$mac}.cfg
resources/templates/provision/yealink/t40p/{$mac}.cfg
resources/templates/provision/yealink/t41p/{$mac}.cfg
resources/templates/provision/yealink/t41s/{$mac}.cfg
resources/templates/provision/yealink/t42g/{$mac}.cfg
resources/templates/provision/yealink/t42s/{$mac}.cfg
resources/templates/provision/yealink/t46g/{$mac}.cfg
resources/templates/provision/yealink/t46s/{$mac}.cfg
resources/templates/provision/yealink/t48g/{$mac}.cfg
resources/templates/provision/yealink/t48s/{$mac}.cfg
resources/templates/provision/yealink/t49g/{$mac}.cfg
resources/templates/provision/yealink/vp530/{$mac}.cfg

Some Yealink templates have hard-coded programmable key options in {$mac.cfg}.
A recent pull request was made to allow provisioning options to be configured on all phones through the  y000000000000.cfg files. This pull request resolves a conflict when configuring the programmable keys in the templates by simply removing the old hard-code options that exist in the {$mac.cfg} files for all devices.

 Fix Yealink Programmable Key Template Conflicts 

---

app/xml_cdr/resources/classes/xml_cdr.php

same as 4.2.
The caller ID number should see the extension that is doing the call, not the outbound caller id number assigned.

Same logic as v_xml_cdr_import.php

---

app/xml_cdr/resources/classes/xml_cdr.php

If you don't run the foreach, then when calling the CDR will report the Outbound caller ID instead of the caller id.

Use the same logic as the v_xml_cdr_import.php

---

resources/install/scripts/app/voicemail/resources/functions/record_message.lua

If bing returns status different than success, it won't have the indexes it needs. This patch adds the support to verify the success value and look for the correct JSON path. It also adds pcall to prevent an LUA script abort if JSON is not valid.

More BING Tolerance ERROR

---

resources/switch.php

if this is left in freeswitch (1.6.20) will not start up. 
Freeswitch: Cannot Initialize [[error near line 4105]: missing >]
there might still be a problem on line 1299 -> please correct me if I'm wrong.

removed double quote from $v_mailer_app path

---

app/dialplans/app_defaults.php

If 400+ domains exist it's not possible to Execute App Defaults without getting PHP out of memory error on line 630 in 'app\dialplan\resources\classes\dialplan.php'.
It would be better to first build XML for each domain_name (context) then for all else.

Fix PHP out of memory error on App Defaults

---

app/devices/device_edit.php

Similar to #3472 needed to allow up to 48 extension to be selectable and editable on the device_edit page.
Additionally, fixed sorting issue so line numbers are correctly sorted sequentially (line number is stored as text field so needed to change cast in SQL query).

Allow Editing 48 Lines on device_edit Page

---

app/provision/resources/classes/provision.php

"Warning: mkdir(): File exists in /var/www/fusionpbx/app/provision/resources/classes/provision.php on line 1405
When using tftp an error would be thrown when modifying extensions. This checks for the existence of the directory before creating.

Check for directory before trying to create

---

resources/templates/provision/cisco/7940/directory.xml
resources/templates/provision/cisco/7960/directory.xml

Generated Cisco 7940/7960 templates contained an error for the 'Enterprise' directory. The $mac variable was not expanded in the template engine.
http://$SOMEPBX/app/provision/?file=directory_enterprise.xml&mac=$mac}
{$mac} is now properly wrapped in the source template.

Fix cisco 7940/7960 directory.xml enterprise line

---

app/provision/resources/classes/provision.php
resources/templates/provision/grandstream/gxp2100/phonebook.xml
resources/templates/provision/grandstream/gxp2100/{$mac}.xml

Adds support for GXP2100 and properly provisions a GXP2100 using the last available firmware from grandstream. Successfully configures line and memory buttons along with additional grandstream options only available in later firmware.
Phonebook.xml relies upon the builtin Contacts APP user/group permissions and does not use the 'private function contact_grandstream' to generate the $contacts array. Instead this phonebook works with the current 4.4 $contacts array.

Setup Grandstream GXP2100 Template and Phonebook

---

resources/install/scripts/app/voicemail/resources/functions/record_message.lua

By setting a few variables, one can use any of a variety of self hosted speech to text APIs.
| Variable               | type    | value              |   |
|------------------------|---------|--------------------|---|
| transcribe_enabled     | boolean | true               |   |
| transcription_server   | text    | https://yourserver |   |
| transcription_provider | text    | selfhosted         |   |
| json_enabled | boolean    | true         | Optional  |
| api_key | text    | your_api_key         | Optional  |
One other thing I noted was it appears the particular Bing Speech API used doesn't have documentation that I can find, and Microsoft is deprecating the Bing Speech APIs in favor of their newer Speech Service API. The documentation of this deprecation is [lacking at …

Selfhosted Transcription Service

---

app/dialplans/resources/switch/conf/dialplan/330_vmain_user.xml

When re-recording the extension voice mail name the new recorded name is appended to the old recorded name file.  The new recorded name should replace the old recorded name.

Add record_append=false

---

resources/templates/provision/htek/uc903/{$mac}.cfg
resources/templates/provision/htek/uc923/{$mac}.cfg
resources/templates/provision/htek/uc924/{$mac}.cfg
resources/templates/provision/htek/uc926/{$mac}.cfg

Currently in the template, the server config prefix is set to http:// and should be set to https://

HTek Template Changes

---

app/call_centers/call_center_queue_edit.php

Sqlite used...
An error occurs when trying to add a queue:
Fatal error: Uncaught Error: Call to a member function execute() on boolean in /usr/local/www/fusionpbx/app/call_centers/call_center_queue_edit.php:398 Stack trace: #0 {main} thrown in /usr/local/www/fusionpbx/app/call_centers/call_center_queue_edit.php on line 398

Fix sqlite error

---

resources/templates/provision/grandstream/dp750/{$mac}.xml

New variables for the DP750 to allow the following settings:
$grandstream_repeater_mode_enable
(Enables or disables repeater mode on DP750 base)
$grandstream_hanging_group_mode
(Allows users to set hanging group mode (e.g. ring handsets at the same time, sequentially, etc.)
$grandstream_handset_X_line_Y_enable
(Allows setting of handset to line assignment)

Variables for DP750 Handset Assignment, Ring Type

---

app/provision/resources/classes/provision.php

Match Fanvil HTTP user-agent and map to template file

Add Fanvil one-hit provisioning support for X6 and i30 devices

---

app/dialplans/resources/switch/conf/dialplan/370_tone_stream.xml

`tone_stream://path=${conf_dir}/conf/tetris.ttm` should be `tone_stream://path=${conf_dir}/tetris.ttm`
There is no directory called "conf". Removing from xml path.

Update 370_tone_stream.xml for the tetris.ttm path

---

app/devices/device_edit.php

Chrome is no longer supporting autocomplete="off". The new standard for Chrome is autocomplete="new-password". This also seems to work for Firefox as well.

autocomplete="new-password" for devices

---

app/click_to_call/click_to_call.php

de-ring was not in the option list.
If multiple devices are registered with the same extension, only on device was ringing. (And this was not the device in front of you :) )
The Call UUID was 'duplicated'
The fix is to remove the origination_uuid. Then all devices rings simultaniously.

Bug option list and with multiple registrations.

---

app/xml_cdr/resources/classes/xml_cdr.php
app/xml_cdr/v_xml_cdr_import.php

Here's a fun little bug that took me a longer than it should have to figure out. When a person make a call and then cancels the request there is no "answer_stamp" written to the CDR. Because of this, v_call_recordings.call_recording_name gets imported as NULL. This causes all the canceled calls to show up in the Call Recordings app first in the list and with no date set.

Bug fix: No answer_stamp in CDR

---

app/xml_cdr/xml_cdr_details.php

Some databases, (mariadb, maybe others as well) save the json escaped "\{ prop: \"value\".......}"  this doesnt allow the json_decode function to work, therefore the details page is blank.
So if first attemp fails, then we strip the slashes (unescape).

[4.4] Fix the CDR Details

---

app/xml_cdr/resources/classes/xml_cdr.php
app/xml_cdr/v_xml_cdr_import.php

when you carry on some updates from 4.0 to 4.2 and then 4.4, old dialplans do not create all the variables, record_session is created, but record_name (and record_path) are not null, set and lenght zero,  "" in other words.
Then, in the db record, record_name and record_path are empty, regardless if the recording file exists. Therefore, they are not shown in the CDR app.
This fixes this issue.

[4.5] fixes null record_name and record_path fields in v_xml_cdr

---

app/fax/fax_emails.php

Foreign language html emails were sent as received.
Now all html entities should be converted to there corresponding UTF8 characters.

convert local html characters like &Uuml;

---

resources/classes/schema.php

when $apps[$x]['db'][$y]['fields'][$z]['name'] is an array, you dont try to get the ['text'] index therefore fields such as v_xml_cdr.xml_uuid, v_destinations.destination_type and v_destinations.destination_number wont be created when upgrading.
This patch fixes it

[4.5] Fix the ALTER TABLE

---

app/dialplans/dialplan_detail_edit.php
app/dialplans/dialplan_edit.php

I committed the change to allow using the diversion header as a condition field a year ago and didnt notice this typo.  I apologize!

fix sip_h_Diversion typo

---

resources/install/scripts/app/voicemail/resources/functions/record_message.lua

This patch adds BING (legacy) some extra fault tolerance support. For those who still use Bing, Bing sometimes fails
It adds another way, which I think it is easier and faster (Azure). Among the outstanding things it has; just configure the zone, and use Memcache to store the access token as per Azure documentation, it saves a query (faster). It also returns the most likely right transcription (digging in the JSON)

Add another working way to use Azure Speech to Text service

---

resources/install/scripts/app/call_block/index.lua

When setting call_block_matching, the setting was not being evaluated as true because it was looking for 'call block' group when the actual name is 'call_block'.
Adding the underscore fixes this small syntax issue and the setting works correctly.

Fix Call Block Type Setting Check

---

app/contacts/contacts.php

Added a default sort order that can be set by the session, if unset defaults to last_mod_date descending.  Added a secondary sort on contact_organization ascending.

Update contacts.php default sort order

---

app/scripts/resources/classes/scripts.php
resources/classes/config.php
resources/classes/database.php
resources/classes/domains.php
resources/pdo.php

This commit adds support for PostgreSQL TLS communication. This requires /etc/fusionpbx/config.php to have two parameters added:
$db_secure = true;
$db_cert_authority = "/path/to/ca.crt";

Add support for PostgreSQL TLS

---

app/phrases/phrase_edit.php
resources/install/scripts/streamfile.lua

With the current implementation, Phrases cannot be used in IVRs as streamfile.lua prevents keypresses from being passed back to the IVR. This fix makes a small change to the way phrases are stored and allows streamfile to be run without blocking IVR keypresses.

Allow Phrases to be used in IVRs

---

README.md

Since the websites SSL / TLS certificate does not include `fusionpbx.com` as a SAN the https links should point directly to `www.fusionpbx.com` since otherwise the browser will throw an error regarding an insecure connection. An alternative fix would be to get the non-www name into the SSL / TLS certificate.

Fix ocurrences of https://fusionpbx.com

---

resources/switch.php

when there is no local freeswitch running (big cluster deployments where Fusion UI is in another server), sometimes there is no local freeswitch running. this breaks the variables per host.
This patch gives the chance to use the hostname as a fallback option before giving up.

gives save_var_xml() more tolerance

---

resources/install/scripts/app/ring_groups/index.lua

This is going to sound really stupid but I have tested this extensively, submitted a Jira on it months ago (was told FS 1.6.20 was no longer supported) and it's still an issue. Please do not take my word for this and create a ring group to test the delay settings with a stopwatch and you should see the real vs set delay discrepancy.
In FreeSWITCH (both on 1.6.20 and 1.8.5) when sending leg_delay_start values, for whatever reason the actual time is double the value sent. The result of this is that if you send 1000ms as leg_delay_start the actual time the call will be delayed is 2000ms.
Because of this bad behavior, ring group delay settings end up being exactly double what is set. e.g. if you set 10s, you will have to wait 20s for the call to be initiated on leg b.
The easiest way to fix …

Fix Ring Group Delay Timing

---

resources/classes/database.php

Currently, the permission checks within the class try to singularize the table name, then check for permissions based on the result.  This PR modifies the private singular() function to support table names that end in "...ies", where an _add or _edit permission likely uses a 'y' instead.  An example would be where inserting records into v_event_categories, the class should probably look for an "event_category_add" permission, instead of "event_categorie_add".  Likewise for update queries.  
This proposed change isn't foolproof, obviously. In the case of inserting or updating records in a table named v_pies, it would fail to suffice.  You're welcome to integrate a better solution, if one exists.

Database Class Support for "...ies" Table Names

---

app/provision/resources/classes/provision.php

Make v_extensions.call_group available to the provisioning engine for templates that pull from v_extensions for contacts.

Make call_group available to provisioning

---

app/yealink/app_config.php

The duplicate uuid of ring_text_5 and _6 produces a lot of errors in postgres log file.
Also ring_text_6 is not available in the settings.

Duplicate uuid

---

app/xml_cdr/resources/classes/xml_cdr.php

Null UUID's are not very kind. They will sneak into your CDR's when you aren't looking and break an otherwise very nice database INSERT statement. We cannot tolerate that sort of behavior.

Check for null uuid's

---

resources/install/scripts/app/voicemail/resources/functions/send_email.lua

The percent sign (%) is a special character for gsub.

Filter out percent signs in transcriptions

---

app/dialplans/resources/switch/conf/dialplan/400_recordings.xml

Without this setting the recordings will append. It may depend on FS versions, but better to be explicit.

'record_append=false' for *732

---

app/calls/resources/classes/follow_me.php

In a case of FollowMe external number, sleep is not treated as a command, but just set as variable named 'sleep'. This fix explicitly set `sleep` in loopback inline dialplan.

FollowMe external number timeout fix

---

app/dialplans/resources/switch/conf/dialplan/500_follow-me-destinations.xml

I believe that call_timeout from the original destination should be unset, so that call_timeouts of the various follow-me destinations can work properly.

Unset Call_timeout

---

resources/install/scripts/app/follow_me/index.lua

Need to lookup the timeout values for the original destination. The variable "destination_number" is being clobbered later in the script.

Use original_destination_number for timeout

---

resources/install/scripts/app/ring_groups/index.lua

This is related to https://github.com/fusionpbx/fusionpbx/commit/9dcaddd81422bb46d940a2a3105112b30debcafa#diff-b1f5588538149bd825603176ff81d714.
For internal calls the delay needs to be "Delay In Seconds * 500".
For external calls the delay needs to be "Delay In Seconds * 10000". 
For external calls I'm am just doubling the value set prior in the script.

Fix delay for external follow-me calls

---

resources/install/scripts/app/ring_groups/index.lua

Need to calculate the timeout for Enterprise RG members that have extensions with follow-me. 
The RG timeout should always take precedence over a follow-me timeout value. What we do is take the delay of the follow-me destination and subtract that from the ring group timeout to give us the total timeout of the destination. 
Example: 
RG 1: x1000 (Delay=0, Timeout=10)
RG 2: x2000 (Delay=10, Timeout=10)
x2000 has follow-me enabled
FM 1: x2000 (Delay=0, Timeout=15)
FM 2: x3000 (Delay=5, Timeout=20)
In this example we would want x2000 ring for 10 seconds and x3000 to ring for 5 seconds. 
What if we changed this... FM 2: x3000 (Delay 15, Timeout=20)
In this example we wouldn't want x3000 to ring at all because it would start to ring after the RG timeout has expired. Our calculated value would …

Calculate timeout for Follow-me

---

app/xml_cdr/app_config.php

There was added a feature a while ago that removes outbound calls prefix on the CDR page, but people don't know about it because the setting was never added to the default settings

default setting to remove prefix on cdr page

---

app/fax/fax_edit.php

RFC's do not specify addresses must be converted lower case by email servers. If a sender has set their "from" address set to a mixed case string, the fax send will not match the authorized senders. This ensures newly entered authorized senders are now stored as lower case.

Match mixed case in "from" address

---

app/calls/resources/classes/follow_me.php

When the confirmation number is not a local extension (aka cellphone), you need to use enterprise in order to make the confirm to work, otherwise, it will answer right away (no prompt)
I think you have these already fixed in 4.5, I was reading you are using enterprise. I am not sure if you switch to the enterprise mode when you find an external number.

[4.4] Fix the confirmation

---

app/devices/app_config.php
app/devices/devices.php

This makes a permission change on the devices page to list only devices assigned to a particular user if they do not have device_all or device_domain_all permissions.
Note that device_domain_all is a new permission that has been added. The concept is that this permission could be assigned to admins which would allow them to see all devices on their particular domain, without having access to the "Show all" button.
To see how this works, assign device_view and device_edit permissions to a user-level user that has an extension assigned to them. They will now be able to see their assigned devices on the devices.php page and no other user's devices.

Devices Page - Show only Assigned Devices to User Level

---

app/registrations/resources/classes/registrations.php

1. Registrations XML from Freeswitch contains invalid characters '&gt' and '&lt' in the contact field; stripped. 
2. Registrations does not parse the Freeswitch 'Contact' field for a Yealink (or other) LAN IP address; added condition.

Registrations page: Parse for LAN IP in "Contact" field

---

resources/login.php

- sql query was using wrong column for user_email.
- there's no need anymore to join the v_contact_emails table as v_users has there own user_email column.

Fixed reset password

---

app/voicemails/app_config.php
app/voicemails/voicemail_edit.php
resources/install/scripts/app/voicemail/resources/functions/send_sms.lua

This SMS bugfix works out two issues:
* SMS permissions were not properly included. This causes SMS functionality to be inaccessible if the system implementor works out a Lua SMS implementation
* If voicemail transcription doesn't exist for the voicemail the send_sms.lua script crashes. Added a nil check to prevent this.

SMS bugfix

---

app/devices/app_config.php
app/devices/device_download.php
app/extensions/app_config.php
app/extensions/extension_download.php

Add new permissions extension_export and device_export which may be assigned under group manager. Default only allows superadmin.

Allow permission to export devices and extensions to be assigned to groups

---

app/dialplans/resources/switch/conf/dialplan/010_user_exists.xml

Leg B won't have the variable domain_name filled correctly, regardless if you do the right loopback/user/domain values.
however, the context variable is filled correctly. This will allow us to let all the dial plans run correctly.

Some Loopback endpoint support

---

app/xml_cdr/v_xml_cdr_import.php

When an inbound call has E.164 caller ID format (eg Skyetel), the + is being stripped from the caller_id_number variable before storing in the v_xml_cdr database table. If we then try and block this CDR in the Call Block application it adds the number BUT without the + so it never matches future calls.
This proposed change ensures that the + is not stripped for INBOUND calls when written to v_xml_cdr and therefore when blocking the CDR it works correctly (i.e. it includes the + which then matches the call next time and blocks it).

E.164 Inbound caller ID fix

---

themes/default/css.php

Adds ability to set the background to be a centered circular radial gradient
If the following is set: theme > background_radial_gradient > text
Then the radial gradient will be enabled. If not set, it will use linear gradient to preserve previous behavior.

Add Option for Background Radial Gradient

---

app/contacts/contact_edit.php
app/contacts/contacts.php

A user with only contact_view permissions is unable to click on the contact record to view the numbers and addresses etc.
By add allowing contact_view to have the contact_edit.php link they can now view the numbers etc.
Only showing the save button for users with contact_edit and contact_add permissions reinforces the fact that a user with contact_view only cannot edit the contact.

Allow user with only contact_view permission to click on contact record to view numbers etc.

---

app/calls/call_edit.php

This is fixed in 4.5 but not in 4.4. selected='selected' shouldn't be scaped in the <option> tag

[4.4] Cosmetic fix

---

app/scripts/resources/scripts/app/conference_center/index.lua

Right now settings a conference room's to 'sounds=false' doesn't do anything. This fixes that bug. 
Additional updates to the script most likely need to be made after this so that conference_enter_sound and conference_exit_sound honor the value specified in the conference profile. I didn't see any code referencing the conference profile values for sounds.

Setting a conference room sounds=false

---

resources/install/scripts/fax_retry.lua

sofia gateway has the dialled number in the fourth element, others such as lcr have it in the third which breaks the email title. This cosmetic fix allows you to fix that.

[4.4] Fix Fax Subject when not using sofia/gateway

---

app/xml_cdr/xml_cdr_inc.php

I had to add "c." in order for accountcode CDR searches to work under Advanced CDR Search. 
I suspect there may be more that require this, but I haven't checked every field under advanced search.

Specify table for Accountcode Search

---

app/dialplans/resources/switch/conf/dialplan/300_dx.xml

As per
https://freeswitch.org/confluence/display/FREESWITCH/mod_dptools%3A+read
And aligned to 310_att_xfer

[BUG] Change min/max digits in dx read application

---

app/scripts/resources/scripts/app/conference_center/index.lua

Conference Controls for moderators are hard coded. Because of this you cannot use the Conference Controls app in the web interface to create a new set of moderator controls and set them in the Conference Profile.

Remove hard coded setting for moderator conf ctls

---

app/conference_centers/conference_sessions.php

Page was downloading all audio files that caused not loading and timing out fixed by adding ```preload="none"``` attribute to audio tag

Fix conference_sessions.php page loading issue

---

app/scripts/resources/scripts/app/is_local/index.lua

line 111 emptied the  cache ```value``` variable that was set on line 51

Fix is_local 

---

app/scripts/resources/scripts/fax_retry.lua

Small change that attaches a pdf copy of the sent fax rather than the tif by replacing the extension in the file path.
PDF files are dramatically smaller and more user friendly than TIF files.

Attach PDF on Sent Fax Email Instead of TIF

---

resources/templates/provision/grandstream/gxp2160/{$mac}.xml

P2916 (wallpaper source) is defined twice in the file: once statically and then again immediately after in an if/else statement. The latter is correct. Having it defined twice causes the phone to ignore the second declaration.

Remove duplicate declaration of P2916

---

resources/switch.php

Change order of unset statement as it is after a return statement thus unreachable.

$sql and $parameters never unset

---

resources/templates/provision/polycom/4.x/{$mac}.cfg

added server address to address line instead of just the user id got issue when doing server1 server2 setup

Update {$mac}.cfg for plycom 4.x

---

resources/functions.php

N,X,Z syntax was always matched in destinations

Fix string_to_regex()

---

app/scripts/resources/scripts/app/xml_handler/resources/scripts/configuration/ivr.conf.lua

The IVR config didn't get set with the right name in the cache causing the XML handler to always query the database

Fix IVR Cache

---

app/devices/device_copy.php

Since the field is an integer, INT is a common type on Postgresql and MariaDB, Numeric is not (yet).
This fixes copy_device.php

[4.4] Use INT instead of NUMERIC

---

app/devices/device_profile_edit.php

The 'if' statements need to reference v_device_profile_keys.profile_key_vendor instead of device_key_vendor which is in a different table.

Fix Yealink Expansion Modules in Device Profiles

---

app/extensions/extension_edit.php

Add missing quotes surrounding extension_advanced permission so it is interpreted as text.

add missing quotes surrounding extension_advanced

---

app/scripts/resources/scripts/app/xml_handler/resources/scripts/configuration/sofia.conf.lua

* The SQL query queried the gateways for each domain causing each gateway being  numerous times in the XML 
* the SQL query that queries the domain_uuid  is not used

xml handler: fix duplicate gateways and unnecessary query

---

app/scripts/resources/scripts/app/follow_me/index.lua

``${domain_uuid}``  is needed in the dialplan for a few dialplans (example: call-limit is using it for the resource)

Follow me: set domain_uuid as a channel variable

---

app/scripts/resources/scripts/app/ring_groups/index.lua

``domain_uuid`` is needed in the dialplan for a few dialplans (example: call-limit is using it for the resource)

set domain_uuid variable

---

app/conference_centers/conference_sessions.php

The hardcoded path didn't allow to move conference recordings to a different path other than the default fixed by getting the recordings from the database

Conference recordings: remove hardcoded path

---

app/scripts/resources/scripts/app/ring_groups/index.lua

We only want to lookup the follow-me destinations for ring group members. If additional numbers are added to the destination array via follow-me lookup then we don't want to check for follow-me again on the new destinations. This can result in a lookup loop that will cause the call to not complete and throw lua into a loop that will fill up logs and burn system resources.

Fix for follow-me loops in Ring Groups

---

app/sip_profiles/sip_profiles.php

SIP profiles were unordered unless $_GET["order_by"] was set. Now if unset, it will order by sip_profile_name by default for nicer ordering.

Order SIP Profiles by Name by Default

---

app/scripts/resources/scripts/app/conference_center/index.lua

conference recording missing ext causes the recording not to show up on the conference session page was caused by commit https://github.com/fusionpbx/fusionpbx/commit/5b35a041d36d2d253bb64ea5134388fc259f8552

Conference recording missing ext

---

app/dialplans/resources/switch/conf/dialplan/050_user_record.xml
app/scripts/resources/scripts/app/ring_groups/index.lua

This is a feature for PCI compliance when taking credit card numbers or any personal information over a recorded phone call.
This allows the user to dial *5 before taking the personal information to play white noise instead of recording and then *6 after the information is taken to start recording the conversation again.
This solution is better than pausing and unpausing the recording because you can tell how long it took the user to gather the personal information. The recording is still in progress but white noise is being recorded instead of the conversation.
These changes allow recording masking/unmasking on inbound, outbound, and ring group calls.
1 bug is that if you dial a DID the outside party can mask/unmask but I think its a nonissue since its an obscure binding and the callee …

feature add mask/unmask recordings in real time. white space cleanup.

---

app/scripts/resources/scripts/app/agent_status/index.lua

Adds a bit of additional logic to allow the following variable to be set in dialplan:
agent_action
When set to login, this script will always log the agent in regardless of current state.
When set to logout, this script will always log the agent out regardless of current state.
When unset, original behavior is preserved.
The reason for adding this code is to allow us to create a dialplan that puts a user on DND at the same time as logging out the agent, and vice-versa.

Allow Variable to Manually set Agent Status

---

resources/templates/provision/snom/D120/{$mac}.xml
resources/templates/provision/snom/D315/{$mac}.xml
resources/templates/provision/snom/D345/{$mac}.xml
resources/templates/provision/snom/D375/{$mac}.xml
resources/templates/provision/snom/D385/{$mac}.xml
resources/templates/provision/snom/D712/{$mac}.xml
resources/templates/provision/snom/D715/{$mac}.xml
resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D725/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D745/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml

The most recent firmware adds a setting on how to handle BLF key presses while on a call, as well as options to display certain function keys while in various call states. I set some sensible defaults for those.

Updated snom templates to work with newer firmware

---

resources/templates/provision/polycom/4.x/{$mac}.cfg

I added variables to allow loading a root TLS certificate authority and time settings. The variables that have been added are the same as in the Polycom 5.x branch.

Add TLS settings to enable working with LetsEncrypt wildcard

---

app/ivr_menus/app_config.php
app/scripts/resources/scripts/app/xml_handler/resources/scripts/configuration/ivr.conf.lua

In one of our production systems we have IVR options that are three digits and we also have direct dial enabled. I do not believe this was a supported configuration to begin with but it operated okay until this commit 2e8f5d1f00a45d445f281fd47c0b412412aa130e. This merge request adds in the ability to change the direct dial digits regex from the default settings to allow more granular matching.
* Add a new default setting in ivr_menus called direct_dial_digits to allow changing the behavior of the direct dial IVR feature
* Modify ivr.conf.lua to attempt to load that setting, if the setting does not exist or is blank default back to the normal regex pattern for direct_dial

[4.5] Allow changing the direct dial digits regex for IVRs

---

app/scripts/resources/scripts/app/follow_me/index.lua

internal numbers were set to half of the time due to a FreeSWITCH bug but need to be set back for external numbers (ring groups was already fixed)

Fix follow me originate_delay for external numbers

---

app/scripts/resources/scripts/app/follow_me/index.lua

There are some cases where people want to use their internal extension caller id  when calling out to external numbers

Follow me add ability to use internal caller id when calling out to external numbers  

---

app/scripts/resources/scripts/fax_retry.lua

accountcode would only appear on the sip header for the 1st retry. Added the accountcode parameter to the rest of the originate commands to resolve this issue

Fix broken accountcode on fax retries

---

app/fax/fax_send.php

When faxing to multiple numbers the foreach loop  wasn't resetting the ```$dial_string``` variable for each loop causing the variable to concatenate the previous values causing the fax to fail

Fix faxing to multiple numbers

---

core/default_settings/default_setting_edit.php
core/domain_settings/domain_setting_edit.php
core/user_settings/user_setting_edit.php

the _setting_order was missing from the SELECT queries for all 3 places I could find that use this mechanism. The device settings don't seem to use it.

Fix displaying array order for settings of type array in multiple settings pages

---

app/scripts/resources/scripts/app/voicemail/resources/functions/send_email.lua

This was breaking when the variable wasn't set in the dialplan. 
Len discovered this :-)

Check for origination_callee_id_name

---

app/scripts/resources/scripts/app/voicemail/resources/functions/send_email.lua

To handle scenarios where transcribe_enabled is true BUT voicemail_transcription_enabled is not true for specific voicemail boxes. Need to be able to switch between the email templates.

Update send_email.lua to choose correct email template

---

app/fax/fax_send.php

Added additional command line switches to the Ghostscript command which greatly improves the output quality and legibility of converted faxes.
Now using a simple threshold method - 75% threshold to determine if a pixel will be black or white.
Dithering is turned off completely.
Also switched to newer tiffg4 compression method.

Optimize Fax Conversion Quality

---

app/scripts/resources/scripts/app/voicemail/resources/functions/send_email.lua

Ability to use ${new_messages} as a variable in the subject for voicemail to email template. Specifically useful for users who are migrating from asterisk and freepbx

Add new_messages variable in VM Email template

---

app/scripts/resources/scripts/app/voicemail/resources/functions/record_message.lua

Advanced --> Default Settings --> Voicemail.
Add: Category: voicemail
Subcategory: transcribe_provider
Type: text
Value: google
Enabled: true
Add: Category: voicemail
Subcategory: transcribe_enabled
Type: boolean
Value: true
Enabled: true
Add: Category: voicemail
Subcategory: json_enabled
Type: boolean
Value: true
Enabled: true
Add: Category: voicemail
Subcategory: transcribe_enabled
Type: boolean
Value: true
Enabled: true
Add: Category: voicemail
Subcategory: json_enabled
Type: boolean
Value: true
Enabled: true
Add: Category: voicemail
Subcategory: google_key
Type: text
Value: INSERT YOUR API KEY HERE
Enabled: true
Add: Category: voicemail
Subcategory: google_url
Type: text
Value: https://speech.googleapis.com/v1p1beta1/speech
Enabled: true

Updated code for v1p1beta1 API utilization

---

app/devices/device_edit.php

It appears that no group by default has the permissions device_line_outbound_proxy_primary/secondary or device_line_server_address_primary/secondary. They appear commented out for superadmin and admin in the app_config.php This causes any new lines/devices that are setup for provisioning to not respect the global outbound_proxy_primary/secondary and server_address_primary/secondary settings.
This change helps ensure that device configurations are not broken for some multi-tenant configurations where the domain isn't a real domain or isn't routed to the server. In this configuration the server_address always refers to the domain but the outbound proxy is set to the actual routable address.
This could be operating 100% as intended and I just need to always enable those permissions when …

Ensure new lines respect proxy and address default settings.

---

app/extensions/extension_edit.php

if the user_context is set to something other than the default domain_name users with edit permission were overriding the context to the default domain_name when saving extensions

Prevent users from overriding user_context

---

resources/functions.php

`urlencode()` encoded the `&` and `=` causing order by to fail when passing `$app_uuid` to `th_order_by()`

Fix order by on outbound routes

---

app/xml_cdr/xml_cdr_inc.php

when the $sql_* variables do not exist, sizeof() sends a warning

[4.4] Missing quotes and type verification

---

app/extensions/extensions.php

Extension searches would fail if an extension limit was set. This is because the `unset($parameters)` that was used at the end of the query that counts the extensions is also unsetting the "search" parameter that was set previously and needed later. I moved the `//get total extension count for domain` query to happen before the search parameter is added to fix it.

Fixed Issue with extension limits preventing Extension Search

---

app/dialplans/resources/switch/conf/dialplan/470_valet_park_in.xml
app/dialplans/resources/switch/conf/dialplan/475_valet_park_out.xml

BLF Presence support was not working with the valet parking dialplan since the parking lots were being created without the * in the parking lot name. This adds allowing park+5900-5999 to match the dialplan so we can use that to monitor the parking lot presence.
https://regex101.com/r/KBNVEj/2
- Switched the extension Regex to `^(?:(?:park\+\*?)|(?:\*))(5900)$` and `^(?:(?:park\+\*?)|(?:\*))(59[0-9][0-9])$` in `470_valet_park_in.xml` and `475_valet_park_out.xml` respectively.
- Update `475_valet_park_out.xml` to use $1 since the new Regex used non-capture groups now so the lot is in the first group.
- Fix some whitespace inconsistencies.
- I originally wanted to add the asterisk prefix in front of the parking lot names to match the default parking dialplan. However this does not work with …

Fix the valet auto-in parking dialplan to allow BLF presence monitoring.

---

app/ring_groups/ring_group_edit.php

Bring the ring_group_caller_id_name and number fields and permissions in line with the prefix permissions so that users without permission don't overwrite those fields by hitting save.

Prevent Users without permission from clobbering ring_group_caller_id

---

app/xml_cdr/xml_cdr_inc.php

In some cases, this seems to speed up xml_cdr loading times by ~10x.
It appears one big cause of this is the final ORDER_BY statements are very slow in PostgreSQL for timestamp fields. Ordering by start_epoch field improves query execution time in a dramatic way and should result in the same ordering.

Order by start_epoch to Speed Up Query Execution

---

resources/php.php

I saw this variable is stripped in 4.5, but I think it is used somewhere in 4.4.

[4.4] Deprecated syntax of JOIN

---

app/extensions/extension_edit.php

FreeSWITCH could be broken if you input a wrong CIDR value in the extension settings. This patch filters out any wrong CIDR notation. If you input 300.5.599.99,1.1.1.1/32,alb.sfie, the invalid parts will be filter out and only 1.1.1.1/32 will be saved.

[4.4] Filter wrong CIDR

---

app/destinations/app_config.php
app/destinations/app_languages.php
app/destinations/destination_edit.php
app/extensions/app_config.php
app/extensions/extension_edit.php

`v_destinations` has a new numeric column `destination_type_emergency` to be filled when a DID is validated to be used as a caller ID for emergency/E911 calls.
`destination_emergency` defaults to superadmin only
- adds a checkbox to the "Destinations" page that allows admins to mark a DID for use for emergency calls. Typically, when they have validated/configured the E911 emergency services with the carrier they will select this box.
`emergency_caller_id_select` no default
- changes the "Emergency Caller ID Number" and "Emergency Caller Name" to dropdown selectors, similar to the `outbound_caller_id_select` permission
- Different from the outbound select, it uses the `destination_type_emergency` selection from the Destinations to limit the options to only DIDs that the admin has validated …

Add Support for Validated Emergency Destinations/Caller ID

---

app/basic_operator_panel/index.php
app/basic_operator_panel/resources/content.php

Changing user status via the operator panel was broken due to an invalid permission and database update.
- Switch from checking `user_account_setting_edit` to `user_setting_edit` as the permission
- Change the database update to how it's updated in [/app/calls/resources/classes/do_not_disturb.php#L51]( https://github.com/fusionpbx/fusionpbx/blob/master/app/calls/resources/classes/do_not_disturb.php#L51)
- Add a `user_setting_edit` permissions check in content.php to only show the buttons if there is permission to change the status.
- Setting DND via the operator panel does not trigger the DND feature key sync found in the calls application.

Fix changing user status via the operator panel

---

app/calls/calls.php

As discussed in our phone call this seems like the better option then the weird dropdown interface for the calls application.
(My test server has a custom theme that's why it's green)
- Remove toggle select box and javascript
- Add individual buttons for each toggle type that sets the form action and then opens the confirmation modal
- Modify the confirmation modal to just submit the form when the user confirms the toggle

Remove the toggle dropdown in favor of three separate toggle buttons

---

app/extensions/extension_edit.php
app/voicemails/app_config.php
app/voicemails/voicemail_edit.php

When creating a new extension/voicemail box it can have a global/domain default setting for whether to enable transcription.
`transcription_enabled_default` boolean default setting that determines what status transcription should be for all new extensions/voicemails.

Allow Setting Default transcription state

---

core/users/user_edit.php

If someone without the api_key permissions modified a user, it would wipe out the api_key value.

Bug fix for api_key

---

app/call_centers/call_center_agent_dashboard.php

The footer was displaying inside the main content div causing the bottom of the page to look weird since the footer isn't in the same place as other pages.
- Remove the footer call in the call_center_agent_dashboard.php file.
- As far as I can tell this should never be needed in this file since the footer is added in the user_dashboard.php file.

Remove footer from call center dashboard widget.

---

app/scripts/resources/scripts/app/voicemail/resources/functions/record_message.lua

We found that callers were not hearing the tone_stream if they pressed "#" to bypass the voicemail greeting. Inserting a very brief silence_stream seems to fix the issue.

Bug Fix: No beep when bypassing the greeting

---

app/dialplans/resources/switch/conf/dialplan/080_default_caller_id.xml

By default custom caller ID names will get clobbered by this diaplan if no number is set. This is potentially problematic if you just want a custom caller ID name set for multiple extensions using the default caller ID number.
- Split up the two groups in this dialplan to check the name values and it they are empty set them with the defaults.

Do not clobber caller ID names if no number is set

---

app/scripts/resources/scripts/app/ring_groups/index.lua

ring group kept an open database connection for the duration of the bridge

ring group release database handle before bridge

---

app/scripts/resources/scripts/app/ring_groups/index.lua

Got broken yesterday after https://github.com/fusionpbx/fusionpbx/commit/a39a65d21ef89abd679b0e83a9b87f2df6a4a68a commit for releasing db handle before the bridge

Ring group fix missed call alert

---

resources/templates/provision/grandstream/gxp2170/{$mac}.xml

Added the following variables to support OpenVPN:
grandstream_openvpn_enable (P7050)
grandstream_openvpn_server (P7051)
grandstream_openvpn_port (P7052)
grandstream_openvpn_transport (P2912)
grandstream_openvpn_ca (P9902)
grandstream_openvpn_cert (P9903)
grandstream_openvpn_key (P9904)
grandstream_openvpn_cipher (P8396)
grandstream_openvpn_username (8394)
grandstream_openvpn_password (P8395)
grandstream_openvpn_options (P8460)

Added OpenVPN Variables

---

app/recordings/app_config.php

storage_type was never initialized as a setting in the database due to the y counter being reset to 0 after it. This was causing the storage_type setting to not show up in the UI.
- Replace `$y=0` with `$y++`

Fix app_config typo for recordings.

---

app/xml_cdr/xml_cdr_statistics.php
app/xml_cdr/xml_cdr_statistics_inc.php

Simple change to exclude lose_race and fix a URL change for the xml_cdr page.

Fixed "Missed" link and exclude LOSE_RACE from CDR stats

---

app/scripts/resources/scripts/app/voicemail/resources/functions/record_message.lua
app/xml_cdr/app_config.php
app/xml_cdr/resources/classes/xml_cdr.php
app/xml_cdr/v_xml_cdr_import.php
app/xml_cdr/xml_cdr.php
app/xml_cdr/xml_cdr_export.php
app/xml_cdr/xml_cdr_inc.php
app/xml_cdr/xml_cdr_statistics_inc.php

Purpose
----------
I have been getting clients wanting statistics on their calls and useful reports, but when we try to explain and validate the results of the CDR page and the CDR statistics page, I always come up short because the stats are just not accurate and broken in many ways. This is round 1 of improving this accuracy, making it more useful, and filtering out the remaining "chaff" that has no use except to clutter our views in the CDR and throw off missed call and volume statistics. I dug around with using external reporting tools, but 90% of the work is already there in fusionpbx.
Changes
-----------
- Improve CDR Import Logic so that missed_call column is more accurate to the "missed" status. It would previously mark unanswered outbound calls as "missed", but they can be be …

Improved Missed Call accuracy, cdr statistics, and hide duplicated CDRs from Enterprise Ring Groups

---

app/devices/device_imports.php

MAC addresses were not being normalized when importing CSV files. If it is not normalized you can get a not found error when provisioning since that is checking the database with a normalized MAC address
- Use the same normalization done in device_edit.php in device_imports.php

Fix device MAC address imports not normalizing.

---

app/call_centers/app_config.php
app/call_centers/app_languages.php
app/call_centers/call_center_queue_edit.php
app/call_centers/call_center_queues.php

This pull request is to add a field in Call Centers to manually specify the Time Score when entering the Call Center. I was requested by a customer that they wanted one Call Center to be prioritized over another.
I was able to do this by editing the XML in the dialplan however I did not like that solution since it would be hard to explain to all techs in our company.
Hopefully this pull request is ok with you guys. Let me know if you have any questions.

Adding Call Center Base Score Time in Seconds

---

app/xml_cdr/xml_cdr.php

I have been debugging slow loading on our CDR pages for the last few days now.
One issue that we have encountered is that currently as the page loads, it checks the filesystem for each file one at a time. In our case, we move recordings to object storage after 1 week, so each time we check for a file it passes api calls which take over 1 second each to return a result. This causes this page to not load at all for us in many cases.
Regardless, this current method is unnecessarily I/O intensive and really page load is probably not the time to be checking for each file one by one.
So this PR is the simplest solution - remove the check entirely. I would contend that the administrator should remove the record_path from the database if the file was removed so this should be acceptable.
This …

CDR - Don't Check Filesystem for Recording on Load

---

app/recordings/recording_edit.php

This is less of an improvement than the other changes I proposed since it's only doing it for one file. But it still doesn't need to pull that recordings base64 data here if it has it.
- Only select recording_name, recording_filename, recording_description as used by the code to prevent loading base64 data if present.

Update recording edit to not pull base64 data

---

app/music_on_hold/music_on_hold_edit.php

Currently if you are using base64 database backed recordings when you edit MOH all recording data will be pulled into memory. This will fix unnecessary memory usage/latency in this application when dealing with base64 recordings.
- Only select recording_name and recording_filename from the database

Do not load base64 data into MOH edit

---

app/recordings/resources/classes/switch_recordings.php

recording_base64 was pulled from the database and never used. Remove it to optimise base64 handling.
- Remove `recording_base64` from the select statement

Update switch_recordings.php to optimize base64 recordings

---

app/provision/resources/classes/provision.php

This will ensure that anyone using TFTP still can use array template variables. I am one of those unlucky ones that have to support a few devices that do not have HTTP provisioning.
- Apply changes from 906b86d3dc4c00ad53e2b93a52f854ab5b5d9b46
- Apply changes from 0b91af9f424cae593625dd133ca61d1a77e72b02

Update provision write() to match render()

---

app/devices/device_imports.php

If you bulk imported devices and had the TFTP path set the configuration files would not be written out to the TFTP path. This MR fixes it to trigger write() in this condition just like `device_edit.php` and other files.
- Trigger provision->write() if ['provision']['path']['text'] is set.

Fix bulk device imports with TFTP path enabled

---

app/scripts/resources/scripts/app/voicemail/resources/scripts/mwi.lua
app/scripts/resources/scripts/app/voicemail/resources/scripts/mwi_subscribe.lua

FusionPBX would continue replying to `MESSAGE_QUERY` events or send `MESSAGE_WAITING` events periodically even when voicemail boxes were disabled. This can also cause issues if you have another system responding to MESSAGE_QUERY events for the extensions that have their voicemail boxes disabled.
- For the main MWI notifier that just sends notifications every X seconds add an extra clause to check that `v.voicemail_enabled = 'true'`
- For the MWI subscription responder add the same check in the UUID lookup.
- Modify the logic and SQL to instead of embedding the uuid lookup SQL as a subquery to just use the value queried earlier.
- This is needed otherwise the `(SELECT COUNT(*) ...) AS ...` statements would return a valid row with zeros for even a disabled voicemail account causing the …

Only send MWI notifications for enabled voicemail boxes.

---

app/scripts/resources/scripts/do_not_disturb.lua

The follow me update code in do_not_disturb.lua was being executed even when the follow me uuid didn't exist. Let me know if this is the wrong approach to fix this in lua, I'm not particularly well versed in this but this seemed to have fixed it in my testing.
I have some concerns about this section of code in general though, it seems that enabling server side DND will turn off follow me, but then turning off DND won't return follow me to its original state. Is this the intended behavior? and if so we might need to make a workaround.

Fix follow_me_uuid error when enabling DND

---

app/calls/resources/classes/feature_event_notify.php
app/devices/cmd.php
app/devices/device_edit.php
app/scripts/resources/scripts/app/feature_event/index.lua
app/scripts/resources/scripts/app/feature_event/resources/functions/feature_event_notify.lua
app/scripts/resources/scripts/call_forward.lua
app/scripts/resources/scripts/do_not_disturb.lua

If you have multiple registrations that are also across SIP profiles the provision button under the `device_edit.php` page and the feature syncing will not work since it calls `sofia_contact` and only uses the first profile found. This causes the feature keys to not sync or devices to not re-provision in some cases.
- Modify `send_notify` in `feature_event_notify.php` to use `preg_match_all` to grab all of the profiles and loop the event sending for each unique profile.
- Move the profile code to `cmd.php` in the devices app and like what was completed in `feature_event_notify.php` loop over each unique profile and send the command.
- Also removes the newly unused code from `device_edit.php`
- Renames `get_profile` to `get_profiles` in `feature_event_notify.lua` which either returns nil …

Fix Device Provisioning and Feature Sync across SIP Profiles

---

core/domains/domains.php

Skip the step of clicking on the domain then clicking settings. I very rarely want to edit a domain's basic settings, 99% of the time I am wanting to either manage the domain or edit domain_settings.
There are a few other potential improvements to the "Settings" workflow that I'm tossing around:
- Rename "Default Settings" to "Domain Settings" and have it open the current domain's settings.
- The settings that are "custom" per domain would be highlighted, possibly with a filter to show which ones have been edited.
- A setting that is marked as "default" is still visible, but you can "Edit". The act of editing it will do the same as the current "copy" function, just in one transparent step. 
- If a user has permissions, there will be a separate "Edit Global Default" edit button for that …

Add "Settings" link to Domains list

---

app/scripts/resources/scripts/app/feature_event/resources/functions/feature_event_notify.lua

Add Delay to prevent infinite feature key Loops on some phones (Yealink....)
With some phones (easy to reproduce on Yealink) if a user toggles the DND too quickly it would create a loop where it kept turning DND off and on again repeatedly, often until you rebooted the phone. Even harder with multiple devices on the same extension.
This adds a short delay before firing the feature sync notification event and prevents the loop.

Fix DND Feature Sync loop

---

app/email_logs/email_test.php
resources/functions.php

The send_email function wasn't successfully parsing ; or , separated email address lists. I simplified it's processing and fixed it.
While I was at it I removed the "valid email" check from email_test.php because that step is already being done in the send_email function that is called and it safely returns the appropriate error. I would have had to rewrite that function to handle the multiple email lists otherwise.
This edit looks much larger than it actually is because I adjusted indentation on blocks of code that were moved out of an if statement.

fix send_email function for multi-part addresses

---

app/scripts/resources/scripts/app/fax/resources/scripts/queue/retry.lua

Zero should not be wrapped in double quotes as it's causing an SQL error.
PGRES_FATAL_ERROR
2021-03-11 10:30:47.738673 [ERR] switch_pgsql.c:680 Error executing query:
ERROR:  invalid input syntax for type numeric: "'0'"
LINE 1: ...p/c8505148-1b02-4f6f-9157-b5cf64ebcc4d.tif','','','''0''',''...
^

Small error in Fax Retry.lua

---

resources/templates/provision/grandstream/dp750/{$mac}.xml

Forcing incoming SIP from proxy only disables phantom call issues that will be present otherwise on UPnP style firewalls

Updated Allow Incoming

---

resources/templates/provision/grandstream/grp2615/{$mac}.xml

Set unregister on reboot to yes
Disabled DHCP Overrides 42 and 2, these options cause problems with the GRP2615 & DP752 time zone. Disabling these options should be good more often then not.
Added DND and Forward features in a way that will play nice with FusionPBX, as well as work well with the Grandstream Phone. The value of having them as IF statements, is the Features button becomes crowded with all accounts even if only 1 account is enabled.
May consider adding these to other GRP models.

Updated/Added Features

---

resources/templates/provision/yealink/t57w/y000000000097.cfg

missing newline causes smarty to combine `static.network.static_dns_enable` with the next line and breaking it

T57W fix static dns

---

app/dialplans/resources/switch/conf/dialplan/490_do-not-disturb.xml
app/scripts/resources/scripts/app/feature_event/resources/functions/feature_event_notify.lua

This is a dialplan approach to fix the feature key sync loop/race with yealink phones. This approach may also need to be extended to the Call Forward dialplans. It limits the number of simultaneous calls for a particular user to change their DND/Forwarding status to a single call at a time and returns user busy. The yealink phones will re-try their background feature key sync phone call several times and the call is very short it doesn't introduce any risk of the phones being "out of sync" with the server's DND status.
I am also reverting the lua approach because it was not reliable and can still easily allow the loop to occur.

Dialplan Fix for Feature Key Sync Race

---

app/fifo/fifo_add.php

In troubleshooting a known FreeSwitch bug with mod_callcenter, I started to try out mod_fifo as an alternative. I realized that the dialplan that was being created by Fusion was not working. Creating a queue is very simple so I knew it wasn't a user error on my part so I dug in deeper. There were a few issues in the dialplan generation that I needed to fix to get queues working again.
1. Add a "break on-true" to each condition destination_number (it was changed in two places)
2. populate the "action" for callers entering the queue via the $agent_queue_extension_number
3. remove the appended "_agent" which was added to the $queue_name which was causing the queue for entering and retrieving calls different.
4. remove the inline="true" for the action that executes the lua script
I also fixed …

Fixed Queues so they work and fixed the commented examples

---

app/registrations/resources/classes/registrations.php

Registrations make exception on got illegal character from sip phones
In iconv("utf-8", "utf-8//ignore" is not working, only like this:
iconv("utf-8", "utf-8//IGNORE"
in
app/registrations/resources/classes/registrations.php
Correct ignore to IGNORE in iconv paramter.

Registrations list is empty

---

app/dialplans/resources/classes/dialplan.php

When editing in the CLI with any editor that does syntax highlight, the * breaks it. Adding on the following line /* **/ restores the right highlighting

Fix CLI editors with faulty syntax highlining.

---

app/call_center_active/call_center_active_inc.php
app/call_centers/call_center_queue_edit.php
app/call_centers/cmd.php
app/call_centers/resources/classes/call_center.php
app/scripts/resources/scripts/app/xml_handler/resources/scripts/configuration/callcenter.conf.lua
app/xml_cdr/resources/classes/xml_cdr.php

* Freeswitch requires callcenter to have queue_name@domain for presence to work. this commit adds queuename@domain to be used for callcenter
* you can get a queues presence by subscribing to callcenter+queue_name@domain

[callcenter] Add ability for callcenter presence

---

app/scripts/resources/scripts/app/voicemail/resources/functions/mwi_notify.lua

Sometimes you can have multiple registrations for the same extension across multiple SIP profiles. This adds the functionality to fire an event for each unique SIP profile. I also added a check to see if we have already send an event for a profile since you don't want multiple events fired one SIP profile.

MWI for Multi Registrations on Multi Profiles

---

app/dialplans/resources/switch/conf/dialplan/470_valet_park_auto.xml
app/dialplans/resources/switch/conf/dialplan/470_valet_park_in.xml
app/dialplans/resources/switch/conf/dialplan/475_valet_park_out.xml

There were a couple of features of valet_park that were not exposed before by the default FusionPBX dialplan. This adds support for those features.
- If the Referred-By header is set call the normal `auto in` code. If it isn't set that means someone called it directly, call `auto out` and attempt to pop the calls in the lot in FIFO order.
- This also changes the parking lot name from `park` to `5900` this allows phones to monitor `park+5900` to get the status of the whole parking lot. Before you would have to monitor `park+park` to get this functionality.
- https://freeswitch.org/confluence/display/FREESWITCH/mod_valet_parking#mod_valet_parking-UsingPresence

Improve the valet_park_auto dialplan to support auto out and whole lot BLF monitoring

---

app/dialplans/resources/switch/conf/dialplan/470_valet_park.xml

This updates the main valet_park diaplan to match the changes done in #5606. This allows the diaplan to work with park+5901-5999 without the asterisk prefixed and fixes the lot names to match.
- Parking lots are no longer directly prefixed with *. But for backwards compatibility can be called that way still.
- Parking lot name changed from `park` to `5900` to allow monitoring the whole parking lot with a BLF if desired.
- https://freeswitch.org/confluence/display/FREESWITCH/mod_valet_parking#mod_valet_parking-UsingPresence
- Fix regex from matching 5900 to allow this dialplan to work with the valet_park_auto if enabled.

Update the valet park dialplan to allow matching park+5901-5999

---

app/basic_operator_panel/app_config.php
app/basic_operator_panel/resources/content.php

A quality of life improvement that allows extensions to be grouped by their group in the "ALL" view of the operator panel.
- Initialized the extension arrays at the beginning to eliminate the need for some is_array checks and prevent errors on size checks.
- If an extension has a call_group and the setting to show them as groups is enabled add them to the new $grouped_extensions array with the call group as the key and an array of extensions as the value.
- Add a new block to iterate over all $grouped_extensions and print out the group name and all of the extension blocks.
- Change the no extensions found check to take into account the new grouped extensions map.
- Add a setting to allow disabling this behavior if other users prefer the extensions to always be grouped up together in the …

Group extensions by call_group when viewing all groups in Operator Panel

---

app/scripts/resources/scripts/app/ring_groups/index.lua

the whole point of ring group presence is to monitor the ringing state If the call was bridged or went to timeout destination the presence should be set to terminated

[Ring Group] Improve presence

---

app/dialplans/resources/switch/conf/dialplan/470_valet_park.xml

when an outbound call is parked we need to set the `callee_id number` not the `caller_id_number`

[Valet Park] fix caller id for outbound call parks

---

app/dialplans/resources/switch/conf/dialplan/470_valet_park.xml
app/extensions/extension_edit.php
resources/functions.php
resources/templates/provision/grandstream/gxp2130/{$mac}.xml
resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/gxp2140/{$mac}.xml
resources/templates/provision/grandstream/gxp2160/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml

This is a new feature for grandstream, supporting dual simultaneous registrations. Only the very latest firmware 1.0.10.35 has it fully working, the last few versions had various partially working versions. This formats the username correctly when a secondary server is present.
There are more phone models that support this feature, but since it has been hit and miss on getting it going I am not going to enable it on those templates unless I have one of each to fully test because if the secondary server is added for a phone with an older firmware, the phone will not register to either server.

GXP21XX Dual Registration Support

---

resources/templates/provision/grandstream/ht802/{$mac}.xml

DNS Type wasn't being applied to the second line.

Fix HT802 Line 2 not setting SRV DNS

---

app/scripts/resources/scripts/app/voicemail/resources/functions/play_greeting.lua

This adds the ability to override any set greeting_id to use the default greeting

[voicemail] allow setting greeting_number_id to default

---

app/dialplans/resources/switch/conf/dialplan/470_valet_park.xml

If forwarding a call to park before the call is answered the call will get parked but will stay early media

[valet park] Add answer for calls that are still in early media

---

app/xml_cdr/resources/classes/xml_cdr.php

There has been some discussion of edge cases for CDR Importing time zones/time stamps.
This modification makes the start_stamp, answer_stamp, and end_stamp values use the corresponding _epoch times for import into the v_xml_cdr table.
This prevents scenarios where the DB's default time zone is set differently than the switch's timezone. 
I believe this is the most flexible solution because it doesn't require a new setting, it doesn't require reading the system timezone (which isn't always the same system for postgres and freeswitch) and it prevents all possible timezone offset mistakes when setting the timestamptz columns, regardless if the admin is using a default fusionpbx install or any altered/custom installation this will work for all of those scenarios because it uses an absolute …

Use epoch times for CDR Imports

---

resources/templates/provision/yealink/t46u/y000000000108.cfg

The variable for setting the wallpaper was set to T43U even though this is a T46U. This update is to fix that.

Updated the wallpapers variable to be for the T46U

---

resources/templates/provision/yealink/t33g/y000000000124.cfg
resources/templates/provision/yealink/t41s/y000000000068.cfg
resources/templates/provision/yealink/t42s/y000000000067.cfg
resources/templates/provision/yealink/t43u/y000000000107.cfg
resources/templates/provision/yealink/t46s/y000000000066.cfg
resources/templates/provision/yealink/t46u/y000000000108.cfg
resources/templates/provision/yealink/t48s/y000000000065.cfg
resources/templates/provision/yealink/t4x/y000000000065.cfg
resources/templates/provision/yealink/t4x/y000000000066.cfg
resources/templates/provision/yealink/t4x/y000000000067.cfg
resources/templates/provision/yealink/t4x/y000000000068.cfg
resources/templates/provision/yealink/t4x/y000000000107.cfg
resources/templates/provision/yealink/t4x/y000000000108.cfg
resources/templates/provision/yealink/t4x/y000000000109.cfg
resources/templates/provision/yealink/t4x/y000000000116.cfg
resources/templates/provision/yealink/vp59/y000000000091.cfg

Not all device templates supported the screensaver wait time variable. I edited them all to include the variable.

updated templates to include screensaver.wait_time

---

app/basic_operator_panel/index.php
app/call_center_active/call_center_active.php
app/conferences_active/conference_interactive.php
app/conferences_active/conferences_active.php
app/destinations/resources/classes/destinations.php
app/fifo_list/fifo_interactive.php
app/fifo_list/fifo_list.php
app/registrations/registration_reload.php

Responses to AJAX calls are now checked for a redirection to the login page and redirect the user to the login page if logged out.
This fixes an issue where fail2ban detects too many login tries when some users leave an "Operator Panel" tab open after logging out in an other tab. The "Operator Panel" tab keeps refreshing and requesting the login page.

Fix for ajax redirects when logged out

---

app/scripts/resources/scripts/app/conference_center/index.lua

* Remove these as they break HTML emails. 
* Remove quotes from Caller ID name and number. 
Same as following commits:
https://github.com/fusionpbx/fusionpbx/commit/29c1d52533fd95ce0b995122471b9b283962bc3f
https://github.com/fusionpbx/fusionpbx/commit/c93c20c4e10796e7b3e64c67565748e83f0a100c

Remove these as they break HTML emails.

---

resources/templates/provision/yealink/t40p/{$mac}.cfg

The t40p template was missing the rules for setting the transport type for the secondary server for dual registration.
Related note, A lot of the T4xG series phones don't support dual registration with fusionpbx. They have a secondary server address, but the update that fixed the context to allow the user@domain format for the user name was never released for most of those phones, and they are now end of support (no new firmwares). 
Can anyone see any reason to keep the server.2 options in the T4xG phone templates? It just causes issues because the phone will be sending bad registrations constantly to the secondary server since it doesn't know how to send them properly and could trigger fail2ban.

Yealink Dual Registration for T40P

---

app/dialplans/resources/switch/conf/dialplan/200_agent_status.xml

Taking the agent_id from sip_from_user doesn't allow tracking other agents

agent+ fix dialplan

---

app/scripts/resources/scripts/app/voicemail/resources/functions/listen_to_recording.lua

This useful for shared voicemail boxes and a voicemail is meant for someone else or a person doesn't want yet to mark the voicemail as saved

[voicemail] Add # option to go to next recording without saving the message

---

app/click_to_call/click_to_call.php
resources/functions.php

Click to call doesn't work if sip extension has - or . (which it is allowed by the naming rules).
Also, we have agreed in another PR discussion that detecting local extensions by the condition strlen < 7 is not an option. I have created user_exists() as a way to verify any extension regardless of its naming.

[4.4] Fix Click To Call

---

app/call_centers/call_center_agent_dashboard.php

The dashboard widget for call center agent self management was not working. It seems like it has been broken for some time and certainly stopped working when we switched the call center naming to <ext>@<domain> from <uuid>.
- Fix setting agent_status in the `call_center_agents` table
- Actually set the agent status in FreeSWITCH
- Fix the tier creation and deletion to match the new `<ext>@<domain>` call center naming format
- Fix an issue where $agent array access wouldn't work due to having a container array.
- Add support for On-Break
- This widget assumes each user is only associated to one agent. This could be restructured a bit to support multiple agents associated with a single user account if desired.

Fix dashboard widget for agent status management

---

resources/templates/provision/grandstream/gswave/{$mac}.xml

I fixed the voicemail access number (this was hard coded to *98)
Removed unsupported P values and added many hidden values that cannot be configured on the app but are present in the default app config file
TLS support (you can now easily toggle TLS using default settings)
Added grandstream_config_server_path, http_auth_username/password (useful if you want to point to another PBX)
And many other fixes/improvements

Fixes, also can now provision all 6 accounts

---

app/scripts/resources/scripts/app/ring_groups/index.lua

ring_group_distinctive_ring is always an empty string

ring group lua minor improvement

---

app/calls/call_edit.php
app/calls/resources/classes/call_forward.php
app/calls/resources/classes/do_not_disturb.php
app/calls/resources/classes/follow_me.php
app/scripts/resources/scripts/app/xml_handler/resources/scripts/directory/directory.lua

Until now, the behavior nulled the dial string every time a save was made on the call forward page that didn't allow for custom dial strings that can be useful in some cases.
The only place fusionpbx uses the dial string is for DND, which can be set in the XML handler.

[Extension] Don't null dial_string when enable/disable follow me or dnd

---

secure/v_mailto.php

at line 269 if this is set to ZERO all emails are bcc. this causes problems for normal recipients and scripts that depend on a TO field existing.
Setting to 1 will have it be a normal to: if its 1 email address and if its more than 1 it will do the BCC steps.

update to fix array count of emails to determine if normal to: or bcc:

---

app/call_centers/call_center_queue_edit.php

The announce sound previously required users to manually type in the full path of the announce sound. It has now been modified to be a hybrid dropdown which shows available recordings on the domain and also allows for the old text entry method (type in the path).

Add announce sound dropdown selection

---

app/devices/device_edit.php

This change adds support for images of the current selected device on the device_edit.php page.
The images need to be stored with the provisioning templates in the following format:
* /yealink/t21p/t21p.jpg
Images loaded into the page without needing link to the direct path. This makes it possible to store images with the template and not need any form of nginx rewrite rule or any other changes.
The images are zoomable with pure CSS, no javascript required.

Add device image support from provisioning templates

---

resources/templates/provision/grandstream/grp2612/{$mac}.xml

Allows the active mpk page to be disabled on expansion modules

Add grandstream_disable_active_mpk_page variable

---

app/snom/app_config.php

This commit adds some snom-variables that are already used in the templates.
See https://github.com/fusionpbx/fusionpbx/blob/d7cc26a51df7dae1e464dc883d3ac61788a6826b/resources/templates/provision/snom/D745/%7B%24mac%7D.xml#L6-L8

Add some snom-variables that are already used in the templates.

---

app/dialplans/resources/switch/conf/dialplan/085_bind_digit_action.xml

Using ${sip_authorized} is not effective since the inbound
call often has authorization to call into the PBX, either via
ACL or registration.  Instead, use ${from_user_exists} to test
if this user exists on the system.
We also fix a condition that the local user types *1 and the
remote user receives the dial tone.

Fix permissions on inband feature codes

---

app/scripts/resources/scripts/directory.lua

The database contains directory_first_name entries that are blank, and the
table does not populate properly.  Use effective_caller_id_name when a
nil or blank entry is found.

[directory] Use effective_caller_id_name when directory_first_name blank

---

app/snom/app_config.php

The old timezone URL is no longer valid. I've updated the default description with the new correct URL.

updated the snom timezone description

---

app/dialplans/resources/switch/conf/dialplan/085_bind_digit_action.xml
app/scripts/resources/scripts/bind_digit_bleg.lua

The existing code only binds properly when one leg
is not internal.  Here we use LUA to bind the bleg
for internal calls.

bind_digit_action for B-leg during internal call

---

app/scripts/resources/scripts/resources/functions/send_mail.lua

`freeswitch.email` returns a boolaen

[send_mail] return freeswitch.email Boolean value

---

resources/templates/provision/snom/D785/{$mac}.xml

The reason I think this should be removed is because setting the label on this model of phone removes the ability to see status of the line button.
For example (without the label), if I have a call on hold on my first line button, it will show the caller's number and the state of that call. For example: "4165551234 holding"
When you put the label, it removes that great feature. When the label is left blank, it defaults to "Line".
<details>
<summary>Click to view image</summary>
</details>
<details>
<summary>Click to view image</summary>
</details>

Removing {$row.display_name} from the line button

---

resources/templates/provision/grandstream/dp750/{$mac}.xml
resources/templates/provision/grandstream/gxp2130/{$mac}.xml
resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/gxp2140/{$mac}.xml
resources/templates/provision/grandstream/gxp2160/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml
resources/templates/provision/grandstream/gxw42xx/{$mac}.xml
resources/templates/provision/polycom/4.x/{$mac}.cfg
resources/templates/provision/yealink/t46s/y000000000066.cfg

Hello Mark,
Per our call I have modified 9 templates, adding the following things:
**Grandstream**
- Fixed grandstream_lan_port_vlan
- Backported grandstream_dhcp_option_override and grandstream_phonebook_download and grandstream_phonebook_download_interval
- Added grandstream_key_mode (Key Mode. 1 - Line Mode, 2 - Account Mode. Default is 1)
- Added grandstream_dhcp_option_2_timezone_override (When set to Yes(1), it will override the configured Time Zone setting if available)
- Added grandstream_jitter_adapt
- Added xmlappurl and xmlapp ([Grandstream thread](https://forums.grandstream.com/t/writing-an-xml-application/15888/6))
**Yealink**
- Backported voicemail_number
- Added yealink_headset_ringer (Configures the ringer device for the IP phone, 0-Use Speaker, 1-Use Headset, 2-Use …

Provisioning Template Updates for Grandstream GXP2130+, Yealink T46S & Polycom 4.x

---

resources/templates/provision/yealink/t46u/y000000000108.cfg

The expansion module can use a different background image
The wallpaper_upload.url setting in yealink can be used multiple times to download multiple images.
setup for 2 more variable:
$yealink_t46u_wallpaper_expansion
and 
$yealink_t46u_wallpaper_expansion_filename
This is only a template update. I did not push any additional varaibles up into the default settings.

Update yealink t46u to add variables for expansion module background

---

resources/templates/provision/snom/D375/{$mac}.xml
resources/templates/provision/snom/D385/{$mac}.xml
resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml

This PR includes new settings for both the snom wallpaper on the main screen as well as the expansion module. Snom documentation states that if the option is left blank then the default will be used. I tested this on my lab system and when the variable exists it shows up in the template like this:
> `<custom_bg_image_url perm="">https://imgur.com/fakeimage.png</custom_bg_image_url>`
When the variable is blank or not set it looks like this:
> `<custom_bg_image_url perm=""/>`

Wallpaper setting added to provisioning template

---

resources/functions.php

The current validation regex didn't conform with RFC 5322, but PHP `filter_var` does.
More information can be found at https://en.wikipedia.org/wiki/Email_address#Local_part
I also removed the unused function `email_validate`

[email validation] improve validation to conform the RFC

---

app/xml_cdr/app_config.php
app/xml_cdr/resources/classes/xml_cdr.php
app/xml_cdr/xml_cdr_extension_summary.php

Add new permission xml_cdr_extension_summary_all. Reason is many extensions and CDR records make this a  very resource intensive query use with caution and only on smaller system.  Disabled by default for all groups.

Hide Extension Summary Show all by default.

---

resources/templates/provision/yealink/t31g/y000000000123.cfg

Looks like a combined boot file and a config, minor template issue. Stops the Yealink t31g from provisioning.

Removing invalid lines in Yealink t31g template, appears to be a dodgy concatenation

---

resources/functions.php

When an old server has been upgrading fusion, it gets to the combination of having PHP5 + Fusion 4.5  And yes, there are a lot of these combos out there.
random_int function is not properly implemented.
I have been reported that creating an extension gets a blank extension, after researching I found the root cause.
PR #4460 tried to fix it properly, but you rejected it. This is an ugly patch following your style.

[4.5] Fixes the blank password issue

---

app/yealink/app_config.php

Allow swap button to be changed to 'hold', 'swap', or 2 buttons 'hold' and 'swap' on yealink phones. This is only a factor when there are 2 active calls.

allow yealink swap/hold button behaivor change

---

app/scripts/resources/scripts/fax_retry.lua

Added the following variables to the fax send email templates:
**${fax_time}**
Returns the date and time of the fax send based on the OS time. Formatted in 24h time format. e.g. 2022-12-01 13:01:44
**${fax_document_transferred_pages}**
Returns the number of pages transferred successfully.
**${fax_document_total_pages}**
Returns the total number of pages that was to be transferred.
**${fax_local_caller_id_number}**
Returns the outbound caller ID number of the sending fax server.
**${fax_image_resolution}**
Returns the resolution of the sent fax.
**${fax_duration}**
Returns a formatted version of the sent fax based on billsec. e.g. 20 billsec = 20s, 60 billsec = 01m 00s; 3600 billsec = 01h 00m 00s

Add variables to fax send email templates

---

app/dialplans/resources/switch/conf/dialplan/050_user_record.xml

Most recent PR on this file duplicated enabled statements causing the dialplan to be invalid and not be generated when running App Defaults.

Delete duplicate enabled="true" statements

---

app/dialplans/resources/classes/dialplan.php

Having a space before the opening of the PHP tag causes headers to be sent prematurely.

remove space before tag

---

app/call_forward/call_forward_edit.php

calls.php no longer exists as of recent updates. We are now redirecting to call_forward.php instead of calls.php file.

Resolve bug when saving CFWD settings

---

app/yealink/app_config.php

This is required for the Yealink template, currently the variable being set in the templates for DND is the call forward all variable which is incorrect. I will submit a separate pull request to update those yealink templates.

Add DND Variable to Yealink settings

---

resources/templates/provision/yealink/t54w/y000000000096.cfg

Resolve current issue with T54W template DND using the call forward all feature code. My other pull request adding the DND variable option will need to be accepted prior to this one.

Add DND Variable to Yealink T54W Template

---

app/extensions/extension_edit.php

When creating a new extension, under the Voicemail tab, Transcribe is empty. This was causing users to not receive VM transcriptions. Adding the above code will push transcribe = true or false (depending on the value in default settings) after creating a new extension.

Fix voicemail transcriptions not being pushed

---

core/domains/domains.php
resources/check_auth.php

This was a tricky one to find, but it was reported that IVRs were broken. After digging into why this was happening,  I found the v_dialplan.dialplan_context field was null.
dialplan_context Is fed from $_SESSION[[context] variable, which is not set in all use cases. 
This bug especially happens when you log into fusion using a URL that do not matches the username, for example, HTTP://1.1.1.1/ and using a username admin@mydomain
This could be the root cause of the well-known bug of ghost-dial plans that were very common in Fusion 4.2 and the bug from 4.4 where you clone a global dialplan and it was missing (but exists in the DB).
Fusion 5.0 and 4.4 are affected as well, I will send the PR soon.

Fixes NULL in _SESSION[context]

---

app/dialplans/resources/switch/conf/dialplan/080_user_hold_music.xml

If the aleg is an existing user, setting the hold_music on his leg causes the wrong hold_music to be used when he puts the other leg on hold.

[dialplans] don't set hold music if from user exists

---

resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml

Currently there is only one wallpaper variable used for all Snom phones. That works fine if you set a wallpaper on a per device level.
It doesn't work if you want to set the same wallpaper across the domain since some users may have different models of phone which might use a different resolution.
This PR hopes to fix that by maintaining the existing variable that users might be using as well as adding a few new ones for model specific wallpapers.
If a domain has just one model of phone they can keep using the old variable.

Snom templates - added per model wallpaper settings

---

app/scripts/resources/scripts/app/follow_me/index.lua

When a user has the Email Alerts for Missed Calls set, it works
As soon as there is a Follow Me configured, the email stops arriving
This patch restores the desired behaviour

Fix Missed Call email when Follow Me is On

---

resources/templates/provision/yealink/w60b/y000000000077.cfg
resources/templates/provision/yealink/w70b/y000000000146.cfg

Checked on the yealink cordless base and found a different variable for the time format

Update 12-24 hour variable

---

app/xml_cdr/xml_cdr_statistics_inc.php

LOSE_RACE is already being handled later `if (permission_exists('xml_cdr_lose_race'))`

[xml_cdr] LOSE_RACE handled in wrong place

---

app/devices/device_edit.php

If mac address and template already exists in Devices page and you attempt to associate the mac address with the extension from the extensions page, the "vendor" is removed from the device, thus causing provisioning not to look at the device profiles settings of the mac address

fix issue with device vendors

---

app/grandstream/app_config.php
resources/templates/provision/grandstream/grp2612/{$mac}.xml
resources/templates/provision/grandstream/grp2612w/{$mac}.xml
resources/templates/provision/grandstream/grp2613/{$mac}.xml
resources/templates/provision/grandstream/grp2614/{$mac}.xml
resources/templates/provision/grandstream/grp2615/{$mac}.xml
resources/templates/provision/grandstream/grp2616/{$mac}.xml
resources/templates/provision/grandstream/grp26xx/{$mac}.xml
resources/templates/provision/grandstream/gxp2130/{$mac}.xml
resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/gxp2140/{$mac}.xml
resources/templates/provision/grandstream/gxp2160/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml

@danry25 requested `grandstream_show_key_labels` to be configurable for P code `P8386`, I've also added it as a option through the UI along with the settings from a previous commit
- `grandstream_idle_mute_function`
- `grandstream_idle_mute_function_old`

Added grandstream_show_key_labels and other default values.

---

app/scripts/resources/scripts/app/follow_me/index.lua

The accountcode variable is used in a dialstring later on and if it comes back nil for any reason, then the following error is thrown:
```
2022-07-22 16:19:11.524674 [ERR] mod_lua.cpp:202 /usr/share/freeswitch/scripts/app/follow_me/index.lua:396: attempt to concatenate global 'accountcode' (a nil value)
stack traceback:
/usr/share/freeswitch/scripts/app/follow_me/index.lua:396: in main chunk
/usr/share/freeswitch/scripts/app.lua:48: in main chunk
```
This completely breaks follow-me.
This code sets the accountcode variable to the domain name if it comes back nil during script execution, thus protecting the script from failing with an empty accountcode value in the db or query.

Check to make sure accountcode has some value

---

resources/templates/provision/snom/D120/{$mac}.xml
resources/templates/provision/snom/D315/{$mac}.xml
resources/templates/provision/snom/D345/{$mac}.xml
resources/templates/provision/snom/D375/{$mac}.xml
resources/templates/provision/snom/D385/{$mac}.xml
resources/templates/provision/snom/D712/{$mac}.xml
resources/templates/provision/snom/D715/{$mac}.xml
resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D725/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D745/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml

This template parameter provides the ability to configure whether or not the phone provides a tone while the user is put on hold.
The default is to provide tone so I wrote the change to provide tone so there is no change in user experience.

adding template support for call waiting tone

---

resources/templates/conf/sip_profiles/internal.xml.noload

Parameter names have changed. See here: https://freeswitch.org/confluence/display/FREESWITCH/Sofia+Configuration+Files
When starting a profile, the following warnings would appear:
[WARNING] sofia.c:5332 rtp-hold-timeout-sec deprecated use media_hold_timeout variable.
[WARNING] sofia.c:5325 rtp-timeout-sec deprecated use media_timeout variable.
Updating the parameters fixes the issue.

Update deprecated sip profile params

---

app/fax/app_config.php
app/fax_queue/app_config.php
app/fax_queue/resources/job/fax_send.php
app/scripts/resources/scripts/app/fax/resources/scripts/hangup_tx.lua

This PR adds back some of the missing session variables that should be logged to v_fax_logs that were lost when fax_queue was rewritten. Additionally, it allows us to access variables logged in v_fax_logs in the fax email templates.
Here are details of the changes:
**Added two new db fields:**
* v_fax_logs - added fax_duration
* v_fax_queue - added fax_log_uuid
**hangup_tx.lua**
* Added back missing session variables needed to save to fax log that were lost when fax_queue was rewritten
* Added new session variable for fax_duration
* Now update fax_log_uuid to v_fax_queue when send is successful so we can access the log data later
**fax_send.php**
* Get the new fax_log_uuid variable
* We now query the db to get all the fax log data
* Add additional replacements to allow us to use these …

Add Fax Queue TX Email Variables

---

app/fax_queue/resources/job/fax_send.php

Variables `$fax_file_tif` and `$fax_file_pdf` are missing a period before the extension so file_exists is always evaluating to false. Thus, TIF was always sent. Adds the period back into the path so the check works correctly.
NOTE: `$fax_file_tif` is completely unused and can be removed from this code for cleanup.

Fix fax_queue to Email PDF Instead of TIF

---

resources/templates/provision/grandstream/ht814/{$mac}.xml

Fixes 2 issues:
1. if any password contains HTML special chars the XML breaks
2. This file doesn't use non-standard SIP port.

[ht814] Grandstream escape html and sip_port

---

resources/classes/database.php

Database setAttribute needs 2 parameters.

Fix PHP warning for PDO::setAttribute() requires 2 parameters

---

resources/classes/event_socket.php

Adjust timeout and enable blocking

Removed usleep command

---

app/contacts/resources/classes/contacts.php
app/dialplans/dialplan_edit.php
core/user_logs/resources/classes/user_logs.php
resources/classes/database.php

Added documentation for database class with clean up. Although the properties are set to private, they are still accessible because the __get method allows it. Removing case statements from the magic __get method will remove read access to the object properties. Some of them ie. password should be considered to be removed. Also, the db PDO object should be removed as to not allow access to the underlying PDO object.

Move database methods to static and document database class

---

resources/templates/provision/grandstream/gxp2100/{$mac}.xml

{if $account.1.sip_transport == 'udp'}P130 = 0{/if} {if $account.1.sip_transport == 'tcp'}P130 = 1{/if} {if $account.1.sip_transport == 'tls'}P130 = 2{/if} {if $account.1.sip_transport == 'dns srv'}P130 = 1{/if}
<P340>{$grandstream_enable_idle_screen_download}</P340> <P1349>{$grandstream_download_idle_at_boot}</P1349>

Update SIP Transport and Added Idle Screen vars

---

app/dialplans/resources/switch/conf/dialplan/890_local_extension.xml

Update local_extension fail_on_single_reject to handle stale registrations and other failures. Previously any failure mode would cause the call to drop to all.
So if a mobile app has a stale registration that times out when called, that leg fails with RECOVERY_ON_TIMER_EXPIRE and all other legs are cancelled and sent to voicemail.
This change handles 3 situations. All others should not fail the entire call to voicemail/forwarding.
1.  CALL_REJECTED - End User Rejects call - this means they hit cancel/end on their mobile app or desk phone. This reason should handle almost all phones. There may be edge cases that a phone doesn't conform and we can add those if discovered
2.  USER_BUSY - endpoint decides user is already on the phone - since we assume that an extension is a single person in …

Update local_extension fail_on_single_reject

---

app/dialplans/resources/switch/conf/dialplan/200_agent_status.xml
app/scripts/resources/scripts/app/agent_status/index.lua

When logging into call center from phone, index.lua only supports identity with agent_id.  We allow passing agent_name as well to assist with BLF configuration.

[call_center] Use agent_name or agent_id

---

app/scripts/resources/scripts/app/agent_status/index.lua

Agent log out from queue would have delayed lamp turn off. Solution credit:
https://www.pbxforums.com/threads/agent-status-blf.549/page-2#post-11458

[call_center] Add uuid to lamp turn

---

resources/templates/provision/yealink/t41p/{$mac}.cfg

I was having an issue where my T41P phones were getting provisioned with IPv4 & IPv6 - even though I specified in default settings yealink_ip_address_mode=0 for IPv4 only. Checked the y000000000036.cfg, which was setting it correctly. The issue was that {$mac}.cfg was overriding the correct setting. There were several instances of "network.ip_address_mode = 2" in this file, which specifies ipv4&ipv6. I changed all 5 of those entries in this file to pull from the default setting {$yealink_ip_address_mode} rather than just setting a static value of 2. I don't know why it has this listed in this file 5 times. But, this change resolved my issue and will force the T41P provisioning to follow FusionPBX default settings.

Update t41p {$mac}.cfg to correct IPv4 / IPv6 bug

---

app/devices/device_edit.php

The reason for this is the default behaviour for 'return' or 'enter' is to delete the device entirely. This makes using a barcode scanner impossible, or user error resulting in a lot of lost time.

Updated device_edit.php 'Save' to be a submit function for the form. 

---

app/dialplans/resources/switch/conf/dialplan/010_user_exists.xml

Adds 2 new variables to the user_exists dialplan:
* extension_effective_caller_id_name
* extension_effective_caller_id_number
This allows us to access these channel variables from the event socket and get the caller id name and number of the dialed extension when an inbound call comes in to that extension.

user_exists: Add effective_caller_id_name and effective_caller_id_number

---

app/xml_cdr/resources/classes/xml_cdr.php

This handles a future change to freeswitch that stores an array of bridge_uuids without breaking support for previous releases.

Support upcoming change in freeswitch - bridge_uuid changes to bridge_uuids array

---

app/xml_cdr/resources/classes/xml_cdr.php

So I discovered 2 things,
1. If a user adds the default config cdr-field-array with the content of a database field Let's pretend they want to show the xml_cdr_uuid column (for support purposes) - it could be any column (please don't argue with the column name, it is an example only), the SQL construction will fail as not Postgresql, Not MariaDB/MySQL allow having a column repeated twice. Adding array_unique() fixes this issue.
2. This one is for developers: If a developer wants to create more columns in the v_xml_cdr table and make them visible in the CDR app, common sense tells to add the default setting cdr-field-array to show it. As the code is now, this will look into the freeswitch variables and overwrite it with NULL. I am adding a condition that verifies if the value has been …

Make the XML CDR Importer more resilient

---

app/xml_cdr/app_config.php
app/xml_cdr/xml_cdr.php

Creating a status permission so status can be displayed independently from hangup cause. The combination of status within the hangup permissions has confused some conversations with admins and superadmins.

separating status and hangup permissions

---

app/scripts/resources/scripts/page.lua

Adding "mintwo" flag will tell the system that there has to be a minimum of two people in the conference to keep it open. This fixes the problem of when a user initiates a *8[ext] to someone and the far end hangs up and the initiator does not hang up the line they will hear hold music till they hang up.  Adding this will disconnect the intercom page if either party hangs up the call.

Fix page issue of hold music heard

---

app/dialplans/resources/classes/dialplan.php

In this condition you already have  p.dialplay_uuid = s.dialplay_uuid  and you have p.dialplay_uuid = CONST, no need tor s.dialplay_uuid=CONST,
if a = b, and a = c, then b = c
In small databases, this could be trivial; but in significant databases, this saves a lot of processing.

Remove redundant SQL condition

---

app/email_queue/resources/functions/transcribe.php

This updates the custom transcription endpoint to support async transcriptions. We've been running into issues with the old method were the connection would sometimes drop before the  transcribing is completed, which lead to users getting emails with no transcription. These changes allow for retrying on failure, and not depending on the initial request remaining open during transcription.

update custom transcription provider for async transcriptions and retry logic

---

app/provision/resources/classes/provision.php

When alternate device, the vendor should not be overwritten as this will break device profiles.

Keep device vendor when using alternate device

---

app/voicemails/resources/classes/voicemail.php
app/voicemails/voicemail_messages.php
app/xml_cdr/resources/classes/xml_cdr.php

Sometimes our users will encounter an invalid call recording or voicemail download URL, which currently displays a blank page. This adds some error messaging for users in those conditions.

Improve error handling when a recording download fails

---

app/fax_queue/resources/job/fax_send.php

The SQL query is missing the toll-allow setting from the virtual fax extension. All dialplans that have that condition will fail. This patch makes sure the variable is present if need it.

SQL query missing toll_allow

---

app/devices/device_edit.php

We are currently seeing some UI weirdness that seems to stem from the changes in #6409. The key subtype field is displayed and labeled "line", and all following field labels are shifted one to the left of what they should be, with the last field being unlabeled:
This PR fixes

Hide field for key subtype when $show_key_subtype is false

---

app/fax/app_languages.php
app/fax/fax_send.php
themes/default/css.php

Similarly to disabling extension registration and other functions, fax server sending should also be disabled for disabled domains. This prevents users from being able to send a fax and adds a warning message saying that sending is disabled.
Disabling of sending on disabled domains is accomplished in 2 ways:
- Preview and Send buttons are not rendered on the fax_send.php page
- POST data is not captured to prevent users from injecting the button back and completing the send that way
We have done regression testing to ensure that this does not break sending for users, admins or superadmins on domains which are still active.

Disable fax sending when domain is disabled

---

resources/templates/provision/yealink/t46s/{$mac}.cfg

This change is required to get OPUS working. It seem that Yealink may have changed their template structure a few years ago and the T46s was not updated. These changes are tested working with the latest T46s firmware which was released a while back.

Fixing Yealink T46s codecs in template

---

app/fax/fax_edit.php

$fax_email_outbound_authorized_senders is only filled when fax_extension_advanced permission is set. However, the edit part doesn't verify that sizeof(NULL) creates a fatal error.
Fatal error: Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/fusionpbx/app/fax/fax_edit.php:286 Stack trace: #0 {main} thrown in /var/www/fusionpbx/app/fax/fax_edit.php on line 286
This patch verifies that $fax_email_outbound_authorized_senders is an array before sizeof() evaluates it. You can now add faxes with the fax_extension_advanced disabled.

Fix adding Faxes

---

app/grandstream/app_config.php
resources/templates/provision/grandstream/grp2615/{$mac}.xml

This adds two variables to the Grandstream GRP2615 provisioning template that we would like to set.

Add support for XMLApp to grp2615 provisioning template

---

app/fax/app_config.php
app/fax/fax_files.php

Add fax_download_view permission to allow hiding the "File Name (Download)" column on Fax Inbox and Fax Sent pages. Some users prefer hiding this field as they also have the "View" column that they can click on to view and download PDFs of the faxes.

Add fax_download_view permission

---

app/extensions/extension_copy.php

When you copy an extension, it just uses the default algorithm for generate_password(). This includes the session variables for complexity and length to keep the extensions consistent.

Honor the settings for password complexity when copying extensions

---

core/install/resources/classes/install.php

The template for codec enable settings was taking a value as 1 if it was set in the settings. It was not taking the actual value inside it. So I have edited the templates to check the value if it's set to true.

T46U: enable/disable codec settings for all accounts

---

app/fax/app_defaults.php
core/authentication/app_defaults.php

A single space before the opening php tag was causing the headers to be sent

Frytimo pr fix headers already sent

---

core/upgrade/upgrade.php

allow default groups to be restored just before calling the permissions restore

restore any missing default groups when permissions are restored

---

app/call_broadcast/call_broadcast_edit.php

Fixed file import. Previously would import with \n separator instead of \r\n (in PHP 7.1), which breaks dialing.

Fix Call Broadcast file upload

---

resources/classes/event/handler/syslog.php
resources/classes/event/handler/virtual.php

php tags are missing from the beginning of the file. These do not seem like they are used but thought it important to have the tags there anyway.

Fix missing php tags

---

app/xml_cdr/xml_cdr_inc.php

so this small change has 2 purposes.
first, I found the hard way, that PHP PDO is not always coded with the same criteria between versions and databases.  While PDO PGSQL on PHP 8.x may work, PDO SQLITE on PHP 7.4 may not and so on.. This will make sure that the value there is an integer.
Second, since these two values are taken from the _GET, which is in the URL string, it will protect against "imaginative" users.

DB and protection

---

resources/templates/provision/grandstream/gxw42xx/{$mac}.xml
resources/templates/provision/grandstream/ht701/{$mac}.xml
resources/templates/provision/grandstream/ht702/{$mac}.xml
resources/templates/provision/grandstream/ht704/{$mac}.xml
resources/templates/provision/grandstream/ht801/{$mac}.xml
resources/templates/provision/grandstream/ht802/{$mac}.xml
resources/templates/provision/grandstream/ht814/{$mac}.xml
resources/templates/provision/grandstream/ht818/{$mac}.xml

This change allows us to override some grandstream provisioning options, specifically around in-call DTMF methods.

add template variables to override DTMF method on certain grandstream devices

---

app/call_forward/call_forward.php
app/call_forward/resources/classes/call_forward.php

Fix multiple PHP 8.1 warnings. Change class private vars to class constants so they can be accessed without an object instance. This will make it possible to get the _APP_UUID_ using the form _call_forward::APP_UUID_ and still have them protected from any changes. This could be used for app_defaults and app_config.

Php 8.1 call forward fixes

---

resources/templates/provision/snom/D717/{$mac}.xml

By Default, Snom D717 has the smartlabel display mode set to "short". Snom D717 has an issue where for short labels it doesn't take the label that we configure in devices. Instead, it tries to look for the value in the system and if it doesn't find a contact or extension associated, it will just show the number itself.

Updated Snom D717 template for setting the Smartlabel display mode

---

app/switch/resources/scripts/resources/functions/mkdir.lua

Add the / character to the ALLOWED_CHARS variable to fix bug with front slashes being stripped.
Previously was turning /var/lib/freeswitch into varlibfreeswitch

Add the / character to the ALLOWED_CHARS

---

app/time_conditions/time_condition_edit.php

Fix time conditions using 'minute-of-day' switching 1 minute early.
We are augmenting the value saved based on what select option is selected.
12:00 AM - 11:59 PM will now serialize as 1-1439 as expected 11:59 PM - 11:59 PM will now serialize as 1440-1439 which is unexpected behavior due to freeswitch's 'wrap around' behavior but acceptable.

Fix time conditions using 'minute-of-day' switching 1 minute early

---

app/switch/resources/scripts/intercept.lua

The channel table is not automatically flushed by FreeSWITCH when restarting, this will keep orphan records with time.
the ORDER will make sure that the code *97 will always get an existing UUID.

[5.1] Make intercept feature more fault tolerant

---

app/scripts/resources/scripts/intercept.lua

The channel table is not automatically flushed by FreeSWITCH when restarting, this will keep orphan records with time.
The ORDER will make sure that the code *97 will always get an existing UUID.

[5.0] Make intercept feature more fault tolerant

---

app/switch/resources/scripts/intercept.lua

The channel table is not automatically flushed by FreeSWITCH when restarting, this will keep orphan records with time.
The ORDER will make sure that the code *97 will always get an existing UUID.

Make intercept feature more fault tolerant

---

resources/templates/provision/grandstream/gxp2135/{$mac}.xml

GXP2135 requires special handling on keys to handle line key vs BLF/Speeddial vs blank.

Second try fixing line keys on GXP2135

---

resources/switch.php

Running `install.php` from a browser when no UI login users exist in the DB causes a failure due to `$_SESSION['switch']['conf']['dir']` not yet existing.  
To reproduce, install FusionPBX via the offical install script and then log into the UI and delete the superadmin user that was created so that no users exist.  Delete `/etc/fusionpbx/config.conf` to cause `install.php` to run and proceed to create a new user via the browser.  You will get a PHP failure on line 948 of `/var/www/fusionpbx/resources/switch.php` because the `$_SESSION` variable on that line does not exist.
Subsequent re-installs (by deleting `/etc/fusionpbx/config.conf`) will work if other login users already exist. It's only when there are no login users configured that it will fail.  There may be better ways to fix …

Fix initial `install.php` failure due to missing `$_SESSION` variable

---

logout.php

Allow administrators to set a custom default setting called `logout_destination` which will redirect the user to a destination of their choosing.
We also pass the PHP session ID after logout was completed to allow custom logic to be executed based on the session ID.

Add ability to set custom logout destination

---

resources/require.php

Ensures no trailing '/' and sets project_path after isset checks for value existing in the config then sets project_root

Reorder project path and project root defines

---

app/fax/fax_send.php

It doesn't make logical sense for **!empty($route_array)** to also have **count($route_array) == 0**. In a typical scenario, if an array is not empty, its count should be greater than 0.
The condition **!empty($route_array)** checks if the array is not empty, meaning it has at least one element, and therefore, **count($route_array)** should be greater than 0.

illogical condition specified in fax_send

---

app/switch/resources/scripts/eavesdrop.lua

If the extension is in a call and also receives calls at the same time, the query will return more than one uuid causing to eavesdrop the wrong channel.

[eavesdrop] Fix eavesdropping wrong uuid

---

app/switch/resources/scripts/app/voicemail/index.lua

The current condition #vm_disk_quota <= #message_sum is checking the lengths of vm_disk_quota and message_sum, not their actual values. So, it won't compare the numeric values for your intended logic.
If they're strings that can be safely converted to numbers, use tonumber():
if (vm_disk_quota and message_sum and tonumber(vm_disk_quota) <= tonumber(message_sum)) then
-- your code
end
This will compare them as numbers, ensuring that vm_disk_quota is less than or equal to message_sum.

Fix vm_disk_quota

---

app/devices/app_config.php
app/devices/device_edit.php

New device select permissions  allow greater flexibility  for limited  user groups have access to devices profile in view only mode.

New Devices  permissions  profile select and edit.

---

resources/classes/logging.php

Updated the logging class to:
- use the construct and destruct magic methods
- logging constructor now requires a path to the file that needs to be created
- automatic file and line detection from caller using the debug_backtrace function
- added methods **debug**, **info**, **warning**, **error** to avoid using toupper function
This will allow for much more flexible method of logging with a very simple syntax.

Update logging class

---

app/contacts/contact_edit.php

If there are contact permissions enabled, autoassign the current user (who is creating the contact via webinterface) as contact_user. Otherwise it could be possible, that the user who creates the contact would not be able to view it afterwards.

[ENHANCEMENT] Autoassign current user as contact_user

---

resources/footer.php

tmp_url scheme key may not have been set so use an empty statement instead of comparing to empty string

use empty check instead of string check to prevent php warning

---

resources/classes/event_socket.php

$line is already checked for content in the if block above so move it in there to avoid warning messages

move explode of $line inside of if block to fix php warning for line 93

---

app/system/resources/dashboard/system_counts.php

Getting all rows from the database caused PHP to exhaust the memory on systems with a huge amount of VM messages. This was fixed by querying from the database just the total counts.

[dashboard] Fix memory exhaustion on system counts

---

app/contacts/contact_edit.php

Prevent duplicate user allocation caused by https://github.com/fusionpbx/fusionpbx/pull/6837
Only assign the current user, if he is not already assigned.

Prevent duplicate user allocation

---

app/dialplans/resources/switch/conf/dialplan/240_page.xml
app/switch/resources/scripts/page.lua

This PR will add a feature to the paging function of FusionPBX.
This feature allows you to add _delay=true_ to the paging dial-plan to make it so the system will record an audio clip, then disconnect the caller, then play the audio clip over paging.
This was originally requested by a customer who has a speaker beside their work station for overhead paging and was getting feedback and echo when paging overhead. This solves that.
I made sure to make it compatible with users who do not have the _delay_ variable configured in-case their dial-plan is not updated.

added delayed paging

---

app/sip_status/cmd.php
resources/switch.php

Create function to force a port to be closed. This requires the `--enable-debug` flag to be used when compiling freeswitch, sofia-sip, and spandsp. This also requires gdb, pidof, netstat, and lsof to be installed on the system. This will not work on a Windows system. Tested on a raspberrypi. Tested system only required lsof to be installed manually with `apt install -y lsof` as the other tools were preinstalled.

Force close port

---

app/time_conditions/time_condition_edit.php

Use the existing default Variable time_format to adjust the options of the selects of "hours of day" and "time of day" accordingly.
We have been operating FusionPBX for our customers in Germany for several years. Over time, we have noticed many small things that the main user base probably does not notice. The AM and PM times are very unusual in Germany. Therefore I hope that this change will be accepted. There is already a default variable that lets you choose the time format. In my opinion, a user who selects 24 hours and activates the variable should no longer find AM PM times on the interface. If you notice this elsewhere, I would also try to fix it.

make time_condition_edit.php use time_format var for select options

---

app/fax/app_config.php

This permission is referenced in the fax_edit.php code and allows you to enter a confirmation email for faxes that are sent. Without this permission it is no editable.

added missing fax_email permission

---

app/extensions/extension_edit.php
app/voicemails/voicemail_edit.php

Voicemail transcribe always shows in the extensions even though it is disabled in default settings.

fix transcription bug showing when not enabled in default settings

---

resources/templates/provision/snom/PA1/{$mac}.cfg

Deleted elements which were making registrations page displaying device and firmware correctly. With the included elements the device and firmware displayed as "snomPA1/x.x.x". Removing the elements allows the device and firmware to display the installed firmware like "snomPA1/8.7.5.75".

Remove fields to display the installed firmware version

---

app/dialplans/resources/switch/conf/dialplan/030_is_loopback.xml

is_loopback dialplan was utilized by the dialstring follow me method. The code that generates the dialstring including the "is_follow_me_loopback" variable no longer exists, thus this dialplan will never be invoked.

Removed unused dialplan is_loopback

---

resources/classes/permissions.php

The error can cause a stack trace to dump causing a very large data dump. This ensures the session array exists before testing for temp value

after doing a database restore, the session may not yet exist

---

core/authentication/resources/classes/plugins/database.php

Variable `$user_email` missing from the object properties. Line 238 has `$this->user_email` causing php warning for dynamic creation. This resolves that error.

Bug user_email missing from object properties

---

resources/classes/sounds.php

On first iteration of the foreach loop, the variable $x was not yet initialized causing warnings. This fix removes the manual increment and uses the key / value pair syntax as the row is already indexed by numeric values starting at zero and incrementing by one.

fix $x was not initialized on first iteration of for loop

---

app/conference_centers/conference_center_edit.php

variable $conference_center_greeting was not initialized causing a PHP warning when it was a null value and accessed on line 367.

variable conference_center_greeting was not initialized causing warning

---

core/users/user_edit.php

Currently, the user_edit.php uses `$database = new database;` for each database action. This causes the database to re-initialize each time resulting in more overhead for the same operations. This PR will result in a single database object that is used throughout the user_edit view page.

use a single database instead of using new database in user_edit

---

app/conference_centers/conference_room_edit.php
app/conferences/conferences.php

if_group was used conferences causing the conferences not to show up for users that were not in the admin group but were assigned the permission to view conferences.

if_group caused no conferences to show when user not in the admin group

---

app/xml_cdr/resources/classes/xml_cdr.php

When call center is not enabled, during a standard call intercept sometimes we are seeing an error as follows: call_center_queue_uuid=-ERR%20No%20such%20channel!%0A cc_queue_joined_epoch=-ERR%20No%20such%20channel!%0A Normally it returns call_center_queue_uuid=_undef_ but occasionally shows the ERR message. When the epoch variable is set to this it causes the XML CDR service to continually stop and start at the same CDR which raises the CPU load on the server significantly until the CDR is deleted. This code fix will handle the ERR message in the same way as _undef_.

Handle ERR no such channel during call intercepts

---

core/upgrade/upgrade_menu.php

- Rename the option of 'Domains' to 'App Defaults' to better reflect the web interface. 
- Reorder the menu options to do schema before running defaults.

Rename domains to app defaults in menu

---

resources/templates/provision/snom/D735/{$mac}.xml

Snom D735 has a known issue where the lights on the phone won't illuminate when in use. It still functions correctly but without any lights. I talked with Snom support and they provided me with the string that needs to be changed in the template.
This issue started from Snom firmware version 10.1.127.10
Release Notes - https://service.snom.com/display/wiki/10.1.127.10+Release

Updated Snom D735 Template

---

app/extensions/app_config.php
app/extensions/extension_edit.php

The setting was hard coded. Moving it to be a default setting. If the default setting is not enabled or does not exist then extension edit page use the default behavior of value = 5.

Make extension concurrent outbound limit a default setting

---

app/fax/fax_emails.php

Fix: email should not be deleted when the sender is not authorized

Prevent deleting the email when fax sender is not authorized

---

app/snom/app_config.php
resources/templates/provision/snom/D712/{$mac}.xml
resources/templates/provision/snom/D715/{$mac}.xml
resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D725/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D745/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml
resources/templates/provision/snom/D812/{$mac}.xml
resources/templates/provision/snom/D815/{$mac}.xml
resources/templates/provision/snom/D862/{$mac}.xml
resources/templates/provision/snom/D865/{$mac}.xml

This settings is needed to allow the phones to work with intercom.
Without this paging does not work on Snom phones.

Adding snom_answer_after_policy default setting

---

app/fax/fax.php

fax_active is no longer used however, when upgrading from an older version, the permissions still exists. This causes some confusion on whether or not an upgrade has broken fax functionality. This bug fix simply checks for the file to exist (it should no longer exist) and only shows the link if the file is still present.

Add check for file fax_active.php to exist before showing link to page

---

app/dialplans/resources/classes/dialplan.php

fix sorting for dialplan details failing to save xml in proper order without re-saving

fix failing to save dialplan details xml in proper order

---

app/sip_status/sip_status.php

Exiting immediately causes the menu navigation to disappear and breaks the standard look of the page. By removing the exit statement the navigation is still available and the flash notification message shows to notify user that the connection is not available.

do not exit when unable to connect to freeswitch socket

---

app/snom/app_config.php
resources/templates/provision/snom/D712/{$mac}.xml
resources/templates/provision/snom/D715/{$mac}.xml
resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D725/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D745/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml
resources/templates/provision/snom/D812/{$mac}.xml
resources/templates/provision/snom/D815/{$mac}.xml
resources/templates/provision/snom/D862/{$mac}.xml
resources/templates/provision/snom/D865/{$mac}.xml

Snom phones by default display "emergency call" when you dial "911, 112, 110 or 999".
Since these are not emergency numbers everywhere, a setting has been made.
This setting allows emergency numbers to be dialed even when the phone is locked.
As an FYI, this settings change needs the phone to reboot to take effect.

added emergency numbers default settings for Snom

---

resources/templates/provision/snom/D712/{$mac}.xml
resources/templates/provision/snom/D715/{$mac}.xml
resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D725/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D745/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml
resources/templates/provision/snom/D812/{$mac}.xml
resources/templates/provision/snom/D815/{$mac}.xml
resources/templates/provision/snom/D862/{$mac}.xml
resources/templates/provision/snom/D865/{$mac}.xml

Snom's name directory was setup using <name>. This is considered to be the "nickname" on the phone.
Because of that, using Snom's directory to sort by first or last name never worked.
This PR will fix that by adding the <first_name> and <last_name> elements to the xml.
These elements became available in firmware version 8.2.16. This firmware is very old and is not even downloadable anymore from Snom so backwards compatibility wise we should be ok.

Snom first and last name fix in directory

---

resources/templates/provision/snom/D712/{$mac}.xml
resources/templates/provision/snom/D715/{$mac}.xml
resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D725/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D745/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml
resources/templates/provision/snom/D812/{$mac}.xml
resources/templates/provision/snom/D815/{$mac}.xml
resources/templates/provision/snom/D862/{$mac}.xml
resources/templates/provision/snom/D865/{$mac}.xml

This is a fix for when using the `$snom_emergency_numbers` default setting that was added in [PR6996](https://github.com/fusionpbx/fusionpbx/pull/6996).
More info can be found [here](https://service.snom.com/display/wiki/10.1.101.11+Release).
Snom basically produces a message on screen you do not have the default string. This PR makes it so that if the string is manually set, remove that message.

status message fix for emergency numbers Snom

---

app/devices/app_config.php
app/devices/device_edit.php
app/provision/app_config.php
resources/templates/provision/acrobits/default/qr_template.txt

This PR gives the ability to use Acrobits as a vendor and have Fusion generate a QR code on the device page.
Acrobits requires a default settings to be set for your global unique `CODE` which is acrobits specific.

Acrobits vendor support added

---

app/snom/app_config.php
resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D725/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D745/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml
resources/templates/provision/snom/D812/{$mac}.xml
resources/templates/provision/snom/D815/{$mac}.xml
resources/templates/provision/snom/D862/{$mac}.xml
resources/templates/provision/snom/D865/{$mac}.xml

This variable allows you to set a colour theme for the phones.
Valid Values are:
"Light", "Dark", "Colorful", "Industrial"

added snom_ui_theme variable to snom templates

---

resources/templates/provision/snom/D717/{$mac}.xml
resources/templates/provision/snom/D725/{$mac}.xml
resources/templates/provision/snom/D735/{$mac}.xml
resources/templates/provision/snom/D745/{$mac}.xml
resources/templates/provision/snom/D765/{$mac}.xml
resources/templates/provision/snom/D785/{$mac}.xml
resources/templates/provision/snom/D812/{$mac}.xml
resources/templates/provision/snom/D815/{$mac}.xml
resources/templates/provision/snom/D862/{$mac}.xml
resources/templates/provision/snom/D865/{$mac}.xml

Snom shows a warning whenever a headset is connected or when an expansion module is connected. This warning is presented above the missed calls notification which clutters up the view.
This warning is not needed and Snom provides a way to disable it. This should be disabled by default as there will likely be no one who wants a warning messaged that a peripheral has connected successfully.
This PR still allows the message to be present when there is an error connecting a peripheral.

blocked status messages on Snom for certain messages

---

resources/classes/database.php

fixes missing user_uuid in the database transaction logs table by setting the database object property user_uuid in the constructor

fix the user_uuid missing from transaction tables

---

app/email_queue/resources/command/send.php

This uses the settings default value to set smtp_from_name to be set to smtp_from if it does not have it's own value. The isset check on line 248 is no longer needed because smtp_from_name will always have a value

smtp_from_name was accidentally set to smtp_from

---

app/provision/resources/functions/device_by.php

There was a - instead of a = for the string concatenation that caused a bug.

bug fix in device_by.php

---

app/email_queue/resources/jobs/email_send.php

Add a class_exists check to ensure transcribe engine exists before attempting the use of the class.
Extend the if block to include the statements that use the object to ensure the object is not null. Otherwise, a null pointer exception will occur.

fix missing class exists check for transcribe engine

---

app/call_forward/call_forward_edit.php

By including the class manually with the include statement, the class has a possibility of loading twice. This will cause a fatal error if classes are already loaded.

remove the manual inclusion of classes to let autoloader handle it

---

resources/templates/provision/avaya/J169/{$mac}.cfg
resources/templates/provision/avaya/J179/{$mac}.cfg
resources/templates/provision/avaya/J189/{$mac}.cfg

This pull request makes any buttons programmed for the Avaya phones always start on button 4.
Avaya phones insist on having 3 line keys. There is no way that I can find to stop this behaviour.
What this means is that if I program a BLF as button 2, Avaya phones will then put the following on the phone:
1. Line Key
2. BLF
3. Line Key
4. Line Key
This change makes it so that any BLFs etc added start on line 4 so that it would look like this:
1. Line Key
2. Line Key
3. Line Key
4. BLF

fix for Avaya buttons

---

app/email_queue/resources/jobs/email_send.php

Class name requires the transcribe_ prepended before PHP checks to see if the class actually exists as the engine must have 'transcribe_' in front of the classes.

Ensure the 'transcribe_' is prepended to the class name

---

core/install/resources/classes/install.php

This is a fix for the install class for FreeBSD, NetBSD and OpenBSD.
The PHP_OS var does not return "BSD" on modern releases.

Fix for BSDs core classes

---

app/database_transactions/resources/classes/database_transactions.php
app/fax_queue/resources/classes/fax_queue.php
app/voicemails/resources/classes/voicemail.php
app/xml_cdr/resources/classes/xml_cdr.php
core/users/resources/classes/users.php

Update comparison checks when testing the database status and add unified log message with a more detailed message from the database when there is a failure

use loose comparison instead of strict comparison

---

app/dialplans/dialplans.php

The description under the Dialplans message is still using the if_group. This replaces the if_group call with a permission check for dialplan_edit instead.

replace if_group with dialplan_edit permission

---

app/fax_queue/resources/job/fax_send.php

This PR sets the `$fax_status = 'failed'` when the file cannot be found. Not doing this causes faxes with missing files to never get taken out of the fax queue.

set fax failed when missing

---

app/voicemails/voicemail_messages.php

When voicemail is called the first time, it correctly displays the list of voicemail messages. When it is called a second time the function returns an empty array and gives an empty display. This removes the second call to method 'messages' in 'voicemail' object.

voicemail messages function is called twice. second call removes list

---

app/voicemails/resources/classes/voicemail.php

If the settings object is not passed in the parameters the settings object that was created did not have the current domain uuid or user uuid set. This would cause default settings that were copied to the domain to be ignored. Ensuring the domain_uuid and user_uuid are initialized before the setting object and then passing them to the settings object constructor will make sure that the values would be returned when a request to the settings object is made.

update voicemail constructor to use domain and user uuids for settings

---

app/provision/index.php

It was found that the domain_filter was not working when provisioning devices. This can lead to conflicts if a device address is in multiple domains or a valid device address is sent for another domain. This enforces the check so that if http_domain_filter is enabled and the domain name does not match the device specified, it will reject the request.

honor the domain_filter setting in default settings

---

app/devices/app_languages.php
app/devices/device_download.php
app/devices/device_imports.php
app/devices/devices.php

Exporting devices with multiple lines did not show headers for extra columns if the first device listed only had a single line and the other devices had multiple lines. This adds a logical feature to export multiple lines for devices using the "duplicate column feature" so that the import feature can detect and import all lines for the device.

add multiple line export feature

---

secure/fax_to_email.php

Updates:
- use config object to find and load config file
- use single database object with config passed in constructor
- use settings object with database passed in constructor
- parse command line options with for loop so order no longer matters
- store all passed options in the super global $_REQUEST array for easy reference and debugging
- add debug and debug_level options for command line
- allow dumping the command line arguments when debug_level is 3 or higher
- add config option in command line to set location of config file
- add a shutdown function to allow for the exit command to be used but still output to either console or file
- add extra checks for options that are needed during runtime
- remove old PHP version 4 code
- add is_file check when checking for a valid .tiff …

remove all $_SESSION references and use single database object

---

resources/templates/provision/yealink/t27g/y000000000069.cfg
resources/templates/provision/yealink/t29g/y000000000046.cfg
resources/templates/provision/yealink/t41s/y000000000068.cfg
resources/templates/provision/yealink/t42s/y000000000067.cfg
resources/templates/provision/yealink/t46g/y000000000028.cfg
resources/templates/provision/yealink/t46s/y000000000066.cfg
resources/templates/provision/yealink/t48g/y000000000035.cfg
resources/templates/provision/yealink/t48s/y000000000065.cfg

These variables are used to set the Wifi credentials and settings on the below-listed Yealink models.
Only T54S/T52S/T48G/T48S/T46G/T46S/T42S/T41S/T29G/T27G Models support these parameters.
The variables were already configured for a couple of models, I just added them for all supported models.

Yealink Wifi Settings variables

---

core/authentication/resources/classes/authentication.php

Correct variable name to use when logging a cidr failed login attempt

fix authentication logging of cidr fail

---

resources/classes/permissions.php

The foreach loop must iterate over each item in the list to find the match. Using isset on the key name of the array allows it to use a hash table lookup to improve the lookup times for a permission. Currently, the permission name is not set if it does not exist for the current user.

Use isset in permission exists for improved efficiency

---

core/dashboard/index.php

Places a guard to check for the file existing before the file is included. Without the guard, PHP will stop with a fatal error.

fix dashboard break when app removed

---

app/switch/resources/scripts/page.lua

Updates the page.lua file to use sox if it is installed to get the length of the recorded file so that the 'recording_length=' is not necessary. Also makes an adjustment so that delay is auto set to true if the recording file is supplied.

add detect audio length of recording

---

app/xml_cdr/resources/classes/xml_cdr.php

Fixed CDR recording playback - casting an empty string to an int is breaking the if statement. This cast isn't required anyways because is_numeric will already find whether a variable is a number or a numeric string 
See https://php.net/manual/en/function.is-numeric.php

Fix CDR Recording Playback - Update xml_cdr.php

---

themes/default/css.php

This fixes the waveform image when hovering over it. Previously, it would zoom when hovering over it.
Here is an image when hovering on the waveform **BEFORE**:
Here is an image when hovering on the waveform **AFTER**:

fix waveform image background

---

app/avaya/app_config.php
resources/templates/provision/avaya/J139/{$mac}.cfg
resources/templates/provision/avaya/J169/{$mac}.cfg
resources/templates/provision/avaya/J179/{$mac}.cfg
resources/templates/provision/avaya/J189/{$mac}.cfg

This PR is to fix an issue with Avaya J series phones and BLFs.
When phones were configured to set their expiry past the freeswitch SIP profile's `nonce-ttl`, they would get 401'd.
This sets the expiry to 60 to match what Freeswitch works with. It is recommended to change the `nonce-ttl` on the SIP profile that the Avaya phones are registering to.
There is a default settings that allows this to be configured across all systems.

Fix Avaya BLF issue on reSUBSCRIBE

---

app/email_queue/resources/jobs/email_send.php

Ensured the values are of boolean type as PHP 7.1 treats them strange

fix email send breaks transcribe when php 7.1 is used

---

app/ring_groups/ring_group_edit.php

This PR fixes a bug that caused users who did not have the `ring_group_call_screen_enabled` permission to set the value to empty when saving a ring group

bug: fix call screen saving

---

app/fax/fax_emails.php

Use the singleton database object with database::new syntax Pass the connected database object to the settings object so settings object does not have to create another connection

pass database object to settings object

---

app/provision/app_config.php

This PR is to make contacts appear by default in all templates. Most users will find it confusing why contacts are not appearing when the web interface seems to be configured correctly.

contacts appear by default in templates

---

app/xml_cdr/xml_cdr_statistics.php

The sql aliases the calculation as cpm_answered. Without this change the CDR Statistics Call Per Minute will always be zero.
The Error:
The Fix:

update cpm_ans to be cpm_answered

---

app/xml_cdr/resources/classes/xml_cdr.php

xml_cdr service will crash when importing a record that does not contain a start epoch timestamp. This causes xml_cdr records to build up in the filesystem with occasional records being imported.

xml_cdr catch edge case of failed import when no start stamp is present

---

app/xml_cdr/resources/classes/xml_cdr.php

When an XML CDR record is zero bytes that is recorded in the /var/log/freeswitch/xml_cdr directory, the xml_cdr class would fail to move the file. This causes the record files to eventually build up to where the files can exceed the import limit. This adjustment moves the sanity checking for `filesize` to before the import attempt and checks for over limit and zero bytes. If those conditions match the file is moved to the "failed" folder.

fix xml_cdr import failing to move a zero byte record to failed folder

---

resources/header.php

The ini setting can only be modified when the session has not already started. This moves the ini_set function call inside the if block

fix php warning for ini set

---

resources/footer.php
resources/header.php

When 'dev' or 'all' error level is set in the config.conf file, the menu will fail to expand or contract. This commit adds the missing variable causing a PHP warning responsible for the behavior.

fix missing variable in default template

---

app/yealink/app_config.php

It was unclear as to what 'saving enabled' is. Updated to 'power saving enabled'. Yealink setting `features.power_saving.enable`

yealink power savings description clarity

---

app/switch/resources/conf/languages/en/vm/sounds.xml
app/switch/resources/conf/languages/en/vm/voicemail.xml
app/switch/resources/scripts/app/voicemail/index.lua
app/switch/resources/scripts/app/voicemail/resources/functions/listen_to_recording.lua
app/switch/resources/scripts/app/voicemail/resources/functions/main_menu.lua
app/switch/resources/scripts/app/voicemail/resources/functions/menu_messages.lua
app/switch/resources/scripts/app/voicemail/resources/functions/message_saved.lua
app/switch/resources/scripts/app/voicemail/resources/functions/remove_deleted_messages.lua
app/switch/resources/scripts/app/voicemail/resources/scripts/delete_messages.lua
app/voicemails/app_config.php

Instead of immediately deleting a voicemail simply mark the status of the message as _deleted_. Users can listen to "deleted" messages and undelete/forward them etc. 
There is a script that can be run from a cronjob that deletes any messages deleted longer ago than the new default setting, **deletion_queue_retention_hours**,  which I added to the voicemail app. 
This behaviour is helpful to prevent accidental deletions of a voicemail.
1. Added default settings **use_deletion_queue** and **deletion_queue_retention_hours** to the **voicemail** category. 
2. Added a **deleted** phrase for **voicemail_listen_file_options**.
3. Added option 3 in the main menu to listen to deleted messages.
4. Added ability for **menu_messages** to accept and query messages by any status.
5. Added ability to …

Add a voicemail deletion queue

---

app/event_guard/resources/service/event_guard.php

Event Guard already has a log table so no need to duplicate the transactions in another table

do not save event_guard logs to transactions

---

app/extensions/extension_edit.php

There are a few SESSION variables that are needed for the Back button, Domains, Destinations (to clear them), and a 'toll allow' (not snake case). I am unable to find any reference in the code where this is used so I left it unchanged. 
The following defaults have been placed at the top of the page are now loaded dynamically from the settings object:
- $limit_extensions
- $limit_devices
- $extension_limit_max
- $extension_call_timeout
- $extension_max_registrations
- $extension_password_length
- $extension_password_strength
- $extension_user_record_default
- $provision_path
- $provision_line_label
- $provision_line_display_name
- $provision_outbound_proxy_primary
- $provision_outbound_proxy_secondary
- $provision_server_address_primary
- $provision_server_address_secondary
- …

use settings object where possible

---

app/system/resources/dashboard/system_disk_usage.php

The name used in the chart would expand the wrong dashboard card. This has been fixed.
Added disk breakdown that is provided by the `df` command for Linux systems and FreeBSD systems. (Windows will need to be added).

Fix incorrect name on disk usage chart

---

app/devices/devices.php

When the 'Show All' button is clicked the display of devices is using the current domain name instead of the domain name that belongs to the device

bug fix domain name when using devices showall

---

app/destinations/destinations.php

This pull request adds the CID Name Prefix to the destinations page. It also includes searching for the CID Name Prefix and selecting the column header to sort A-Z and Z-A. No more entering every DID to view and note the prefix.

Add CID Name prefix to destinations.php

---

app/sip_status/sip_status.php
core/default_settings/default_settings_reload.php
core/domain_settings/domain_setting_edit.php
core/user_settings/user_setting_edit.php
resources/classes/auto_loader.php
resources/classes/cache.php
resources/classes/settings.php

When the PHP extension APCu is loaded, the settings class and the auto_loader will cache their results across requests in RAM. For more information about the APCu extension visit the PHP page: https://www.php.net/apcu

add the apcu caching ability for performance

---

resources/templates/provision/grandstream/grp2612/{$mac}.xml
resources/templates/provision/grandstream/grp2612w/{$mac}.xml
resources/templates/provision/grandstream/grp2613/{$mac}.xml
resources/templates/provision/grandstream/grp2614/{$mac}.xml
resources/templates/provision/grandstream/grp2615/{$mac}.xml
resources/templates/provision/grandstream/grp2616/{$mac}.xml

The loop used to populate the keys was using the incorrect variables. Updating the variable to same variables used for the memory keys 8 and higher resolved the issue of blank keys being set for keys 1 - 7.

update grandstream template loop

---

resources/classes/auto_loader.php

Forgot to remove the '!' (not) operator from the cache check when re-organizing the update cache function

fix wrong logical check

---

app/switch/resources/scripts/app/emergency/index.lua

Sending an email with the email templates will never work if the email template category is misspelled.
Search this URL for 'emergency' to confirm singular versus plural misspelling
https://github.com/fusionpbx/fusionpbx/blob/f3986290eaf3e3b65b792da803e21ff4969c0113/core/email_templates/app_defaults.php#L28

fix email category misspelling

---

app/registrations/resources/classes/registrations.php

Allow passing an event_socket in the constructor
Ensure the event_socket is connected before using it in loops
Helps to optimize loading/counting registrations when used on the Dashboard

Use single event socket object in registrations class

---

app/calls_active/app_config.php

Add new permissions to the active calls page so the fields can be removed from an admin permissions group to simplify the page, hiding more technical fields they probably will not find helpful.

add new active calls permissions

---

app/emergency/app_languages.php
app/emergency/emergency.php

I found it was important to know if an emergency call was successful. This pull request adds the status of the call to the emergency logs page so we can know if the call was successful or not.

add call status to emergency logs page

---

resources/templates/provision/grandstream/grp2612/{$mac}.xml
resources/templates/provision/grandstream/grp2612w/{$mac}.xml
resources/templates/provision/grandstream/grp2613/{$mac}.xml
resources/templates/provision/grandstream/grp2614/{$mac}.xml
resources/templates/provision/grandstream/grp2615/{$mac}.xml
resources/templates/provision/grandstream/grp2616/{$mac}.xml
resources/templates/provision/grandstream/gxp2130/{$mac}.xml
resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/gxp2140/{$mac}.xml
resources/templates/provision/grandstream/gxp2160/{$mac}.xml
resources/templates/provision/grandstream/gxp2170/{$mac}.xml

Original template uses the user_id field instead of the auth_id field to fill the value for authentication ID - which are usually the same value. However, this is not always the case so this patch will use the auth_id field to match in the UI.

Fix user id instead of auth id used in grandstream template

---

app/extensions/extension_edit.php

Using 'order by' in statement is not needed as the query only requires a single column of count. This causes an exception to be thrown and the $total_devices returned is an invalid result.

Fix exception thrown for order by used in count devices clause

---

app/dialplans/dialplans.php

If permissions to dialplans is given to anyone other than superadmin then they should not be able to see GLOBAL dialpans unless they have dialplan_all permission as well.

Hide global dialplans. Show to superadmin group that has dialplan_all permission

---

core/default_settings/default_settings.php

The $parameters array is not unset causing other $parameters arrays in the global namespace to have the 'search' parameter (line 188) to always be added to the query.

unset the parameters array

---

resources/templates/provision/grandstream/ghp6xx/{$mac}.xml

This PR includes a fix to the provisioning templates for Grandstream GHP6xx phones. May find others, but dnsMode and natTraversal should have been lowercase, not camel case.

Corrected case errors in provisioning template for Grandstream GHP6xx Series

---

resources/classes/auto_loader.php

When a cache miss happens, the auto_loader did not have the authentications plugins folder in the search path causing a class not found error.

add missing file path when cache miss in auto_loader

---

app/extensions/app_config.php

Change description of default setting to:
`Sets the default value for the "Limit Max" field that is required when adding a new extension`

Sets the default value for Limit Max field when adding a new extension

---

app/devices/device_edit.php

- Check the outbound_proxy_primary and outbound_proxy_secondary default value for an array value so the drop-down field on the device edit page can be filled.
- Use a variable to get the value from the settings class for server_address_primary and server_address_secondary instead of calling the settings class three times for each value.

Check outbound_proxy and server_address for array with drop-down field

---

app/extensions/extension_edit.php

This pull request fixes the code for adding extensions and a device is added to the extension.
These device fields are populated if they are defined and enabled in default settings. This works if the data types = text (the default) and it works if the data types = array (very useful for server clusters). The code also fixes 2 misspellings of 'primary' versus 'secondary' which was a small part of the problem of the values not being populated correctly.

Update extension_edit to populate device servers

---

resources/classes/settings.php

After the clear cache static method is called, re-create the settings object so the settings object remains available and settings are re-cached for subsequent calls

Update clear cache method for settings object

---

resources/classes/auto_loader.php

When matching the file name of the plugins in the authentication plugin folder they do not match. This causes auto loader not to find and load the class.

Fix plugin class name mismatch in auto loader

---

core/default_settings/default_setting_edit.php

When a setting is modified, the settings cache can be reloaded allowing the setting that was modified or added to take immediate effect. The call to allow any other clear cache methods to be called will allow any new features to have their settings also take effect. The settings are first cleared though so that any of the other classes that may require updated settings to work with, ensure that they have the newest default setting values.

Add clear settings object cache when modifying or adding setting

---

app/yealink/app_config.php

This variable allows automatic provisioned Yealink devices to dim the backlight after X seconds. Disabled by default for same operations as without the default setting variable. The Yealink automatic provisioning templates have this variable defined as:
`phone_setting.backlight_time = {$yealink_backlight_time}`

Add yealink_backlight_time to default settings -> provision section

---

app/switch/resources/scripts/directory.lua

When the directory name set the extension is two characters such as DJ or Yu, the lookup will fail to match the name. This will adjust the script so that the first and last name will match on the number of characters in the directory.

Fix two character directory name lookup

---

resources/classes/event_socket.php

Check that the current socket in the object is false before trying to create a new socket

Do not create a new socket when one is provided

---

resources/functions.php

FreeBSD verison of get_memory_details() incorrectly append a '%' sign, which breaks the round() call in system status dashboard

Fix FreeBSD system memory calculation

---

app/yealink/app_config.php

Removed the leading $ from the variable

Fix mispelling in yealink_firmware_t44w

---

app/voicemails/resources/classes/voicemail.php

This PR is to prevent orphaned data when deleting a voicemail box that is used as a forward destination in another voicemail box.

Prevent orphaned data in voicemail destinations

---

resources/templates/provision/grandstream/ht801/{$mac}.xml
resources/templates/provision/grandstream/ht802/{$mac}.xml

HT801 & HT802
The firmware upgrade protocol was hard coded as https. Updated to use default settings variable.

Grandstream - use variable for firmware upgrade protocol

---

resources/templates/provision/grandstream/ht802/{$mac}.xml

Allow device to not revert back to DHCP on reboot and keep manually entered static IP.

Allow device to not revert back to DHCP on reboot and keep manually entered static IP.

---

resources/templates/provision/groundwire/default/{$mac}.xml

This applies to users in the United States. When a user dials 911 or 933 (commonly used for 911 testing) from the Groundwire app, the call is automatically placed using the device's cellular service. This approach can enhance location accuracy for emergency services and ensure more reliable call completion.

Force Groundwire to use GSM/LTE for emergency calls

---

app/xml_cdr/resources/classes/xml_cdr.php

Within my environment, CDR's stopped being written to the db after a `git pull` on 12-April-2025. Under the hood, CDR imports appear to have been silently failing when `http_enabled` is set to `true` due to inverted authentication logic. 
Line 1706 was checking `if (http_enabled)` when it should check `if (!http_enabled)` to deny access only when HTTP is 
disabled.
Added missing negation operator (`!`) to fix the authentication logic.
- Proposed fix resolves silent CDR import failures
- Tested with both staging and production environments
- Confirmed HTTP POST authentication now works correctly
This affects at least one FusionPBX installation using HTTP POST for CDR imports with `http_enabled=true`. I do not have access to enough systems to know if "flipping the bit" might introduce …

Fix CDR HTTP authentication logic bug

---

app/grandstream/app_config.php
resources/templates/provision/grandstream/gxp2135/{$mac}.xml
resources/templates/provision/grandstream/ht801/{$mac}.xml
resources/templates/provision/grandstream/ht802/{$mac}.xml

Added configurable SNMP settings to Grandstream HT801, HT802, and GXP2135 provisioning template. Includes enable/disable toggle, SNMP version selection (default v2c), and community string configuration. SNMP is disabled by default
for security.

Add SNMP configuration support for Grandstream HT801,HT802 and GXP2135

---

resources/classes/groups.php

Setting the name and uuid when the groups object is created causes the database transactions to almost always show that it was the groups object that made the changes.

Remove setting name and uuid for groups object

---

app/call_forward/call_forward_edit.php

We are currently saving the empty fields for the destination for each switch, but it's not functioning correctly. Now, we are simply preventing saving when there is no destination.
https://github.com/user-attachments/assets/e340f9ba-ac94-468d-8018-9edf99c2bfb4

call_forward fix saving proccess with empty inputs

---

resources/classes/auto_loader.php

This patch will stop the auto_loader from adding the same class to the interface list when they have already exist in the list.

fix auto_loader duplicate classes in interface list

---

app/xml_cdr/resources/classes/xml_cdr.php

When a call is blocked, it was still showing in the CDRs. This fix corrects the condition used to check for call block in default settings.

Fix call block save call detail record condition

---

app/active_calls/resources/classes/active_calls_service.php
app/system/resources/classes/system_dashboard_service.php
core/websockets/resources/classes/base_websocket_system_service.php
core/websockets/resources/classes/websocket_client.php
core/websockets/resources/classes/websocket_service.php

When reading web socket data, the loop will run forever if there is no more data available in a chunk. This fix will add a counter to how many times it tries to read before a timeout is reached.
Fixed a problem where the constructor parameter for permission_filter was not being fulfilled. This can cause a crash also leading to the read of web socket data to begin looping.
Added better debugging information by using the topic of the websocket_message instead of the payload data. This would cause some messages to appear empty when they were not.
Added a wait state for re-connecting to the web socket server for system status service so it would not exit immediately when the websocket server exited.
Added more PHPDoc Block information.

Fix bug by adding a 'tries' counter so reading websocket data can return

---

app/fax_queue/resources/job/fax_send.php

When fax_send queries the database for a matching record using the fax_queue_uuid and does not return with a record, this will exit immediately and put a message in the syslog.

Exit fax_send immediately if no fax_queue_uuid is found

---

resources/classes/service.php

Fixed process id not detected
Process Signals are not using numbers instead of their constant. PHP-FPM does not pre-declare the constants.

Fix pid detection in service class

---

app/system/app_config.php
app/system/resources/classes/system_dashboard_service.php
core/websockets/resources/classes/base_websocket_system_service.php

Allow timers to be set for different intervals for the dashboard web socket items.
- Add multiple timers
- Add default setting for network status
- Add default setting for cpu status
- Fix copy/paste error for setting on_network_status callback

Create multiple timers for system status
